import type { FoundationLanguage } from "./multilingual-foundation";
import { requiredScriptModes, scriptRequirements, type ScriptStrand, type ScriptTaskMode } from "./script-literacy";

/** Authored review material, not editorially approved course availability. */
export type ScriptLesson = {
 id: string; title: string; explanation: string; example: string; meaning: string;
 prompt: string; answer: string; alternatives: string[]; prerequisites: string[];
 strand: ScriptStrand; modes: ScriptTaskMode[]; components: string[];
};
export type ScriptCourse = { language: FoundationLanguage; revision: 3; status: "release-foundation"; explanationLanguage: "en"; convention: string; inventory: string; requirements: typeof scriptRequirements[FoundationLanguage]; lessons: ScriptLesson[] };
type Row = readonly [id: string, title: string, explanation: string, example: string, meaning: string, prompt: string, answer: string, ...alternatives: string[]];
function course(language: FoundationLanguage, convention: string, inventory: string, rows: Row[]): ScriptCourse {
 if (language === "vi" && rows.some((row) => row.slice(3).some((value) => /[Ðð]/u.test(value)))) throw new Error("Vietnamese course contains a non-Vietnamese eth character; use Đ or đ.");
 return { language, revision: 3, status: "release-foundation", explanationLanguage: "en", convention, inventory, requirements: scriptRequirements[language], lessons: rows.map((r, i) => ({ id: `${language}-script-${r[0]}`, title: r[1], explanation: r[2], example: r[3], meaning: r[4], prompt: r[5], answer: r[6], alternatives: r.slice(7), prerequisites: i ? [`${language}-script-${rows[i - 1][0]}`] : [], strand: /input|keyboard|pinyin/i.test(r[0]) ? "input" : /block|component|join|conjunct|final|cluster/i.test(r[0]) ? "composition" : /tone|sound|vowel|consonant|voice|stress/i.test(r[0]) ? "sound-system" : /sentence|question|punctuation/i.test(r[0]) ? "sentences" : "orthography", modes: [...requiredScriptModes], components: Array.from(r[6].normalize("NFC")) })) };
}
const latin = "A a · B b · C c · D d · E e · F f · G g · H h · I i · J j · K k · L l · M m · N n · O o · P p · Q q · R r · S s · T t · U u · V v · W w · X x · Y y · Z z";
export const scriptCourses: Record<FoundationLanguage, ScriptCourse> = {
 en: course("en", "Modern English; spelling variants require explicit acceptance", latin, [
  ["case", "Two forms, one letter", "English letters have uppercase and lowercase forms. A capital begins a sentence or a proper name. The first-person pronoun I remains a capital even inside a sentence. Uppercase does not mean a different word by itself.", "I live in Canada.", "A statement about where the speaker lives.", "Write the English first-person pronoun with its required capitalization.", "I", "i", "l"],
  ["boundaries", "Give words their space", "A space marks a word boundary. A name can contain more than one word. Keep New and York separate; joining them changes the conventional written name. Line wrapping should happen between words, not by inserting a space inside one.", "New York", "The place name has two written words.", "Write the two-word place name New York with conventional spacing.", "New York", "NewYork", "New  York"],
  ["apostrophe", "A visible omission", "An apostrophe can show that letters have been omitted in a contraction. I am becomes I'm: the apostrophe belongs between I and m. Do not add an apostrophe merely because a word ends in s.", "I'm ready.", "I am ready.", "Write the contraction of I am, using a straight apostrophe.", "I'm", "Im", "I m"],
  ["sentence", "Finish the written thought", "A statement begins with a capital and normally ends with a full stop. A question uses a question mark. Here we are practising written form, not judging spoken pronunciation or speed.", "I am ready.", "A complete written statement.", "Write I am ready as a complete statement with its capital and full stop.", "I am ready.", "i am ready.", "I am ready"],
 ]),
 es: course("es", "Modern Spanish; preserve ñ, accents and paired punctuation", `${latin} · Ñ ñ`, [
  ["enye", "Ñ is a letter", "The tilde makes ñ a different letter from n. It is not an optional decoration. España contains ñ. A keyboard that produces only n is not yet sufficient for this word; use its ñ key or language-specific input.", "España", "Spain.", "Write the name España, retaining its distinctive letter.", "España", "Espana", "Espána"],
  ["accent", "A mark can distinguish meaning", "The affirmative sí has an acute accent. Unaccented si commonly means if. The mark remains necessary even when the context seems obvious. This is a spelling distinction, not a test of your microphone or accent.", "Sí, gracias.", "Yes, thank you.", "Write the Spanish affirmative yes in lowercase.", "sí", "si", "sì"],
  ["diaeresis", "Two dots have a purpose", "In written güe and güi, the diaeresis indicates that u participates in the pronunciation. In vergüenza, retain both dots. This written cue is distinct from an acute accent; neither substitutes for the other.", "vergüenza", "Shame or embarrassment.", "Write vergüenza with its diaeresis.", "vergüenza", "verguenza", "vergúenza"],
  ["questions", "Mark both ends of a question", "Spanish direct questions use an opening inverted question mark and a closing question mark. The interrogative dónde carries an accent. These marks clarify the structure before the reader reaches the end.", "¿Dónde está?", "Where is it?", "Write the complete question ¿Dónde está? with both punctuation marks and accents.", "¿Dónde está?", "Dónde está?", "¿Donde esta?"],
 ]),
 vi: course("vi", "Modern Vietnamese orthography; retain vowel and tone distinctions", "A a · Ă ă · Â â · B b · C c · D d · Đ đ · E e · Ê ê · G g · H h · I i · K k · L l · M m · N n · O o · Ô ô · Ơ ơ · P p · Q q · R r · S s · T t · U u · Ư ư · V v · X x · Y y", [
  ["letters", "Đ is a distinct Vietnamese letter", "Vietnamese distinguishes D d from Đ đ. The crossbar is part of the letter, not a stylistic mark. Lowercase đ begins đường; plain d is a different Vietnamese consonant. The uppercase and lowercase forms must also remain distinct in writing.", "đường", "Road; also sugar in another context.", "Choose the crossed lowercase Vietnamese letter used at the beginning of đường.", "đ", "d", "Đ"],
  ["tones", "Six written tone patterns", "A syllable can have no tone mark, a grave, acute, hook, tilde or dot below: a, à, á, ả, ã, ạ. The unmarked pattern is also meaningful. In bạn, the dot belongs below a; removing it does not preserve the same written word.", "bạn", "Friend; also a form of address in suitable contexts.", "Write bạn, preserving the dot below the vowel.", "bạn", "ban", "bán"],
  ["combined", "Vowel shape and tone can coexist", "A vowel letter may carry both its shape mark and a tone mark. In tiếng, ê retains its circumflex and also carries the acute tone mark. Entering plain e or only one mark does not reproduce the word.", "tiếng Việt", "Vietnamese, as a language name.", "Write tiếng with both the vowel-shape mark and tone mark.", "tiếng", "tiêng", "tiéng"],
  ["input", "Type the written word, not the keystroke recipe", "Telex and VNI are input methods, not alternative Vietnamese spellings. The keyboard converts a sequence of keys into marked text. Judge the final visible word. Keep the syllables in Việt Nam separated by a space.", "Việt Nam", "Vietnam.", "Write Việt Nam with its marks, capitals and space.", "Việt Nam", "Viet Nam", "ViệtNam"],
 ]),
 fr: course("fr", "Modern French; retain accents, ligatures and apostrophes", `${latin} · À à · Â â · Ç ç · É é · È è · Ê ê · Ë ë · Î î · Ï ï · Ô ô · Ù ù · Û û · Ü ü · Œ œ · Æ æ · Ÿ ÿ`, [
  ["accent", "Accents belong to the spelling", "French uses different marks, including acute, grave and circumflex accents. They are not interchangeable. Café ends in é. Capitalization does not justify dropping an accent from a letter.", "café", "Coffee; also a café.", "Write café with its acute accent.", "café", "cafe", "cafè"],
  ["meaning", "A small mark, a different function", "Où means where; ou means or. The grave accent distinguishes their written functions. Learn the word with its mark instead of treating the plain letters as a complete spelling.", "Où est la gare ?", "Where is the station?", "Write the lowercase word meaning where.", "où", "ou", "oú"],
  ["cedilla", "Keep the cedilla", "The cedilla in ç modifies the written c. In français it is required. The ligature œ appears in words such as cœur; it is another written form worth learning, not a reason to replace ç with plain c.", "français · cœur", "French · heart.", "Write français with its cedilla.", "français", "francais", "françois"],
  ["elision", "An apostrophe joins the written expression", "Before certain vowel-initial words, a short word loses its final vowel and an apostrophe marks the omission. Je m'appelle contains the contracted form m'. Do not insert a space inside that contraction.", "Je m'appelle Alex.", "My name is Alex.", "Write m'appelle using a straight apostrophe and no internal space.", "m'appelle", "m appelle", "mappelle"],
 ]),
 pt: course("pt", "Brazilian Portuguese examples; regional alternatives require authored notes", `${latin} · Á á · Â â · Ã ã · À à · É é · Ê ê · Í í · Ó ó · Ô ô · Õ õ · Ú ú · Ç ç`, [
  ["acute", "Keep the acute accent", "Portuguese written accents distinguish forms and guide reading. Olá has an acute accent on its final a. Omit it and you have not reproduced the conventional greeting. Letter recognition and pronunciation remain separate assessments.", "Olá.", "Hello.", "Write the greeting Olá with its accent, without punctuation.", "Olá", "Ola", "Olà"],
  ["tilde", "The tilde marks a vowel feature", "The tilde in não belongs to the vowel and must remain in ordinary text. It is different from an acute or circumflex accent. The combinations ão and õe occur in many words and need practice in context.", "não", "No; not.", "Write não with its tilde.", "não", "nao", "náo"],
  ["cedilla", "Distinguish ç from c", "A cedilla changes how written c is read before a, o or u. In coração, both ç and ã are required. Practise the entire word so its marks are retained together.", "coração", "Heart.", "Write coração with both required marks.", "coração", "coracao", "coraçao"],
  ["grave", "À is not plain a", "The grave accent in à conventionally marks a contraction involving the preposition a and a feminine article or another compatible a-form. It is not a general emphasis mark. Preserve it in the phrase supplied here.", "Vou à escola.", "I go to school.", "Write the marked one-letter form from Vou à escola.", "à", "a", "á"],
 ]),
 de: course("de", "Standard German with ß; Swiss ss variants need explicit contextual acceptance", `${latin} · Ä ä · Ö ö · Ü ü · ẞ ß`, [
  ["umlaut", "The two dots are not optional", "German distinguishes a, o and u from ä, ö and ü. The umlaut is part of the written form. Here, ü in für must be retained. Keyboard substitutions may exist in restricted systems, but this exercise teaches the normal spelling.", "für", "For.", "Write für with its umlaut.", "für", "fur", "fúr"],
  ["eszett", "Learn ß as a written form", "In the convention used here, Straße contains ß. It is not the Greek letter beta. Swiss standard spelling uses ss instead; that is a regional convention, not proof that all occurrences of ß and ss are freely interchangeable.", "Straße", "Street.", "Write Straße using the convention taught in this unit.", "Straße", "Strase", "Straβe"],
  ["capitals", "Nouns begin with capitals", "German capitalizes nouns in ordinary sentences, not only at the start. Sprache is a noun. Its capital S carries a grammatical writing convention; copying it in lowercase misses that convention.", "die Sprache", "The language.", "Write the noun Sprache with its conventional capitalization.", "Sprache", "sprache", "SPRACHE"],
  ["compounds", "One compound, one written word", "German often joins the parts of a compound noun. Bahnhof is written as one word. Compound formation is not permission to join every adjacent word: learn each form in context.", "der Bahnhof", "The railway station.", "Write Bahnhof as one capitalized word.", "Bahnhof", "Bahn hof", "bahnhof"],
 ]),
 it: course("it", "Modern Italian; j, k, w, x and y occur particularly in borrowed words and names", latin, [
  ["accent", "An accent can distinguish a word", "È means is, whereas e means and. The grave accent is part of the written distinction. Use the accented character itself rather than a plain E followed by an apostrophe.", "È importante.", "It is important.", "Write lowercase è, meaning is.", "è", "e", "é"],
  ["acute", "Not every accent points the same way", "The conventional spelling perché ends in é, with an acute accent. Do not replace all Italian accents with one generic mark. Learn the written form with the word.", "perché", "Why; because, depending on context.", "Write perché with its conventional accent.", "perché", "perchè", "perche"],
  ["double", "A doubled consonant matters", "Italian distinguishes words with single and double consonants. In anno, both n letters are required. Ano is a different word. A spelling check should not silently collapse repeated letters.", "un anno", "One year.", "Write anno, the word for year.", "anno", "ano", "annno"],
  ["apostrophe", "Keep elision visible", "In l'amico, the article is elided before the vowel. The apostrophe marks that written relationship; it is neither a space nor an accent attached to a letter.", "l'amico", "The male friend.", "Write l'amico with a straight apostrophe.", "l'amico", "lamico", "l amico"],
 ]),
 zh: course("zh", "Simplified Chinese teaching forms; pinyin is a reading aid, not character mastery", "一 丨 丿 丶 · 人 亻 · 口 · 日 · 月 · 木 · 水 氵 · 你 好 我 中 国 学 生", [
  ["characters", "Characters and words are different units", "A Chinese word can contain one or several characters. 中国 contains two characters and forms the word China. Ordinary Chinese does not insert a space between each character. A character inventory must grow with the course, not end with this example.", "中国", "China.", "Write 中国 as ordinary Chinese text without an inserted space.", "中国", "中 国", "中国国"],
  ["components", "Look inside the character", "In 你, the left component is 亻, a form related to 人. Components help distinguish and remember forms; they do not guarantee a whole character's meaning or pronunciation. Learn 你 as the complete written word here.", "你", "You, singular.", "Write the complete character meaning you in this example.", "你", "亻", "人"],
  ["pinyin", "Retain tone notation in the reading aid", "Pinyin uses Latin letters and tone marks. In nǐ, the third-tone mark belongs to i. This helps interpret written pronunciation guidance; typing pinyin is not the same achievement as producing 你, and this silent exercise does not certify spoken tones.", "你 · nǐ", "You, with its pinyin reading aid.", "Write nǐ with its tone mark, not the Chinese character.", "nǐ", "ni", "ní"],
  ["input", "Choose the intended character candidate", "A pinyin keyboard can offer several candidates for the same typed syllable. Inspect the final characters after conversion. 我 is the first-person pronoun here; the Latin input wo is only a route to that character, not the required written answer.", "我", "I; me.", "Enter the character 我, not its pinyin input sequence.", "我", "wo", "wǒ"],
  ["punctuation", "Chinese punctuation has its own forms", "The ideographic full stop 。 is used at the end of an ordinary Chinese statement. It is distinct from the small Latin full stop. Learn punctuation with the sentence rather than treating all marks as disposable.", "你好。", "Hello, written with an ideographic full stop.", "Write 你好。 with the punctuation taught here.", "你好。", "你好.", "你好"],
 ]),
 ja: course("ja", "Modern Japanese; basic kana plus a growing contextual kanji strand", "あいうえお かきくけこ さしすせそ たちつてと なにぬねの はひふへほ まみむめも やゆよ らりるれろ わをん · アイウエオ カキクケコ サシスセソ タチツテト ナニヌネノ ハヒフヘホ マミムメモ ヤユヨ ラリルレロ ワヲン", [
  ["systems", "Three scripts work together", "Japanese combines hiragana, katakana and kanji. Hiragana commonly writes grammatical elements; katakana often writes borrowed words and foreign names. Kanji supplies many content words. These are interacting systems, not three interchangeable decorative fonts.", "カナダ", "Canada, written in katakana.", "Write カナダ in katakana.", "カナダ", "かなだ", "カナタ"],
  ["voicing", "Small marks distinguish kana", "The two-stroke dakuten changes a kana's reading: か becomes が. The circular handakuten is used with the h-row, as in ぱ. Preserve the mark in かぎ; it is part of the word.", "かぎ", "Key.", "Write かぎ with its dakuten.", "かぎ", "かき", "かぴ"],
  ["small-tsu", "Small っ is not full-sized つ", "The small っ marks a consonant-length distinction in many words. In きって, it is smaller than ordinary つ. Simply adding a full-sized つ produces a different written sequence.", "きって", "Postage stamp.", "Write きって using small っ.", "きって", "きつて", "きて"],
  ["combinations", "Size changes the combination", "Small ゃ, ゅ and ょ combine with certain preceding kana. In きゃ, the second kana is small. Do not assume every visual sequence of two kana has the same reading as a contracted combination.", "きゃく", "Guest; customer.", "Write きゃく with small ゃ.", "きゃく", "きやく", "きゅく"],
  ["long-vowels", "Keep the katakana length mark", "Katakana often marks a long vowel with ー. コーヒー contains two such marks. The mark is not a hyphen, and omitting it fails to preserve the conventional spelling.", "コーヒー", "Coffee.", "Write コーヒー with both long-vowel marks.", "コーヒー", "コヒ", "コ-ヒ-"],
 ]),
 ko: course("ko", "Modern South Korean Hangul orthography", "ㄱ ㄲ ㄴ ㄷ ㄸ ㄹ ㅁ ㅂ ㅃ ㅅ ㅆ ㅇ ㅈ ㅉ ㅊ ㅋ ㅌ ㅍ ㅎ · ㅏ ㅐ ㅑ ㅒ ㅓ ㅔ ㅕ ㅖ ㅗ ㅘ ㅙ ㅚ ㅛ ㅜ ㅝ ㅞ ㅟ ㅠ ㅡ ㅢ ㅣ", [
  ["blocks", "Letters form a syllable block", "Hangul combines consonant and vowel letters into a block. ㄱ and ㅏ form 가. The individual letters are useful for analysis, but ordinary Korean text uses the composed block, not a line of disconnected compatibility letters.", "가", "The syllable ga; its meaning depends on the word or grammatical context.", "Compose ㄱ + ㅏ as one Hangul syllable block.", "가", "ㄱㅏ", "나"],
  ["orientation", "The vowel guides the layout", "With a vertical vowel such as ㅏ, the consonant sits to its left. With a horizontal vowel such as ㅗ, the consonant sits above it. ㄱ and ㅗ form 고. Both layouts remain one syllable block.", "가 · 고", "Two syllables with different vowel layouts.", "Compose ㄱ + ㅗ as one block.", "고", "가", "ㄱㅗ"],
  ["placeholder", "Initial ㅇ can hold a position", "A Hangul block needs an initial position. When a syllable begins with a vowel, initial ㅇ fills that position without representing an initial consonant sound. Its final-position role is different. 우유 contains two vowel-initial blocks.", "우유", "Milk.", "Write 우유 as two composed syllable blocks.", "우유", "ㅜㅠ", "우 유"],
  ["final", "A final consonant goes below", "A final consonant occupies the bottom of a syllable block. Add ㄴ below 하 to form 한. Do not place it beside the completed block as a separate letter. Written composition and spoken realization are assessed separately.", "한", "The syllable han, used in 한국, Korea.", "Compose ㅎ + ㅏ + ㄴ as one block.", "한", "하ㄴ", "하"],
  ["double", "Doubled initials distinguish forms", "ㄸ is a doubled initial consonant, distinct from ㄷ. 달 and 딸 are different written words. A text-only exercise can check the distinction you produce, but cannot assess how accurately you pronounce it.", "달 · 딸", "Moon · daughter.", "Write the word 딸, daughter, preserving its doubled initial.", "딸", "달", "따"],
  ["clusters", "A final can contain two consonant letters", "Some blocks have a two-letter final, such as ㅄ in 값. Both letters belong inside the final position. Learn these spellings in whole words; the number of written final letters does not directly tell you how they sound in every context.", "값", "Price; value.", "Write 값 with its complete final cluster.", "값", "갑", "갓"],
 ]),
 ar: course("ar", "Modern Standard Arabic; fully marked examples only where explicitly taught", "ا ب ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ ف ق ك ل م ن ه و ي", [
  ["direction", "Read words from right to left", "Arabic words run from right to left. Let the keyboard and text renderer handle that order: do not reverse the letters manually. Dots distinguish many letters that share a basic shape. باب keeps its two ب letters distinct from ت and ث.", "باب", "Door.", "Write باب in its normal logical order.", "باب", "تاب", "بات"],
  ["joining", "Joining changes appearance, not identity", "Letters can have different visible shapes depending on their position and neighbors. Some, including ا د ذ ر ز و, do not connect onward to the following letter on their left. A visible break inside ورد is not a space between words.", "ورد", "Roses; a collective form used for rose flowers.", "Write ورد as one word, without added spaces at joining breaks.", "ورد", "و ر د", "و رد"],
  ["vowels", "Short-vowel marks carry information", "Marks above and below consonants can distinguish written readings. كَتَبَ means he wrote; كُتُب means books. Unvowelled texts often omit these marks, but this exercise explicitly checks the marked form taught here.", "كَتَبَ · كُتُب", "He wrote · books.", "Write كُتُب with the two short-vowel marks shown for books.", "كُتُب", "كَتَبَ", "كتب"],
  ["ta-marbuta", "Distinguish ة from ه", "Tāʾ marbūṭa ة occurs at the end of many words. It is not interchangeable with ه merely because the shapes are related. In مدرسة, retain the two dots of the final letter.", "مدرسة", "School.", "Write مدرسة with its final ة.", "مدرسة", "مدرسه", "مدرست"],
  ["hamza", "Hamza is part of the written word", "Hamza may appear on a carrier or independently under spelling rules that need further practice. In سأل, retain the hamza above alif. Removing it does not preserve the taught spelling.", "سأل", "He asked.", "Write سأل with the hamza shown here.", "سأل", "سال", "سئل"],
 ]),
 hi: course("hi", "Modern Hindi in Devanagari; distinguish vowel signs and conjuncts", "अ आ इ ई उ ऊ ऋ ए ऐ ओ औ · क ख ग घ ङ च छ ज झ ञ ट ठ ड ढ ण त थ द ध न प फ ब भ म य र ल व श ष स ह · ़ ं ँ ः ्", [
  ["vowels", "A vowel can be a letter or a sign", "Devanagari uses independent vowel letters and dependent vowel signs attached to consonants. क and का are different written forms. In का, the added ा changes the vowel represented; it is not a separate word.", "क · का", "A consonant form and the same consonant with an attached vowel sign.", "Write क with the ा vowel sign.", "का", "क", "क आ"],
  ["reordering", "Visible position differs from input order", "The sign ि is displayed to the left of its consonant even though the logical sequence is consonant followed by vowel sign. A normal Hindi keyboard and renderer handle this. Do not manually reorder the stored characters to match the visual position.", "कि", "The written sequence क + ि.", "Enter कि using a Hindi input method.", "कि", "िक", "की"],
  ["halant", "Suppress the inherent vowel explicitly", "A consonant normally carries an inherent vowel convention. The halant ् suppresses it and can participate in conjunct formation. क् is therefore a different written form from क. Reading full Hindi words also requires word-specific conventions.", "क्", "क with a halant.", "Write क followed by the halant ्.", "क्", "क", "का"],
  ["nasal", "Retain the nasalization mark", "Chandrabindu ँ is a nasalization mark. In माँ it belongs above the written syllable. It is not ordinary punctuation and should not be discarded by answer normalization. Anusvāra ं has its own uses and conventions.", "माँ", "Mother.", "Write माँ with chandrabindu.", "माँ", "मा", "मः"],
  ["ra", "Conjunct order matters", "र combines with other consonants in different positions. कर्म and क्रम do not have the same consonant order. Learn each written cluster in the word instead of treating the visible marks as movable decorations.", "कर्म · क्रम", "Action or work · order or sequence.", "Write क्रम, the word for order or sequence shown here.", "क्रम", "कर्म", "करम"],
 ]),
 ru: course("ru", "Modern Russian Cyrillic; preserve ё in instructional forms", "А а · Б б · В в · Г г · Д д · Е е · Ё ё · Ж ж · З з · И и · Й й · К к · Л л · М м · Н н · О о · П п · Р р · С с · Т т · У у · Ф ф · Х х · Ц ц · Ч ч · Ш ш · Щ щ · Ъ ъ · Ы ы · Ь ь · Э э · Ю ю · Я я", [
  ["lookalikes", "A familiar shape can belong to another script", "Cyrillic Р and р resemble Latin P and p but are different characters with different language roles. Use the Russian keyboard for Russian text. Visual similarity is not sufficient for a spelling match.", "Р · р", "Uppercase and lowercase Cyrillic forms of the same letter.", "Enter lowercase Cyrillic р, not Latin p.", "р", "p", "Р"],
  ["yo", "Learn ё explicitly", "Ё is part of the Russian alphabet. Although dots are omitted in some publications, instructional text here retains them. Всё and все are distinct forms; learners should not be taught to erase the distinction indiscriminately.", "всё", "Everything; all of it.", "Write всё with ё.", "всё", "все", "всë"],
  ["soft-sign", "A sign can matter without being a vowel", "The soft sign ь has a grammatical and orthographic role. It is not an ordinary vowel letter. In день it is required at the end. Dropping it is not a harmless simplification.", "день", "Day.", "Write день with its final soft sign.", "день", "ден", "денъ"],
  ["hard-sign", "Keep the separating hard sign", "The hard sign ъ appears in particular spelling environments. In съезд it separates the prefix from the following part of the word. It is distinct from the soft sign, and neither is decorative punctuation.", "съезд", "Congress; convention.", "Write съезд with the hard sign.", "съезд", "сьезд", "сезд"],
 ]),
};

// The checks do not display the answer inside their question. Study mode supplies the worked model first.
const recallPrompts: Record<FoundationLanguage, string[]> = {
 en: ["Write the English first-person singular pronoun with its required capitalization.", "Write the two-word name of the US city whose name begins with New and ends with York.", "Contract the words I am, using a straight apostrophe.", "Turn the words i am ready into a conventionally capitalized statement ending with a full stop."],
 es: ["Write the Spanish name for Spain, with its conventional capital letter.", "Write the affirmative yes in lowercase Spanish.", "Write the lowercase Spanish word for shame or embarrassment taught in this lesson.", "Write the Spanish question meaning Where is it?, with opening and closing punctuation."],
 vi: ["Write the crossed lowercase Vietnamese consonant, not plain d.", "Write the lowercase Vietnamese word for friend taught in this lesson.", "Write the lowercase first word of the Vietnamese expression for the Vietnamese language.", "Write the Vietnamese country name for Vietnam, with its marks, capitals and syllable space."],
 fr: ["Write the lowercase French word for coffee.", "Write the lowercase French word meaning where, not or.", "Write the lowercase French word for French, retaining its cedilla.", "Combine m and appelle with the required straight apostrophe and no internal space."],
 pt: ["Write the Portuguese greeting hello with an initial capital and no punctuation.", "Write the lowercase Portuguese word meaning no or not.", "Write the lowercase Portuguese word for heart.", "Write lowercase a with the grave accent used to mark the taught contraction."],
 de: ["Write the lowercase German word meaning for, using an umlaut rather than a keyboard substitution.", "Write the German noun for street using the ß convention taught here.", "Write the German noun for language, with its conventional capital letter.", "Write the German compound noun for railway station as one conventionally capitalized word."],
 it: ["Write the lowercase Italian word meaning is, not and.", "Write the lowercase Italian word that can mean why or because.", "Write the lowercase Italian noun meaning year.", "Join the elided article l to amico with the required straight apostrophe."],
 zh: ["Write China in the simplified Chinese characters taught here, without spaces.", "Write the complete Chinese character for singular you taught here, not just its left component.", "Write the pinyin reading for singular you with the third-tone mark.", "Write the Chinese character for I or me, not pinyin.", "Write the Chinese greeting hello with an ideographic full stop."],
 ja: ["Write Canada in katakana.", "Write the Japanese word for key in hiragana, retaining its voicing mark.", "Write postage stamp in hiragana using the small consonant-length marker.", "Write the Japanese word for guest or customer taught here, using a small kana combination.", "Write coffee in katakana, retaining both long-vowel marks."],
 ko: ["Compose initial ㄱ and vowel ㅏ into one syllable block.", "Compose initial ㄱ and vowel ㅗ into one syllable block.", "Write the Korean word for milk as two composed syllable blocks.", "Compose initial ㅎ, vowel ㅏ and final ㄴ into one syllable block.", "Write the Korean word for daughter, not moon.", "Write the Korean word for price or value taught here, retaining the two-letter final cluster."],
 ar: ["Write the Arabic word for door taught here.", "Write the Arabic word for roses taught here as one word, without inserting spaces at joining breaks.", "Write the Arabic word for books with both short-vowel marks taught here.", "Write the Arabic word for school taught here, retaining the correct final letter.", "Write the Arabic past-tense form meaning he asked taught here, retaining its hamza."],
 hi: ["Attach the dependent long-a vowel sign to क as one written syllable.", "Attach the short-i vowel sign to क using logical input order.", "Write क with a halant to suppress its inherent vowel.", "Write the Hindi word for mother taught here, retaining chandrabindu.", "Write the Hindi word for order or sequence taught here, not the word for work or action."],
 ru: ["Enter the lowercase Cyrillic letter whose uppercase form is Р. Do not use Latin p.", "Write the lowercase Russian form meaning everything or all of it taught here, retaining its dots.", "Write the lowercase Russian noun meaning day, retaining its final sign.", "Write the lowercase Russian word for congress or convention taught here, retaining its separating sign."],
};
for (const language of Object.keys(scriptCourses) as FoundationLanguage[]) {
 const prompts = recallPrompts[language];
 if (prompts.length !== scriptCourses[language].lessons.length) throw new Error(`Missing script prompt: ${language}`);
 scriptCourses[language].lessons.forEach((lesson, i) => { lesson.prompt = prompts[i]; });
}
