import type { Course, Exercise, Stage } from "./model";

type Row = { id: string; title: string; explanation: string; cue: string; answer: string; alternatives: string[]; parts?: string[]; mode?: "hangul"; stage?: Stage; meaning?: string; track?: string; second?: { cue: string; answer: string; alternatives: string[]; parts?: string[]; mode?: "hangul" } };
const rows: Partial<Record<Course["language"], Row[]>> = {
 en: [
  { id: "case", title: "Uppercase marks names and sentence beginnings", explanation: "English uses the same alphabet in uppercase and lowercase forms. Capitals identify sentence beginnings and proper names; they do not create a different word sound.", cue: "Choose the correctly capitalized sentence.", answer: "I live in Indiana.", alternatives: ["i live in indiana.", "I live in indiana."], stage: "contrasts" },
  { id: "digraph-sh", title: "Two letters can represent one consonant", explanation: "In ship, s and h work together as the digraph sh. Decoding proceeds through the sound-bearing unit, not by pronouncing each letter independently.", cue: "Build ship from its sound-bearing parts.", answer: "ship", alternatives: ["sip", "shop"], parts: ["sh", "i", "p"], second: { cue: "Build fish from its sound-bearing parts.", answer: "fish", alternatives: ["fis", "fiss"], parts: ["f", "i", "sh"] } },
  { id: "silent-e", title: "Final e can change an earlier vowel", explanation: "Compare cap and cape. In many words, final e is not pronounced separately but helps signal a different preceding vowel. This is a pattern, not an exception-free rule.", cue: "Choose the word that names a long outer garment.", answer: "cape", alternatives: ["cap", "capee"], stage: "decoding" },
  { id: "apostrophe", title: "Apostrophes preserve omitted material", explanation: "In I’m, the apostrophe marks letters omitted from I am. The written contraction carries the same core meaning with a different register and rhythm.", cue: "Build the contraction for I am.", answer: "I’m", alternatives: ["Im", "Iam"], parts: ["I", "’", "m"] },
 ],
 es: [
  { id: "enye", title: "Ñ is its own letter", explanation: "Spanish n and ñ are distinct letters and can distinguish words, as in ano and año. The tilde belongs to the letter; it is not an optional accent.", cue: "Enter the word for year, not anus.", answer: "año", alternatives: ["ano", "ãnó"], second: { cue: "Enter the word for child.", answer: "niño", alternatives: ["nino", "níno"] }, stage: "contrasts" },
  { id: "stress", title: "Written accents can mark stress and meaning", explanation: "An acute accent can show stress that the ordinary spelling rules would not predict, and it can distinguish words such as sí and si. Keep it in recognition and input.", cue: "Choose the affirmative word yes.", answer: "sí", alternatives: ["si", "sì"], second: { cue: "Enter the word canción with its written stress.", answer: "canción", alternatives: ["cancion", "cáncion"] } },
  { id: "question-marks", title: "Questions are framed at both ends", explanation: "Spanish uses an opening inverted question mark and a closing question mark. The opening mark helps the reader identify the sentence type before reaching the end.", cue: "Build the complete question How are you? in Spanish.", answer: "¿Cómo estás?", alternatives: ["Cómo estás?", "¿Como estás?"], parts: ["¿", "Cómo", " ", "estás", "?"] },
  { id: "hard-soft-c", title: "C changes with the following vowel", explanation: "Before e and i, c is pronounced differently from c before a, o and u; pronunciation varies by region. Qu preserves the k-like sound before e and i, as in queso.", cue: "Choose the conventional spelling for cheese.", answer: "queso", alternatives: ["ceso", "keso"], stage: "decoding" },
  { id: "gue-gui", title: "U can guide G without being heard", explanation: "In gue and gui, u commonly keeps g hard and is silent. A diaeresis in güe or güi makes the u audible, as in pingüino.", cue: "Choose the word in which u is pronounced.", answer: "pingüino", alternatives: ["pinguino", "pingúino"], stage: "decoding" },
 ],
 fr: [
  { id: "accent-contrast", title: "Accent marks belong to French spelling", explanation: "French uses acute, grave and circumflex accents, and diaeresis. They can distinguish vowel quality, history, or words; they must survive written reconstruction.", cue: "Enter the word école with its accent.", answer: "école", alternatives: ["ecole", "ècole"], second: { cue: "Enter the word frère with its accent.", answer: "frère", alternatives: ["frere", "frére"] } },
  { id: "cedilla", title: "Ç preserves the soft c sound", explanation: "Before a, o and u, a cedilla makes c retain the soft sound found before e and i. Compare garçon with car.", cue: "Enter the word for boy.", answer: "garçon", alternatives: ["garcon", "garsson"], stage: "contrasts" },
  { id: "apostrophe", title: "Elision joins grammar to the next word", explanation: "French often drops a final vowel before another vowel sound and marks the omission with an apostrophe: je aime becomes j’aime. The apostrophe is structural, not decorative.", cue: "Build the natural form of je aime.", answer: "j’aime", alternatives: ["je aime", "jaime"], parts: ["j", "’", "aime"] },
  { id: "ligature", title: "Œ functions as a joined written form", explanation: "The ligature œ occurs in common words such as sœur and cœur. Typing systems may require a special input method; the displayed word should retain the ligature.", cue: "Enter the French word for sister.", answer: "sœur", alternatives: ["soeur", "sour"], stage: "contrasts" },
  { id: "silent-endings", title: "Written endings can carry grammar silently", explanation: "Many final consonants and inflectional endings are not pronounced in isolation, yet they remain essential in writing and can mark number or verb form. Read the whole word in its sentence.", cue: "Choose the written plural: the small cats.", answer: "les petits chats", alternatives: ["le petit chat", "les petit chat"], stage: "decoding" },
 ],
 pt: [
  { id: "nasal-tilde", title: "The tilde marks a nasal vowel", explanation: "Portuguese ã and õ mark nasal vowels. The mark is part of the spelling and participates in contrasts such as avó and avô, where other accents also matter.", cue: "Enter the word for bread.", answer: "pão", alternatives: ["pao", "paõ"], second: { cue: "Enter the word for mother.", answer: "mãe", alternatives: ["mae", "mâe"] } },
  { id: "cedilla", title: "Ç represents a soft c sound", explanation: "Portuguese ç occurs before a, o and u and represents the soft c sound. It does not begin a word.", cue: "Enter the word coração with its cedilla and accent.", answer: "coração", alternatives: ["coracao", "coraçáo"], stage: "contrasts" },
  { id: "nh-lh", title: "Digraphs encode single consonant relationships", explanation: "Nh and lh are stable letter combinations in words such as vinho and filho. Decode the pair as a unit while retaining both letters in writing.", cue: "Build the word for son.", answer: "filho", alternatives: ["fio", "fillo"], parts: ["fi", "lh", "o"], second: { cue: "Build the word for wine.", answer: "vinho", alternatives: ["vino", "viño"], parts: ["vi", "nh", "o"] } },
  { id: "stress", title: "Written accents guide stress and vowel quality", explanation: "Acute and circumflex accents mark stressed vowels and may help distinguish vowel quality. Do not remove them during input.", cue: "Enter the word água with its accent.", answer: "água", alternatives: ["agua", "agúa"], stage: "decoding" },
 ],
 de: [
  { id: "umlauts", title: "Umlauts create distinct vowel spellings", explanation: "Ä, ö and ü are not decorative versions of a, o and u. They represent different vowel patterns and can distinguish words. Preserve them or use accepted keyboard substitutions only when explicitly allowed.", cue: "Enter the word for door.", answer: "Tür", alternatives: ["Tur", "Túr"], second: { cue: "Enter the plural of mother, Mütter.", answer: "Mütter", alternatives: ["Mutter", "Mütterr"] }, stage: "contrasts" },
  { id: "eszett", title: "ß and ss follow spelling rules", explanation: "German ß represents a voiceless s sound after a long vowel or diphthong in standard spelling, while ss follows a short vowel. Swiss standard German uses ss instead of ß.", cue: "Enter the standard German word Straße.", answer: "Straße", alternatives: ["Strase", "Straẞe"], stage: "contrasts" },
  { id: "noun-case", title: "Nouns begin with uppercase letters", explanation: "German capitalizes common nouns as well as proper names. This gives the reader grammatical information within a sentence.", cue: "Choose the correctly capitalized sentence: The book is here.", answer: "Das Buch ist hier.", alternatives: ["Das buch ist hier.", "das Buch ist hier."], stage: "decoding" },
  { id: "digraphs", title: "Letter groups carry stable sound patterns", explanation: "Ch, sch, ei and ie must be decoded as combinations. Compare mein with viel; reversing ei and ie changes the word and sound.", cue: "Build the word Schule from its sound-bearing groups.", answer: "Schule", alternatives: ["Shule", "Schülle"], parts: ["Sch", "u", "le"] },
 ],
 it: [
  { id: "c-ch", title: "H preserves hard C before E and I", explanation: "Italian c before e or i has a different sound from c before a, o or u. Ch preserves the hard sound before e and i, as in chiave.", cue: "Enter the word for key.", answer: "chiave", alternatives: ["ciave", "kiave"], stage: "decoding" },
  { id: "g-gh", title: "H preserves hard G before E and I", explanation: "Gh preserves the hard g sound before e and i. Without h, ge and gi represent a different consonant sound.", cue: "Choose the conventional spelling for spaghetti.", answer: "spaghetti", alternatives: ["spagetti", "spagheti"], stage: "decoding" },
  { id: "gn-gl", title: "Letter combinations encode consonant units", explanation: "Gn and gl before i can represent consonant patterns not obtained by reading each letter separately. Decode them inside real words such as gnocchi and figlio.", cue: "Build the word for son.", answer: "figlio", alternatives: ["filio", "figio"], parts: ["fi", "gli", "o"] },
  { id: "double-consonants", title: "Consonant length changes words", explanation: "Italian spelling distinguishes single and doubled consonants. The difference is pronounced and can distinguish words; retain both letters in input.", cue: "Choose the word meaning house, not cash register.", answer: "casa", alternatives: ["cassa", "caza"], stage: "contrasts" },
  { id: "final-accent", title: "Final written accents mark stress", explanation: "Words stressed on a final vowel normally carry a written accent, as in città and perché. The accent remains part of the word.", cue: "Enter the word for city.", answer: "città", alternatives: ["citta", "cítta"], stage: "contrasts" },
 ],
 vi: [
  { id: "vowel-a", title: "A, Ă and Â", explanation: "A, Ă and Â are distinct Vietnamese vowel letters. The breve and circumflex belong to vowel identity. A tone mark can be added separately. Compare an, ăn and ân; keep the letter shape before adding tone.", cue: "Compose a with a breve to make the short-a vowel letter.", answer: "ă", alternatives: ["a", "â"], parts: ["a", "\u0306"] },
  { id: "vowel-o", title: "O, Ô and Ơ", explanation: "O, Ô and Ơ represent different vowel qualities. Ô uses a circumflex; Ơ uses a horn. They remain different when tones change. Compare cô and cơ.", cue: "Compose o with a horn.", answer: "ơ", alternatives: ["o", "ô"], parts: ["o", "\u031b"] },
  { id: "vowel-u", title: "U and Ư", explanation: "U and Ư are different vowel letters. The horn in Ư identifies the vowel; it is not a tone mark. Compare thu and thư. Listen in words and retain the horn in input.", cue: "Compose u with a horn.", answer: "ư", alternatives: ["u", "ú"], parts: ["u", "\u031b"] },
  ...([ ["ngang", "a", "", "unmarked"], ["huyền", "à", "\u0300", "grave"], ["sắc", "á", "\u0301", "acute"], ["hỏi", "ả", "\u0309", "hook above"], ["ngã", "ã", "\u0303", "tilde"], ["nặng", "ạ", "\u0323", "dot below"] ] as const).map(([name, answer, mark, label]) => ({ id: `tone-${name}`, title: `Tone: ${name}`, explanation: `Vietnamese distinguishes six written tone categories. ${name} uses the ${label} pattern. The written category is stable, while spoken realization varies by region. Practise with complete syllables and words; vowel shape and tone are independent layers.`, cue: `Build a with the ${name} (${label}) tone.`, answer, alternatives: ["a", "à", "á", "ả", "ã", "ạ"].filter(x => x !== answer), parts: mark ? ["a", mark] : undefined })),
  { id: "tone-shape", title: "Vowel shape before tone", explanation: "In tiếng, ê retains its circumflex and takes an acute tone mark. Both layers belong to the vowel. The tone is placed on the written vowel nucleus, not the final consonants.", cue: "Build tiếng from ti, ê, the acute tone mark and ng.", answer: "tiếng", alternatives: ["tiêng", "tiéng"], parts: ["ti", "ê", "\u0301", "ng"] },
  { id: "gh-ngh", title: "G/GH and NG/NGH", explanation: "Vietnamese uses gh and ngh before e, ê and i in native spelling. Elsewhere g and ng are used. These spelling choices retain the consonant relationship while fitting the following vowel.", cue: "Complete the word for chair: _ế. Choose the appropriate initial spelling.", answer: "ghế", alternatives: ["gế", "khế"], stage: "decoding" },
  { id: "c-k", title: "C and K before vowels", explanation: "In native spelling, k occurs before e, ê and i; c is used before many other vowels. Learn q with u in the qu pattern. Practise these environments rather than treating the spellings as freely interchangeable.", cue: "Choose the conventional spelling for the word meaning to sign: ký.", answer: "ký", alternatives: ["cý", "qý"], stage: "decoding" },
  { id: "nucleus", title: "Initial, nucleus and final", explanation: "A Vietnamese syllable can be analysed into an initial consonant, a vowel nucleus and an optional final. In bạn, b is initial, a is the vowel and n is final. The dot below a marks tone.", cue: "Build bạn from its initial, marked vowel and final.", answer: "bạn", alternatives: ["bán", "bạ"], parts: ["b", "ạ", "n"] },
  { id: "diphthong", title: "Vowels combine within a syllable", explanation: "Vietnamese spelling includes combinations such as iê, uô and ươ before finals, with related spellings in open syllables. Read the entire nucleus, then the final. In nước, the nucleus is ươ and c is final.", cue: "Build nước from n, ướ and c.", answer: "nước", alternatives: ["nuớc", "nươc"], parts: ["n", "ướ", "c"] },
  { id: "triphthong", title: "Read the full vowel sequence", explanation: "A word such as người contains a complex written vowel sequence. Keep ươ together and attend to the final glide i. The grave mark belongs to the nucleus: người.", cue: "Reconstruct the word for person from ng, ườ and i.", answer: "người", alternatives: ["ngươi", "nguời"], parts: ["ng", "ườ", "i"] },
  { id: "telex", title: "Telex produces Vietnamese text", explanation: "On a Telex keyboard, aa gives â, aw gives ă, ee gives ê, oo gives ô, ow gives ơ, uw gives ư and dd gives đ. Tone keys s/f/r/x/j produce sắc/huyền/hỏi/ngã/nặng; z removes a tone. Keyboard implementations may differ in timing. The final text is what matters.", cue: "Use your Vietnamese keyboard to enter đ. With Telex, dd produces this letter.", answer: "đ", alternatives: ["d", "dd"], stage: "composition" },
  { id: "vni", title: "VNI is another input route", explanation: "VNI commonly uses 1–5 for sắc, huyền, hỏi, ngã and nặng; 6 for circumflex, 7 for horn, 8 for breve and 9 for crossed d. These are input commands, not Vietnamese spelling. You may use Telex or another input method instead.", cue: "Enter the Vietnamese letter ă using your preferred input method.", answer: "ă", alternatives: ["a", "a8"], stage: "composition" },
 ],
 ko: [
  { id: "block-vertical", title: "Vertical vowel: left and right", explanation: "A consonant sits to the left of a vertical vowel. ㄴ and ㅏ compose 나. Build a block from jamo rather than selecting a completed block.", cue: "Compose ㄴ + ㅏ.", answer: "나", alternatives: ["너", "노"], parts: ["ㄴ", "ㅏ"], mode: "hangul" },
  { id: "block-horizontal", title: "Horizontal vowel: above and below", explanation: "With a horizontal vowel, the initial consonant sits above it. ㅁ and ㅗ form 모. The same input order produces a different spatial layout.", cue: "Compose ㅁ + ㅗ.", answer: "모", alternatives: ["마", "무"], parts: ["ㅁ", "ㅗ"], mode: "hangul" },
  { id: "silent-initial", title: "A vowel-initial block needs ㅇ", explanation: "In initial position ㅇ fills the consonant slot without adding a consonant sound. In final position it is pronounced ng. 아 begins with the silent initial.", cue: "Compose silent initial ㅇ and vowel ㅏ.", answer: "아", alternatives: ["앙", "어"], parts: ["ㅇ", "ㅏ"], mode: "hangul" },
  { id: "batchim", title: "Final consonants go below", explanation: "The final consonant, 받침, occupies the bottom of the block. ㅅ + ㅏ + ㄴ forms 산, mountain. Keep initial, vowel and final positions distinct.", cue: "Compose ㅅ + ㅏ + ㄴ.", answer: "산", alternatives: ["사", "삼"], parts: ["ㅅ", "ㅏ", "ㄴ"], mode: "hangul" },
  { id: "compound-vowel", title: "Compound vowel in one block", explanation: "ㅘ combines the vowel elements ㅗ and ㅏ. With initial ㄱ it forms 과. A compound vowel occupies the medial slot in a single block.", cue: "Compose ㄱ with compound vowel ㅘ.", answer: "과", alternatives: ["고", "가"], parts: ["ㄱ", "ㅘ"], mode: "hangul" },
  { id: "final-cluster", title: "A final cluster still occupies one slot", explanation: "Some blocks contain a two-letter final cluster. In 값, the final is ㅄ. Pronunciation depends on the following sound; writing retains both letters.", cue: "Compose ㄱ + ㅏ + ㅄ.", answer: "값", alternatives: ["갑", "갓"], parts: ["ㄱ", "ㅏ", "ㅄ"], mode: "hangul" },
  { id: "liaison", title: "Read across a syllable boundary", explanation: "When a final consonant is followed by a vowel-initial grammatical element, its sound may link forward. In 문이, the written blocks remain 문 + 이 while the pronunciation links the n into the following syllable.", cue: "Keep the written noun 문 and particle 이 together.", answer: "문이", alternatives: ["무니", "문니"], parts: ["문", "이"], stage: "decoding" },
  { id: "plain-aspirated-tense", title: "Plain, aspirated and tense consonants contrast", explanation: "Korean distinguishes series such as ㄱ, ㅋ and ㄲ. They are separate jamo and participate in different words; do not treat them as stylistic variants.", cue: "Choose the tense counterpart of ㄱ.", answer: "ㄲ", alternatives: ["ㄱ", "ㅋ"], stage: "contrasts" },
  { id: "batchim-sound", title: "Final spellings map to a smaller sound set", explanation: "Many written final consonants share a neutralized final pronunciation. The spelling is preserved because it connects words and grammatical forms even when the released sound is not heard.", cue: "Choose the correctly written word for book.", answer: "책", alternatives: ["채", "챋"], stage: "decoding" },
  { id: "nasal-assimilation", title: "Adjacent sounds can reshape pronunciation", explanation: "In combinations such as 국물, the written consonants remain stable while pronunciation adjusts across the boundary. Literacy requires retaining spelling while recognizing connected speech.", cue: "Enter the written form for soup broth, gukmul.", answer: "국물", alternatives: ["궁물", "구물"], stage: "decoding" },
 ],
 zh: [
  { id: "pinyin-mark", track: "pinyin", title: "Where the tone mark belongs", explanation: "Pinyin marks a first; otherwise e, then o in ou. In iu and ui, mark the second vowel. Neutral tone is unmarked. Tone spelling is separate from a character's written form.", cue: "Write shui with the third-tone mark on the correct vowel.", answer: "shuǐ", alternatives: ["shǔi", "shuí"], second: { cue: "Write xue with the second-tone mark.", answer: "xué", alternatives: ["xúe", "xuè"] } },
  { id: "pinyin-u", track: "pinyin", title: "Ü after j, q and x", explanation: "After j, q and x, Pinyin writes ü without its dots: ju, qu, xu. After n and l the dots distinguish nü/lü from nu/lu. Learn this as a spelling rule.", cue: "Choose the Pinyin syllable lü with a fourth-tone mark.", answer: "lǜ", alternatives: ["lù", "lǘ"] },
  { id: "pinyin-syllable", track: "pinyin", title: "Initial and final form one syllable", explanation: "Pinyin syllables combine an optional initial with a final and a tone. Decode the legal combination as one Mandarin syllable rather than as English letters.", cue: "Build mā from initial m, final a and first tone.", answer: "mā", alternatives: ["má", "mǎ"], parts: ["m", "ā"] },
  { id: "pinyin-apostrophe", track: "pinyin", title: "Apostrophes clarify syllable boundaries", explanation: "An apostrophe separates an a-, o- or e-initial syllable when the boundary could otherwise be misread, as in Xī’ān. It is an orthographic boundary marker.", cue: "Enter the Pinyin spelling for Xi'an with tone marks and boundary.", answer: "Xī’ān", alternatives: ["Xīān", "Xǐ’ān"], stage: "decoding" },
  { id: "hanzi-component", track: "hanzi", title: "A recurring person component", explanation: "亻 is the left-side form related to 人 and recurs in characters such as 你 and 他. It can help organize recognition; it does not guarantee the whole character's pronunciation or meaning.", cue: "Choose the left component shared by 你 and 他.", answer: "亻", alternatives: ["口", "氵"] },
  { id: "hanzi-water", track: "hanzi", title: "Components organize related characters", explanation: "氵 is the side form of water and appears in characters such as 河 and 海. Components provide useful structural and semantic clues, but the whole character still requires word-level evidence.", cue: "Choose the water component in 河.", answer: "氵", alternatives: ["亻", "木"], stage: "contrasts" },
  { id: "hanzi-compound", track: "hanzi", title: "Characters make words", explanation: "学 occurs in 学生 (student) and 学校 (school). The recurring character is useful, but meanings and readings must be learned in real words. A word can contain more than one character.", cue: "Build 学校, school, from the two characters.", answer: "学校", alternatives: ["学生", "校学"], parts: ["学", "校"], second: { cue: "Build 学生, student, from the two characters.", answer: "学生", alternatives: ["学校", "生学"], parts: ["学", "生"] } },
  { id: "hanzi-sound-meaning", track: "hanzi", title: "One character participates in several retrieval paths", explanation: "A useful character must connect form, pronunciation, meaning and compounds. 学 is xué, relates to learning, and recurs in 学生 and 学校. These pathways remain separately assessed.", cue: "Choose the character read xué in 学校.", answer: "学", alternatives: ["校", "生"], stage: "decoding" },
 ],
 ja: [
  { id: "dakuten", track: "hiragana", title: "Voicing marks change the kana", explanation: "Dakuten adds voicing to the k, s, t and h rows. Handakuten changes the h row to p. Compare は, ば and ぱ. Marks remain part of spelling.", cue: "Compose は with handakuten to make pa.", answer: "ぱ", alternatives: ["は", "ば"], parts: ["は", "\u309a"], second: { cue: "Compose か with dakuten to make ga.", answer: "が", alternatives: ["か", "ぱ"], parts: ["か", "\u3099"] } },
  { id: "contracted", track: "hiragana", title: "Small kana combine", explanation: "Small ゃ, ゅ and ょ combine with eligible i-row kana. きゃ is kya; full-sized きや is ki-ya. The size changes the sound sequence.", cue: "Build kya from き and small ゃ.", answer: "きゃ", alternatives: ["きや", "きゅ"], parts: ["き", "ゃ"] },
  { id: "geminate", track: "hiragana", title: "Small っ holds the next consonant", explanation: "In きって, small っ indicates the consonant-length contrast before t. It is not pronounced as a separate full tsu syllable.", cue: "Build きって with the small consonant-length marker.", answer: "きって", alternatives: ["きつて", "きて"], parts: ["き", "っ", "て"] },
  { id: "katakana-long", track: "katakana", title: "Katakana marks long vowels with ー", explanation: "In many katakana words, ー extends the preceding vowel. Its visual length mark belongs to the word, as in コーヒー.", cue: "Build the katakana word for coffee.", answer: "コーヒー", alternatives: ["コヒ", "コーヒ"], parts: ["コ", "ー", "ヒ", "ー"] },
  { id: "kanji-reading", track: "words-kanji", title: "Kanji readings live in real words", explanation: "A kanji can have more than one reading. Learn readings in vocabulary and sentences: 学 is read がく in 学生 and まな in 学ぶ. A single isolated label is insufficient mastery.", cue: "Choose the word read がくせい, student.", answer: "学生", alternatives: ["学校", "先生"], stage: "decoding" },
  { id: "mixed-script", track: "words-kanji", title: "Japanese sentences combine scripts", explanation: "Japanese normally combines kanji, hiragana and katakana. Kanji often carry lexical content, hiragana carries inflection and particles, and katakana serves several specialized roles.", cue: "Build the sentence I read a book at home.", answer: "家で本を読みます。", alternatives: ["家デ本オ読みます。", "いえでほんよみます"], parts: ["家", "で", "本", "を", "読みます", "。"], stage: "sentences" },
 ],
 ar: [
  { id: "joining", title: "Letters connect by position", explanation: "Arabic is read right to left. ب has isolated ب, initial بـ, medial ـبـ and final ـب shapes. Input ordinary letters in reading order; the renderer selects the connected shapes.", cue: "Build باب from ب, ا and ب in reading order.", answer: "باب", alternatives: ["ببا", "ابب"], parts: ["ب", "ا", "ب"] },
  { id: "breaks", title: "Six letters break the following connection", explanation: "ا د ذ ر ز و do not join to the letter that follows them in reading order. A break in connection is not a word space. ورد remains one word.", cue: "Build ورد without inserting spaces at joining breaks.", answer: "ورد", alternatives: ["و ر د", "ور د"], parts: ["و", "ر", "د"] },
  { id: "vowel-marks", title: "Short vowels follow their consonant", explanation: "Fatḥa, kasra and ḍamma mark short a, i and u. They are displayed above or below the consonant but pronounced after it. كُ is ku.", cue: "Compose ك with ḍamma.", answer: "كُ", alternatives: ["كَ", "كِ"], parts: ["ك", "\u064f"] },
  { id: "shadda", title: "Shadda marks a doubled consonant", explanation: "Shadda indicates consonant doubling. Retain it when the exercise asks for vocalized text. Unvowelled text often omits such marks and needs contextual reading.", cue: "Compose ب with shadda.", answer: "بّ", alternatives: ["ب", "بْ"], parts: ["ب", "\u0651"] },
  { id: "sun-letter", title: "The article is written even when speech assimilates", explanation: "The definite article ال remains written before both sun and moon letters. Before a sun letter, the l sound assimilates in speech, as in الشَّمس, while the spelling preserves the article.", cue: "Enter the vocalized form for the sun.", answer: "الشَّمْس", alternatives: ["اشَّمْس", "الْشَمْس"], stage: "decoding" },
  { id: "ta-marbuta", title: "ة changes by grammatical context", explanation: "Tāʾ marbūṭa is commonly written ة at the end of feminine nouns. Its pronunciation depends on pause and grammatical connection; its written form remains identifiable.", cue: "Choose the correctly written word for school.", answer: "مدرسة", alternatives: ["مدرست", "مدرسه"], stage: "contrasts" },
  { id: "hamza", title: "Hamza marks a glottal onset", explanation: "Hamza appears on or beside carriers according to orthographic rules. At this level, learn frequent forms inside words rather than treating every seat as interchangeable.", cue: "Choose the correctly written first-person pronoun I.", answer: "أنا", alternatives: ["انا", "إنا"], stage: "contrasts" },
 ],
 hi: [
  { id: "matra", title: "A consonant and vowel sign form an akshara", explanation: "का contains consonant क followed by dependent vowel sign ा. The vowel sign changes the inherent vowel. Do not insert the independent letter आ after क to represent the same syllable.", cue: "Compose क and ा.", answer: "का", alternatives: ["कआ", "क"], parts: ["क", "ा"] },
  { id: "visual-order", title: "Input order and visible order differ", explanation: "In कि, the short-i sign appears to the left but is entered after क. The text renderer handles positioning. Build logical order, not screen order.", cue: "Compose क followed by ि.", answer: "कि", alternatives: ["िक", "की"], parts: ["क", "ि"] },
  { id: "conjunct", title: "Halant connects consonants", explanation: "In क्रम, क् combines with र before म. The halant suppresses the inherent vowel of क. The resulting cluster is part of a word, not a sequence of independent full syllables.", cue: "Build क्रम in logical character order.", answer: "क्रम", alternatives: ["कर्म", "करम"], parts: ["क", "्", "र", "म"] },
  { id: "anusvara", title: "A dot can mark nasal participation", explanation: "Anusvāra ं participates in nasalization or a nasal consonant whose realization depends on context. Keep it distinct from chandrabinduँ and the virāma्.", cue: "Enter the word Hindi, हिन्दी, with its nasal mark.", answer: "हिन्दी", alternatives: ["हिदी", "हिँदी"], stage: "contrasts" },
  { id: "nukta", title: "Nukta extends consonant distinctions", explanation: "The nukta dot creates additional consonant forms used especially in loanwords, such as फ़. The dot is part of the written form when standard spelling requires it.", cue: "Compose फ़ from फ and nukta.", answer: "फ़", alternatives: ["फ", "फ़्"], parts: ["फ", "़"] },
  { id: "danda", title: "Sentence punctuation has script-specific forms", explanation: "Hindi can use the danda । to close a sentence, alongside modern punctuation in many contexts. Recognize both, and preserve the form used by the text.", cue: "Build the sentence This is a book. with a danda.", answer: "यह किताब है।", alternatives: ["यह किताब है.", "यह किताब हैं।"], parts: ["यह", " ", "किताब", " ", "है", "।"], stage: "sentences" },
 ],
 ru: [
  { id: "lookalikes", title: "Cyrillic forms are not Latin substitutes", explanation: "Several Cyrillic letters resemble Latin letters but represent different sounds or code points. Read Р as r, Н as n and С as s; input the actual Cyrillic forms.", cue: "Choose the Cyrillic letter for the r sound.", answer: "р", alternatives: ["p", "п"], second: { cue: "Choose the Cyrillic letter for the n sound.", answer: "н", alternatives: ["h", "п"] }, stage: "contrasts" },
  { id: "soft-sign", title: "The soft sign changes the preceding consonant", explanation: "Ь has no independent vowel sound. It commonly signals palatalization or a grammatical spelling pattern, as in день. It remains part of reconstruction.", cue: "Enter the word for day.", answer: "день", alternatives: ["ден", "дъень"], stage: "decoding" },
  { id: "hard-sign", title: "The hard sign separates a consonant and iotated vowel", explanation: "Ъ marks a boundary after certain prefixes before е, ё, ю or я, as in подъезд. It does not represent an independent spoken segment.", cue: "Enter the word подъезд.", answer: "подъезд", alternatives: ["подьезд", "подезд"], stage: "decoding" },
  { id: "i-short", title: "Й and И are different letters", explanation: "И is a vowel letter; й is a consonantal glide and appears in combinations such as мой. The breve is part of й.", cue: "Enter the word for my, masculine singular.", answer: "мой", alternatives: ["мои", "моӣ"], stage: "contrasts" },
  { id: "stress", title: "Stress is usually learned but not normally written", explanation: "Russian stress can distinguish pronunciation and is often marked in learning materials, but ordinary text normally omits the accent. Learn the stressed syllable while reconstructing standard unmarked spelling.", cue: "Enter the ordinary spelling of water, shown pedagogically as водá.", answer: "вода", alternatives: ["водá", "вада"], stage: "decoding" },
 ],
};

export function addArchitecture(course: Course) {
 const previousByTrack = new Map(course.tracks.map(track => [track.id, course.units.filter(unit => unit.track === track.id).at(-1)?.id]));
 for (const row of rows[course.language] || []) {
  const track = row.track || "architecture";
  const id = `${course.language}-architecture-${row.id}`, skill = `${course.language}:rule:${row.id}`;
  const exercises: Exercise[] = [
   { id: `${id}:recognize`, skill, direction: "recognize", kind: "choice", prompt: row.cue.replace(/^(Compose|Build|Write|Enter|Reconstruct|Complete|Keep)/, "Choose"), answer: row.answer, choices: [row.answer, ...row.alternatives], explanation: row.explanation },
   ...(row.parts ? [{ id: `${id}:compose`, skill, direction: "compose" as const, kind: "compose" as const, prompt: row.cue, answer: row.answer, components: row.parts, composition: row.mode || "sequence" as const, explanation: row.explanation }] : []),
   { id: `${id}:input`, skill, direction: "input", kind: "input", prompt: row.cue.replace(/^(Choose|Compose|Build|Reconstruct|Complete|Keep)/, "Enter"), answer: row.answer, explanation: row.explanation },
   ...(row.second ? [
    { id: `${id}:recognize-2`, skill, direction: "recognize" as const, kind: "choice" as const, prompt: row.second.cue.replace(/^(Compose|Build|Write|Enter|Reconstruct|Complete|Keep)/, "Choose"), answer: row.second.answer, choices: [row.second.answer, ...row.second.alternatives], explanation: row.explanation },
    ...(row.second.parts ? [{ id: `${id}:compose-2`, skill, direction: "compose" as const, kind: "compose" as const, prompt: row.second.cue, answer: row.second.answer, components: row.second.parts, composition: row.second.mode || "sequence" as const, explanation: row.explanation }] : []),
    { id: `${id}:input-2`, skill, direction: "input" as const, kind: "input" as const, prompt: row.second.cue.replace(/^(Choose|Compose|Build|Reconstruct|Complete|Keep)/, "Enter"), answer: row.second.answer, explanation: row.explanation },
   ] : []),
  ];
  const previous = previousByTrack.get(track);
  const stage = row.stage || "composition";
  const level: Course["units"][number]["level"] = stage === "composition" || stage === "contrasts" ? "Foundation" : stage === "decoding" || stage === "words" ? "A1" : "A2";
  course.units.push({ id, title: row.title, track, stage, level, prerequisites: previous ? [previous] : [], objective: row.title, explanation: row.explanation, forms: [row.answer, ...(row.second ? [row.second.answer] : [])], example: row.answer, meaning: row.meaning || "", exercises, sourceIds: [course.sources.at(-1)!.id], courseTerms: [] });
  previousByTrack.set(track, id);
 }
}
