import type { FoundationLanguage } from "../multilingual-foundation";

export type InventorySeed = { id?: string; form: string; label: string; reading?: string; audio?: string };
export type InventoryGroup = { id: string; track: string; title: string; description: string; items: InventorySeed[] };

const items = (forms: string[], labels?: string[]) => forms.map((form, index) => ({ form, label: labels?.[index] || form.toLocaleUpperCase(), reading: labels?.[index] || form }));
const chars = (value: string) => [...value];
const latin = chars("abcdefghijklmnopqrstuvwxyz");
const digits = chars("0123456789");
const alphabet = (language: FoundationLanguage, additions: string[] = []): InventoryGroup[] => [
 { id: "letters", track: "letters", title: "Complete letter inventory", description: "Every letter is introduced, distinguished in both cases, heard in words, and reconstructed through input.", items: items([...latin, ...additions], undefined).map(item => ({ ...item, label: item.form === "ß" ? "ẞ · ß" : `${item.form.toLocaleUpperCase(language)} · ${item.form}` })) },
 { id: "numerals", track: "conventions", title: "Numerals and number words", description: "Recognize the numerals used in ordinary text, then connect them to written number words in the reading path.", items: items(digits) },
];
const named = (forms: string[], labels: string[]) => items(forms, labels);
const sounded = (forms: string[], labels: string[], audio: string[]) => forms.map((form, index) => ({ form, label: labels[index], reading: labels[index], audio: audio[index] }));

export const writingInventories: Record<FoundationLanguage, InventoryGroup[]> = {
 en: [...alphabet("en"), { id: "punctuation", track: "conventions", title: "Sentence marks", description: "Read and enter the marks that organize ordinary English text.", items: named([".", ",", "?", "!", "'", "\"", ":", ";", "-"], ["full stop", "comma", "question mark", "exclamation mark", "apostrophe", "quotation mark", "colon", "semicolon", "hyphen"]) }],
 es: [...alphabet("es", ["ñ"]), { id: "marked-vowels", track: "conventions", title: "Marked vowels", description: "Accents and diaeresis are part of Spanish spelling and must survive reconstruction.", items: named(chars("áéíóúü"), ["a with acute", "e with acute", "i with acute", "o with acute", "u with acute", "u with diaeresis"]) }, { id: "paired-marks", track: "conventions", title: "Paired questions and exclamations", description: "Spanish signals the sentence type at both boundaries.", items: named(["¿", "?", "¡", "!"], ["opening question", "closing question", "opening exclamation", "closing exclamation"]) }],
 vi: [
  { id: "vowels", track: "alphabet", title: "Twelve vowel letters", description: "Vowel shape is lexical information. Learn each plain, breve, circumflex, and horn form as a distinct letter.", items: sounded(chars("aăâeêioôơuưy"), ["a · ba", "ă · ăn", "â · ân", "e · em", "ê · ghế", "i · đi", "o · to", "ô · cô", "ơ · cơ", "u · thu", "ư · thư", "y · y tế"], ["ba", "ăn", "ân", "em", "ghế", "đi", "to", "cô", "cơ", "thu", "thư", "y tế"]) },
  { id: "consonants", track: "alphabet", title: "Seventeen consonant letters", description: "Learn the complete consonant inventory, including the meaningful distinction between d and đ.", items: sounded(chars("bcdđghklmnpqrstvx"), ["b · ba", "c · cá", "d · da", "đ · đi", "g · ga", "h · hoa", "k · kê", "l · lo", "m · mẹ", "n · nam", "p · pin", "q · qua", "r · ra", "s · sao", "t · ta", "v · về", "x · xa"], ["ba", "cá", "da", "đi", "ga", "hoa", "kê", "lo", "mẹ", "nam", "pin", "qua", "ra", "sao", "ta", "về", "xa"]) },
  { id: "tones", track: "tone-orthography", title: "Six written tones", description: "The unmarked tone and five written marks combine with vowel identity; neither layer replaces the other.", items: named(["a", "à", "á", "ả", "ã", "ạ"], ["ngang · level", "huyền · grave", "sắc · acute", "hỏi · hook above", "ngã · tilde", "nặng · dot below"]) },
  { id: "vowel-tone-layers", track: "tone-orthography", title: "Vowel shape plus tone", description: "A tone mark is layered onto the correct vowel without losing breve, circumflex, or horn.", items: named(["ắ", "ằ", "ẳ", "ẵ", "ặ", "ấ", "ầ", "ẩ", "ẫ", "ậ", "ế", "ề", "ể", "ễ", "ệ", "ố", "ồ", "ổ", "ỗ", "ộ", "ớ", "ờ", "ở", "ỡ", "ợ", "ứ", "ừ", "ử", "ữ", "ự"], ["ă + sắc", "ă + huyền", "ă + hỏi", "ă + ngã", "ă + nặng", "â + sắc", "â + huyền", "â + hỏi", "â + ngã", "â + nặng", "ê + sắc", "ê + huyền", "ê + hỏi", "ê + ngã", "ê + nặng", "ô + sắc", "ô + huyền", "ô + hỏi", "ô + ngã", "ô + nặng", "ơ + sắc", "ơ + huyền", "ơ + hỏi", "ơ + ngã", "ơ + nặng", "ư + sắc", "ư + huyền", "ư + hỏi", "ư + ngã", "ư + nặng"]) },
  { id: "multigraphs", track: "syllables", title: "Consonant combinations", description: "Read high-frequency digraphs and trigraphs as spelling units inside complete Vietnamese syllables.", items: sounded(["ch", "gh", "gi", "kh", "ng", "ngh", "nh", "ph", "qu", "th", "tr"], ["ch · cha", "gh · ghế", "gi · gia", "kh · khi", "ng · nghe", "ngh · nghỉ", "nh · nhà", "ph · phố", "qu · qua", "th · thu", "tr · tre"], ["cha", "ghế", "gia", "khi", "nghe", "nghỉ", "nhà", "phố", "qua", "thu", "tre"]) },
  { id: "codas", track: "syllables", title: "Syllable endings", description: "Recognize legal written codas and distinguish their spelling from onset combinations.", items: sounded(["-c", "-ch", "-m", "-n", "-ng", "-nh", "-p", "-t"], ["final c · bác", "final ch · sách", "final m · nam", "final n · bạn", "final ng · đang", "final nh · nhanh", "final p · đẹp", "final t · Việt"], ["bác", "sách", "nam", "bạn", "đang", "nhanh", "đẹp", "Việt"]) },
  { id: "numerals", track: "conventions", title: "Numerals and number words", description: "Vietnamese uses familiar decimal numerals; literacy also requires their written Vietnamese names.", items: sounded(digits, ["0 · không", "1 · một", "2 · hai", "3 · ba", "4 · bốn", "5 · năm", "6 · sáu", "7 · bảy", "8 · tám", "9 · chín"], ["không", "một", "hai", "ba", "bốn", "năm", "sáu", "bảy", "tám", "chín"]) },
 ],
 fr: [...alphabet("fr"), { id: "marks-ligatures", track: "conventions", title: "Accents, cedilla and ligatures", description: "Treat each mark and ligature as an orthographic distinction inside real words.", items: named(["à", "â", "ç", "é", "è", "ê", "ë", "î", "ï", "ô", "ù", "û", "ü", "ÿ", "œ", "æ"], ["a grave", "a circumflex", "c cedilla", "e acute", "e grave", "e circumflex", "e diaeresis", "i circumflex", "i diaeresis", "o circumflex", "u grave", "u circumflex", "u diaeresis", "y diaeresis", "oe ligature", "ae ligature"]) }],
 pt: [...alphabet("pt"), { id: "marked-letters", track: "conventions", title: "Portuguese marks", description: "Accents, tilde, and cedilla are tracked separately and then combined in words.", items: named(["á", "â", "ã", "à", "é", "ê", "í", "ó", "ô", "õ", "ú", "ç"], ["a acute", "a circumflex", "a tilde", "a grave", "e acute", "e circumflex", "i acute", "o acute", "o circumflex", "o tilde", "u acute", "c cedilla"]) }],
 de: [...alphabet("de", ["ä", "ö", "ü", "ß"]), { id: "case-conventions", track: "conventions", title: "Case and orthographic alternatives", description: "Learn noun capitalization, ẞ/ß, and the constrained role of ae, oe, ue and ss substitutions.", items: named(["Ä", "Ö", "Ü", "ẞ"], ["capital A umlaut", "capital O umlaut", "capital U umlaut", "capital sharp S"]) }],
 it: [...alphabet("it"), { id: "marked-vowels", track: "conventions", title: "Written vowel accents", description: "Recognize and enter the accented vowels used in ordinary Italian spelling.", items: named(["à", "è", "é", "ì", "ò", "ù"], ["a grave", "e grave", "e acute", "i grave", "o grave", "u grave"]) }],
 zh: [
  { id: "tones", track: "pinyin", title: "Pinyin tones", description: "Hear, distinguish, and enter all four lexical tones plus neutral tone.", items: sounded(["mā", "má", "mǎ", "mà", "ma"], ["first tone", "second tone", "third tone", "fourth tone", "neutral tone"], ["mā", "má", "mǎ", "mà", "ma"]) },
  { id: "initials", track: "pinyin", title: "Pinyin initials", description: "Learn the complete initial inventory through Mandarin sounds, not English letter names.", items: sounded(["b", "p", "m", "f", "d", "t", "n", "l", "g", "k", "h", "j", "q", "x", "zh", "ch", "sh", "r", "z", "c", "s"], ["b", "p", "m", "f", "d", "t", "n", "l", "g", "k", "h", "j", "q", "x", "zh", "ch", "sh", "r", "z", "c", "s"], ["bā", "pā", "mā", "fā", "dā", "tā", "nā", "lā", "gā", "kā", "hā", "jī", "qī", "xī", "zhī", "chī", "shī", "rì", "zī", "cī", "sī"]) },
  { id: "finals", track: "pinyin", title: "Pinyin finals", description: "Decode simple, compound, nasal, and ü-series finals inside legal syllables.", items: sounded(["a", "o", "e", "i", "u", "ü", "ai", "ei", "ao", "ou", "an", "en", "ang", "eng", "ong", "ia", "ie", "iao", "iu", "ian", "in", "iang", "ing", "iong", "ua", "uo", "uai", "ui", "uan", "un", "uang", "ueng", "üe", "üan", "ün", "er"], ["a", "o", "e", "i", "u", "ü", "ai", "ei", "ao", "ou", "an", "en", "ang", "eng", "ong", "ia", "ie", "iao", "iou → iu", "ian", "in", "iang", "ing", "iong", "ua", "uo", "uai", "uei → ui", "uan", "uen → un", "uang", "ueng", "üe", "üan", "ün", "er"], ["ā", "ō", "ē", "yī", "wū", "yū", "āi", "ēi", "āo", "ōu", "ān", "ēn", "āng", "ēng", "dōng", "yā", "yē", "yāo", "yōu", "yān", "yīn", "yāng", "yīng", "yōng", "wā", "wō", "wāi", "wēi", "wān", "wēn", "wāng", "wēng", "yuē", "yuān", "yūn", "ēr"]) },
  { id: "hanzi-foundation", track: "hanzi", title: "Curriculum Hanzi", description: "Characters enter with pronunciation, meaning, components, compounds, and sentence use. The inventory grows with validated course vocabulary.", items: named(["人", "口", "水", "木", "日", "月", "你", "我", "好", "中", "国", "学", "生", "校", "朋", "友", "今", "天", "明", "喝"], ["rén · person", "kǒu · mouth", "shuǐ · water", "mù · wood", "rì · sun/day", "yuè · moon/month", "nǐ · you", "wǒ · I/me", "hǎo · good", "zhōng · middle", "guó · country", "xué · learn", "shēng · life/student", "xiào · school", "péng · friend", "yǒu · friend", "jīn · present", "tiān · day", "míng · bright/next", "hē · drink"]) },
  { id: "hanzi-numerals", track: "hanzi", title: "Number characters", description: "Recognize and input the foundational number characters used in words, dates, and quantities.", items: named(["零", "一", "二", "三", "四", "五", "六", "七", "八", "九", "十"], ["líng · zero", "yī · one", "èr · two", "sān · three", "sì · four", "wǔ · five", "liù · six", "qī · seven", "bā · eight", "jiǔ · nine", "shí · ten"]) },
 ],
 ja: [
  { id: "hiragana", track: "hiragana", title: "Hiragana inventory", description: "Learn all basic hiragana by sound row, then decode unfamiliar combinations without rōmaji.", items: named(chars("あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん"), "a i u e o ka ki ku ke ko sa shi su se so ta chi tsu te to na ni nu ne no ha hi fu he ho ma mi mu me mo ya yu yo ra ri ru re ro wa o n".split(" ")) },
  { id: "katakana", track: "katakana", title: "Katakana inventory", description: "Learn all basic katakana and discriminate them from visually similar kana.", items: named(chars("アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲン"), "a i u e o ka ki ku ke ko sa shi su se so ta chi tsu te to na ni nu ne no ha hi fu he ho ma mi mu me mo ya yu yo ra ri ru re ro wa o n".split(" ")) },
  { id: "kana-marks", track: "kana-composition", title: "Voiced, semi-voiced and small forms", description: "Marks and reduced-size kana alter sound and composition; they are not decoration.", items: named(["が", "ざ", "だ", "ば", "ぱ", "ゃ", "ゅ", "ょ", "っ", "ー"], ["ga row with dakuten", "za row with dakuten", "da row with dakuten", "ba row with dakuten", "pa row with handakuten", "small ya", "small yu", "small yo", "small tsu", "long-vowel mark"]) },
  { id: "number-kanji", track: "kanji", title: "Foundational number kanji", description: "Track readings inside real number words and expressions rather than assigning one reading per character.", items: named(["〇", "一", "二", "三", "四", "五", "六", "七", "八", "九", "十"], ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"]) },
 ],
 ko: [
  { id: "basic-vowels", track: "jamo", title: "Basic vowels", description: "Learn the ten foundational vowel forms and how vertical or horizontal orientation shapes a syllable block.", items: named(chars("ㅏㅑㅓㅕㅗㅛㅜㅠㅡㅣ"), ["a", "ya", "eo", "yeo", "o", "yo", "u", "yu", "eu", "i"]) },
  { id: "additional-vowels", track: "jamo", title: "Additional and compound vowels", description: "Distinguish the remaining modern vowels and reconstruct their combinations inside blocks.", items: named(chars("ㅐㅒㅔㅖㅘㅙㅚㅝㅞㅟㅢ"), ["ae", "yae", "e", "ye", "wa", "wae", "oe", "wo", "we", "wi", "ui"]) },
  { id: "plain-consonants", track: "jamo", title: "Plain consonants", description: "Learn the foundational consonant forms, including ㅇ in its silent-initial and final ng roles.", items: named(chars("ㄱㄴㄷㄹㅁㅂㅅㅇㅈㅎ"), ["g/k", "n", "d/t", "r/l", "m", "b/p", "s", "silent/ng", "j", "h"]) },
  { id: "aspirated-consonants", track: "jamo", title: "Aspirated consonants", description: "Distinguish the four consonants produced with stronger aspiration from their plain counterparts.", items: named(chars("ㅋㅌㅍㅊ"), ["k", "t", "p", "ch"]) },
  { id: "tense-consonants", track: "jamo", title: "Tense consonants", description: "Treat the five doubled forms as a phonological series, not typographic duplicates.", items: named(chars("ㄲㄸㅃㅆㅉ"), ["kk", "tt", "pp", "ss", "jj"]) },
  { id: "batchim", track: "blocks", title: "Written final consonants", description: "Recognize single and clustered batchim spellings, then connect them to context-sensitive pronunciation.", items: named(["ㄱ", "ㄲ", "ㄳ", "ㄴ", "ㄵ", "ㄶ", "ㄷ", "ㄹ", "ㄺ", "ㄻ", "ㄼ", "ㄽ", "ㄾ", "ㄿ", "ㅀ", "ㅁ", "ㅂ", "ㅄ", "ㅅ", "ㅆ", "ㅇ", "ㅈ", "ㅊ", "ㅋ", "ㅌ", "ㅍ", "ㅎ"], ["final ㄱ", "final ㄲ", "final ㄳ", "final ㄴ", "final ㄵ", "final ㄶ", "final ㄷ", "final ㄹ", "final ㄺ", "final ㄻ", "final ㄼ", "final ㄽ", "final ㄾ", "final ㄿ", "final ㅀ", "final ㅁ", "final ㅂ", "final ㅄ", "final ㅅ", "final ㅆ", "final ㅇ", "final ㅈ", "final ㅊ", "final ㅋ", "final ㅌ", "final ㅍ", "final ㅎ"]) },
  { id: "numerals", track: "conventions", title: "Numerals in Korean text", description: "Connect decimal forms with native Korean and Sino-Korean number words in context.", items: named(digits, ["영/공 · zero", "일/하나 · one", "이/둘 · two", "삼/셋 · three", "사/넷 · four", "오/다섯 · five", "육/여섯 · six", "칠/일곱 · seven", "팔/여덟 · eight", "구/아홉 · nine"]) },
 ],
 ar: [
  { id: "letters", track: "letters", title: "Twenty-eight Arabic letters", description: "Learn each letter’s sound and joining behavior across isolated, initial, medial, and final forms.", items: named(chars("ابتثجحخدذرزسشصضطظعغفقكلمنهوي"), "alif bāʾ tāʾ thāʾ jīm ḥāʾ khāʾ dāl dhāl rāʾ zāy sīn shīn ṣād ḍād ṭāʾ ẓāʾ ʿayn ghayn fāʾ qāf kāf lām mīm nūn hāʾ wāw yāʾ".split(" ")) },
  { id: "vowel-signs", track: "vocalization", title: "Vowel and reading signs", description: "Recognize short vowels, silence, doubling, and nunation in vocalized text, then read increasingly unvocalized text.", items: named(["◌َ", "◌ِ", "◌ُ", "◌ْ", "◌ّ", "◌ً", "◌ٍ", "◌ٌ"], ["fatḥa", "kasra", "ḍamma", "sukūn", "shadda", "fatḥatān", "kasratān", "ḍammatān"]) },
  { id: "numerals", track: "conventions", title: "Arabic-Indic numerals", description: "Recognize the numeral forms commonly used in Arabic-script contexts, with regional variation noted.", items: named(chars("٠١٢٣٤٥٦٧٨٩"), ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]) },
 ],
 hi: [
  { id: "vowels", track: "devanagari", title: "Independent vowels", description: "Learn vowel forms used at syllable onset before mapping them to dependent signs.", items: named(chars("अआइईउऊऋएऐओऔ"), ["a", "ā", "i", "ī", "u", "ū", "ṛ", "e", "ai", "o", "au"]) },
  { id: "consonants", track: "devanagari", title: "Consonant inventory", description: "Learn consonants by place and manner, preserving aspiration and retroflex contrasts.", items: named(chars("कखगघङचछजझञटठडढणतथदधनपफबभमयरलवशषसह"), "ka kha ga gha ṅa ca cha ja jha ña ṭa ṭha ḍa ḍha ṇa ta tha da dha na pa pha ba bha ma ya ra la va śa ṣa sa ha".split(" ")) },
  { id: "matras", track: "composition", title: "Dependent vowel signs", description: "Combine consonants and matras in logical input order while reading their visual placement.", items: named(["ा", "ि", "ी", "ु", "ू", "ृ", "े", "ै", "ो", "ौ"], ["ā sign", "i sign", "ī sign", "u sign", "ū sign", "ṛ sign", "e sign", "ai sign", "o sign", "au sign"]) },
  { id: "marks", track: "composition", title: "Conjunct and nasal signs", description: "Learn virāma, anusvāra, chandrabindu, visarga, and nukta as structural marks.", items: named(["्", "ं", "ँ", "ः", "़"], ["virāma/halant", "anusvāra", "chandrabindu", "visarga", "nukta"]) },
  { id: "numerals", track: "conventions", title: "Devanagari numerals", description: "Recognize and enter the traditional numeral forms while also reading modern international digits.", items: named(chars("०१२३४५६७८९"), ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]) },
 ],
 ru: [{ id: "cyrillic", track: "letters", title: "Thirty-three Cyrillic letters", description: "Learn the actual Cyrillic code points and sounds, especially forms that resemble Latin letters.", items: named(chars("абвгдеёжзийклмнопрстуфхцчшщъыьэюя"), "a b v g d ye yo zh z i short-i k l m n o p r s t u f kh ts ch sh shch hard y soft e yu ya".split(" ")) }, { id: "numerals", track: "conventions", title: "Numerals in Russian text", description: "Recognize decimal numerals and connect them to written Russian number words.", items: named(digits, ["ноль", "один", "два", "три", "четыре", "пять", "шесть", "семь", "восемь", "девять"]) }],
};
