import type { Course, Exercise } from "./model";

type Passage = [text: string, meaning: string, question: string, answer: string, distractors: string[]];
const passages: Record<Course["language"], Passage[]> = {
 en: [["I read a book at home.", "I read a book at home.", "Where does the person read?", "At home", ["At school", "On a train"]], ["The door is open. A cat is in the house.", "The door is open. A cat is in the house.", "What is in the house?", "A cat", ["A dog", "A tree"]], ["Although the train was late, I arrived before the meeting began.", "Although the train was late, I arrived before the meeting began.", "When did the person arrive?", "Before the meeting began", ["After the meeting", "The next day"]], ["Reading becomes more independent when familiar patterns can be recognized in unfamiliar sentences.", "Reading becomes more independent when familiar patterns can be recognized in unfamiliar sentences.", "What supports independent reading?", "Recognizing familiar patterns in unfamiliar sentences", ["Memorizing one sentence", "Avoiding unfamiliar text"]]],
 es: [["Leo un libro en casa.", "I read a book at home.", "Where does the person read?", "At home", ["At school", "On a train"]], ["La puerta está abierta. Hay un perro en la casa.", "The door is open. There is a dog in the house.", "What is in the house?", "A dog", ["A cat", "A tree"]], ["Aunque el tren llegó tarde, llegué antes de que empezara la reunión.", "Although the train arrived late, I arrived before the meeting began.", "When did the speaker arrive?", "Before the meeting began", ["After the meeting", "The next day"]], ["La lectura se vuelve más independiente cuando reconocemos patrones conocidos en oraciones nuevas.", "Reading becomes more independent when we recognize familiar patterns in new sentences.", "What supports independent reading?", "Recognizing familiar patterns in new sentences", ["Memorizing one sentence", "Avoiding new text"]]],
 vi: [["Tôi đọc sách ở nhà.", "I read a book at home.", "Where does the person read?", "At home", ["At school", "On a train"]], ["Bạn tôi đi học. Tôi ở nhà và đọc sách.", "My friend goes to school. I am at home and read a book.", "Who goes to school?", "The speaker's friend", ["The speaker", "The teacher"]], ["Hôm nay tôi nghỉ ở nhà. Ngày mai tôi đến trường.", "Today I rest at home. Tomorrow I go to school.", "When does the speaker go to school?", "Tomorrow", ["Today", "Yesterday"]], ["Mặc dù tàu đến muộn, tôi vẫn đến trước khi cuộc họp bắt đầu.", "Although the train arrived late, I still arrived before the meeting began.", "When did the speaker arrive?", "Before the meeting began", ["After the meeting", "The next day"]], ["Việc đọc trở nên độc lập hơn khi ta nhận ra những mẫu quen thuộc trong các câu mới.", "Reading becomes more independent when we recognize familiar patterns in new sentences.", "What supports independent reading?", "Recognizing familiar patterns in new sentences", ["Memorizing one sentence", "Avoiding new text"]]],
 fr: [["Je lis un livre à la maison.", "I read a book at home.", "Where does the person read?", "At home", ["At school", "On a train"]], ["La porte est ouverte. Il y a un chat dans la maison.", "The door is open. There is a cat in the house.", "What is in the house?", "A cat", ["A dog", "A tree"]], ["Bien que le train soit arrivé en retard, je suis arrivé avant le début de la réunion.", "Although the train arrived late, I arrived before the meeting began.", "When did the speaker arrive?", "Before the meeting began", ["After the meeting", "The next day"]], ["La lecture devient plus autonome lorsqu’on reconnaît des structures familières dans des phrases nouvelles.", "Reading becomes more independent when familiar structures are recognized in new sentences.", "What supports independent reading?", "Recognizing familiar structures in new sentences", ["Memorizing one sentence", "Avoiding new text"]]],
 pt: [["Eu leio um livro em casa.", "I read a book at home.", "Where does the person read?", "At home", ["At school", "On a train"]], ["A porta está aberta. Há um gato na casa.", "The door is open. There is a cat in the house.", "What is in the house?", "A cat", ["A dog", "A tree"]], ["Embora o trem tenha chegado atrasado, cheguei antes do início da reunião.", "Although the train arrived late, I arrived before the meeting began.", "When did the speaker arrive?", "Before the meeting began", ["After the meeting", "The next day"]], ["A leitura se torna mais independente quando reconhecemos padrões conhecidos em frases novas.", "Reading becomes more independent when we recognize familiar patterns in new sentences.", "What supports independent reading?", "Recognizing familiar patterns in new sentences", ["Memorizing one sentence", "Avoiding new text"]]],
 de: [["Ich lese zu Hause ein Buch.", "I read a book at home.", "Where does the person read?", "At home", ["At school", "On a train"]], ["Die Tür ist offen. Eine Katze ist im Haus.", "The door is open. A cat is in the house.", "What is in the house?", "A cat", ["A dog", "A tree"]], ["Obwohl der Zug Verspätung hatte, kam ich vor Beginn der Besprechung an.", "Although the train was delayed, I arrived before the meeting began.", "When did the speaker arrive?", "Before the meeting began", ["After the meeting", "The next day"]], ["Lesen wird selbstständiger, wenn wir vertraute Muster in neuen Sätzen erkennen.", "Reading becomes more independent when we recognize familiar patterns in new sentences.", "What supports independent reading?", "Recognizing familiar patterns in new sentences", ["Memorizing one sentence", "Avoiding new text"]]],
 it: [["Leggo un libro a casa.", "I read a book at home.", "Where does the person read?", "At home", ["At school", "On a train"]], ["La porta è aperta. C'è un gatto in casa.", "The door is open. There is a cat in the house.", "What is in the house?", "A cat", ["A dog", "A tree"]], ["Sebbene il treno fosse in ritardo, sono arrivato prima dell’inizio della riunione.", "Although the train was late, I arrived before the meeting began.", "When did the speaker arrive?", "Before the meeting began", ["After the meeting", "The next day"]], ["La lettura diventa più autonoma quando riconosciamo strutture familiari in frasi nuove.", "Reading becomes more independent when we recognize familiar structures in new sentences.", "What supports independent reading?", "Recognizing familiar structures in new sentences", ["Memorizing one sentence", "Avoiding new text"]]],
 zh: [["我在家看书。", "I read a book at home.", "Where does the person read?", "At home", ["At school", "On a train"]], ["今天我在家。明天我去学校。", "Today I am at home. Tomorrow I go to school.", "When does the person go to school?", "Tomorrow", ["Today", "Yesterday"]], ["虽然火车晚点了，但我还是在会议开始前到了。", "Although the train was late, I still arrived before the meeting began.", "When did the speaker arrive?", "Before the meeting began", ["After the meeting", "The next day"]], ["当我们能在新句子中认出熟悉的结构时，阅读就会变得更加独立。", "Reading becomes more independent when we can recognize familiar structures in new sentences.", "What supports independent reading?", "Recognizing familiar structures in new sentences", ["Memorizing one sentence", "Avoiding new text"]]],
 ja: [["家で本を読みます。", "I read a book at home.", "Where does the person read?", "At home", ["At school", "On a train"]], ["今日は家にいます。明日は学校に行きます。", "Today I am at home. Tomorrow I go to school.", "When does the person go to school?", "Tomorrow", ["Today", "Yesterday"]], ["電車は遅れましたが、会議が始まる前に着きました。", "The train was late, but I arrived before the meeting began.", "When did the speaker arrive?", "Before the meeting began", ["After the meeting", "The next day"]], ["新しい文の中で知っている型を見つけられると、もっと自分の力で読めるようになります。", "When we can find familiar patterns in new sentences, we become able to read more independently.", "What supports independent reading?", "Finding familiar patterns in new sentences", ["Memorizing one sentence", "Avoiding new text"]]],
 ko: [["집에서 책을 읽어요.", "I read a book at home.", "Where does the person read?", "At home", ["At school", "On a train"]], ["오늘은 집에 있어요. 내일은 학교에 가요.", "Today I am at home. Tomorrow I go to school.", "When does the person go to school?", "Tomorrow", ["Today", "Yesterday"]], ["기차가 늦었지만 회의가 시작되기 전에 도착했어요.", "The train was late, but I arrived before the meeting began.", "When did the speaker arrive?", "Before the meeting began", ["After the meeting", "The next day"]], ["새로운 문장에서 익숙한 구조를 알아볼 수 있으면 더 독립적으로 읽을 수 있어요.", "When we can recognize familiar structures in new sentences, we can read more independently.", "What supports independent reading?", "Recognizing familiar structures in new sentences", ["Memorizing one sentence", "Avoiding new text"]]],
 ar: [["أقرأ كتابًا في البيت.", "I read a book at home.", "Where does the person read?", "At home", ["At school", "On a train"]], ["أنا في البيت اليوم. غدًا أذهب إلى المدرسة.", "I am at home today. Tomorrow I go to school.", "When does the person go to school?", "Tomorrow", ["Today", "Yesterday"]], ["مع أن القطار تأخر، وصلت قبل أن يبدأ الاجتماع.", "Although the train was late, I arrived before the meeting began.", "When did the speaker arrive?", "Before the meeting began", ["After the meeting", "The next day"]], ["تصبح القراءة أكثر استقلالًا عندما نتعرف على أنماط مألوفة في جمل جديدة.", "Reading becomes more independent when we recognize familiar patterns in new sentences.", "What supports independent reading?", "Recognizing familiar patterns in new sentences", ["Memorizing one sentence", "Avoiding new text"]]],
 hi: [["मैं घर पर किताब पढ़ता हूँ।", "I read a book at home (male speaker).", "Where does the person read?", "At home", ["At school", "On a train"]], ["आज मैं घर पर हूँ। कल मैं स्कूल जाऊँगा।", "Today I am at home. Tomorrow I will go to school (male speaker).", "When does the person go to school?", "Tomorrow", ["Today", "Yesterday"]], ["ट्रेन देर से आई, फिर भी मैं बैठक शुरू होने से पहले पहुँच गया।", "The train arrived late, yet I arrived before the meeting began (male speaker).", "When did the speaker arrive?", "Before the meeting began", ["After the meeting", "The next day"]], ["जब हम नए वाक्यों में परिचित संरचनाओं को पहचानते हैं, तो पढ़ना अधिक स्वतंत्र हो जाता है।", "When we recognize familiar structures in new sentences, reading becomes more independent.", "What supports independent reading?", "Recognizing familiar structures in new sentences", ["Memorizing one sentence", "Avoiding new text"]]],
 ru: [["Я читаю книгу дома.", "I read a book at home.", "Where does the person read?", "At home", ["At school", "On a train"]], ["Сегодня я дома. Завтра я иду в школу.", "Today I am at home. Tomorrow I go to school.", "When does the person go to school?", "Tomorrow", ["Today", "Yesterday"]], ["Хотя поезд опоздал, я приехал до начала встречи.", "Although the train was late, I arrived before the meeting began.", "When did the speaker arrive?", "Before the meeting began", ["After the meeting", "The next day"]], ["Чтение становится более самостоятельным, когда мы узнаём знакомые структуры в новых предложениях.", "Reading becomes more independent when we recognize familiar structures in new sentences.", "What supports independent reading?", "Recognizing familiar structures in new sentences", ["Memorizing one sentence", "Avoiding new text"]]],
};

const heldOut: Record<Course["language"], { text: string; prompt: string; answer: string; alternatives: string[]; explanation: string }> = {
 en: { text: "Tomorrow I will read a new book at school.", prompt: "Where will the person read tomorrow?", answer: "At school", alternatives: ["At home", "On the train"], explanation: "Tomorrow locates the event in the future. At school gives the location; a new book is what will be read." },
 es: { text: "Mañana leeré un libro nuevo en la escuela.", prompt: "Where will the person read tomorrow?", answer: "At school", alternatives: ["At home", "On the train"], explanation: "Mañana locates the event in the future. En la escuela gives the location; un libro nuevo is what will be read." },
 vi: { text: "Ngày mai tôi sẽ đọc một cuốn sách mới ở trường.", prompt: "Where will the speaker read tomorrow?", answer: "At school", alternatives: ["At home", "On the train"], explanation: "Ngày mai and sẽ locate the event in the future. Ở trường gives the location; một cuốn sách mới is what will be read." },
 fr: { text: "Demain, je lirai un nouveau livre à l’école.", prompt: "Where will the person read tomorrow?", answer: "At school", alternatives: ["At home", "On the train"], explanation: "Demain locates the event in the future. À l’école gives the location; un nouveau livre is what will be read." },
 pt: { text: "Amanhã, vou ler um livro novo na escola.", prompt: "Where will the person read tomorrow?", answer: "At school", alternatives: ["At home", "On the train"], explanation: "Amanhã locates the event in the future. Na escola gives the location; um livro novo is what will be read." },
 de: { text: "Morgen werde ich in der Schule ein neues Buch lesen.", prompt: "Where will the person read tomorrow?", answer: "At school", alternatives: ["At home", "On the train"], explanation: "Morgen locates the event in the future. In der Schule gives the location; ein neues Buch is what will be read." },
 it: { text: "Domani leggerò un nuovo libro a scuola.", prompt: "Where will the person read tomorrow?", answer: "At school", alternatives: ["At home", "On the train"], explanation: "Domani locates the event in the future. A scuola gives the location; un nuovo libro is what will be read." },
 zh: { text: "明天我会在学校看一本新书。", prompt: "Where will the person read tomorrow?", answer: "At school", alternatives: ["At home", "On the train"], explanation: "明天 locates the event tomorrow. 在学校 gives the location; 一本新书 is the new book being read." },
 ja: { text: "明日、学校で新しい本を読みます。", prompt: "Where will the person read tomorrow?", answer: "At school", alternatives: ["At home", "On the train"], explanation: "明日 locates the event tomorrow. 学校で marks the location of the action; 新しい本 is the new book being read." },
 ko: { text: "내일 학교에서 새 책을 읽을 거예요.", prompt: "Where will the person read tomorrow?", answer: "At school", alternatives: ["At home", "On the train"], explanation: "내일 locates the event tomorrow. 학교에서 marks the location of the action; 새 책 is the new book being read." },
 ar: { text: "غدًا سأقرأ كتابًا جديدًا في المدرسة.", prompt: "Where will the person read tomorrow?", answer: "At school", alternatives: ["At home", "On the train"], explanation: "غدًا locates the event tomorrow. في المدرسة gives the location; كتابًا جديدًا is the new book being read." },
 hi: { text: "कल मैं स्कूल में एक नई किताब पढ़ूँगा।", prompt: "Where will the person read tomorrow?", answer: "At school", alternatives: ["At home", "On the train"], explanation: "कल is tomorrow in this context. स्कूल में gives the location; एक नई किताब is the new book being read. The verb form here uses a male speaker." },
 ru: { text: "Завтра я буду читать новую книгу в школе.", prompt: "Where will the person read tomorrow?", answer: "At school", alternatives: ["At home", "On the train"], explanation: "Завтра locates the event tomorrow. В школе gives the location; новую книгу is the new book being read." },
};

export function addReading(course: Course) {
 course.tracks.push({ id: "reading", title: "Sentences and reading", description: "Read connected text, recover meaning and reconstruct the written sentence." });
 passages[course.language].forEach(([text, meaning, question, answer, distractors], i) => {
  const id = `${course.language}-reading-${i}`, skill = `${course.language}:reading:${i}`;
  const explanation = `Read the complete thought, using word boundaries, punctuation and the script patterns you have studied. ${meaning}`;
  const exercises: Exercise[] = [
   { id: `${id}:comprehension`, skill, direction: "meaning", kind: "choice", prompt: question, cue: text, answer, choices: [answer, ...distractors], explanation },
   { id: `${id}:input`, skill, direction: "input", kind: "input", prompt: `Reconstruct the sentence: ${meaning}`, answer: text, explanation },
   { id: `${id}:listen`, skill, direction: "sound-form", kind: "input", prompt: "Listen and enter the sentence, including its punctuation.", audio: text, answer: text, explanation },
  ];
  const level: Course["units"][number]["level"] = i < 2 ? "A1" : i === 2 ? "A2" : i === 3 ? "B1" : "B2";
  course.units.push({ id, title: i ? "Connected thoughts" : "Read a complete sentence", track: "reading", stage: i ? "reading" : "sentences", level, prerequisites: i ? [`${course.language}-reading-${i - 1}`] : [course.units.filter(u => u.stage === "words").at(-1)!.id], objective: "Understand the information in a short everyday text and reconstruct its writing.", explanation, forms: [text], example: text, meaning, exercises, sourceIds: ["cefr"], courseTerms: [] });
 });
 const transfer = heldOut[course.language], id = `${course.language}-reading-transfer`;
 course.units.push({ id, title: "Read a new combination independently", track: "reading", stage: "reading", level: "A2", prerequisites: [`${course.language}-reading-${passages[course.language].length - 1}`], objective: "Recover meaning from a new combination of known writing patterns.", explanation: "This sentence is withheld from the study model. Read it as a new combination. Listening or opening the explanation remains available, but is recorded as support.", forms: [], example: "", meaning: "", sourceIds: ["cefr"], courseTerms: [], exercises: [
  { id: `${id}:meaning`, skill: `${course.language}:reading:held-out`, direction: "transfer", kind: "choice", prompt: transfer.prompt, cue: transfer.text, answer: transfer.answer, answerLanguage: "en", choices: [transfer.answer, ...transfer.alternatives], explanation: transfer.explanation, transfer: true },
  { id: `${id}:input`, skill: `${course.language}:reading:held-out`, direction: "input", kind: "input", prompt: "Reconstruct the sentence from its meaning: Tomorrow I will read a new book at school.", answer: transfer.text, explanation: transfer.explanation },
 ] });
}
