const c = (spanish, meaning, vietnamese, role) => ({ spanish, meaning, vietnamese, role });
const l = (title, skill, spanish, english, vietnamese, focus, pattern, bridgePattern, units) =>
  [title, skill, spanish, english, vietnamese, focus, pattern, bridgePattern, units];

const groups = [
  [37, "Nuanced accounts", [
    l("Reframing the beginning", "viewpoint in narration", "Lo que al principio parecía un fracaso terminó convirtiéndose en una oportunidad.", "What at first seemed like a failure ended up becoming an opportunity.", "Điều ban đầu có vẻ là thất bại cuối cùng lại trở thành một cơ hội.", "terminó convirtiéndose", "free relative + imperfect viewpoint + resultative pronominal verb", "điều + ban đầu + cuối cùng lại trở thành", [c("Lo que al principio parecía", "what at first seemed", "Điều ban đầu có vẻ", "frames the event from the initial viewpoint"), c("un fracaso", "a failure", "là thất bại", "names the first interpretation"), c("terminó convirtiéndose", "ended up becoming", "cuối cùng lại trở thành", "marks the eventual transformation"), c("en una oportunidad", "an opportunity", "một cơ hội", "names the revised outcome")]),
    l("Controlling chronology", "layered past account", "Para cuando nos avisaron, ya llevábamos horas intentando resolver el problema.", "By the time they notified us, we had already spent hours trying to solve the problem.", "Đến khi họ báo cho chúng tôi, chúng tôi đã cố giải quyết vấn đề suốt nhiều giờ.", "llevábamos intentando", "para cuando + preterite + imperfect duration + gerund", "đến khi + đã + suốt", [c("Para cuando nos avisaron", "by the time they notified us", "Đến khi họ báo cho chúng tôi", "sets the later reference point"), c("ya llevábamos horas", "we had already spent hours", "chúng tôi đã suốt nhiều giờ", "measures the earlier ongoing effort"), c("intentando resolver", "trying to solve", "cố giải quyết", "names the sustained activity"), c("el problema", "the problem", "vấn đề", "identifies its object")]),
    l("Foregrounding the cause", "emphatic explanation", "Fue la falta de comunicación lo que provocó la mayoría de los errores.", "It was the lack of communication that caused most of the errors.", "Chính việc thiếu giao tiếp đã gây ra phần lớn sai sót.", "Fue... lo que", "cleft focus + preterite cause", "chính + đã", [c("Fue", "it was", "Chính", "opens the emphatic focus"), c("la falta de comunicación", "the lack of communication", "việc thiếu giao tiếp", "identifies the focused cause"), c("lo que provocó", "that caused", "đã gây ra", "links that cause to its effect"), c("la mayoría de los errores", "most of the errors", "phần lớn sai sót", "names the effect")]),
    l("Changing viewpoint", "retrospective qualification", "Visto con distancia, quizá exageramos la importancia de aquel desacuerdo.", "Seen from a distance, perhaps we exaggerated the importance of that disagreement.", "Nhìn lại với khoảng cách, có lẽ chúng tôi đã phóng đại tầm quan trọng của bất đồng đó.", "Visto con distancia", "detached participle + probability + preterite", "nhìn lại + có lẽ + đã", [c("Visto con distancia", "seen from a distance", "Nhìn lại với khoảng cách", "establishes a later reflective viewpoint"), c("quizá", "perhaps", "có lẽ", "softens the judgment"), c("exageramos la importancia", "we exaggerated the importance", "chúng tôi đã phóng đại tầm quan trọng", "states the revised evaluation"), c("de aquel desacuerdo", "of that disagreement", "của bất đồng đó", "identifies the past issue")]),
  ]],
  [38, "Argument and evidence", [
    l("A central claim", "sustained argument", "Los datos sugieren que invertir ahora resultaría menos costoso que esperar.", "The data suggest that investing now would be less costly than waiting.", "Dữ liệu cho thấy đầu tư ngay bây giờ sẽ ít tốn kém hơn là chờ đợi.", "sugieren que", "evidential claim + conditional comparison", "cho thấy + sẽ + ít hơn", [c("Los datos sugieren que", "the data suggest that", "Dữ liệu cho thấy", "grounds the claim in evidence"), c("invertir ahora", "investing now", "đầu tư ngay bây giờ", "names the first course of action"), c("resultaría menos costoso", "would be less costly", "sẽ ít tốn kém hơn", "states the projected comparison"), c("que esperar", "than waiting", "là chờ đợi", "names the alternative")]),
    l("Conceding a point", "concession and counterclaim", "Aunque la crítica sea válida, no invalida el conjunto de la propuesta.", "Although the criticism may be valid, it does not invalidate the proposal as a whole.", "Mặc dù lời phê bình có cơ sở, nó không làm mất giá trị của toàn bộ đề xuất.", "Aunque... sea", "concessive subjunctive + negated counterclaim", "mặc dù + có cơ sở + không", [c("Aunque la crítica sea válida", "although the criticism may be valid", "Mặc dù lời phê bình có cơ sở", "concedes the opposing point"), c("no invalida", "it does not invalidate", "nó không làm mất giá trị", "limits the consequence of that concession"), c("el conjunto", "the whole", "của toàn bộ", "marks the full scope and its relation"), c("de la propuesta", "of the proposal", "đề xuất", "identifies what remains standing")]),
    l("Challenging an assumption", "critical response", "Ese argumento parte del supuesto de que todas las personas tienen las mismas opciones.", "That argument starts from the assumption that everyone has the same options.", "Lập luận đó dựa trên giả định rằng mọi người đều có những lựa chọn như nhau.", "parte del supuesto", "argument frame + noun clause", "dựa trên giả định rằng", [c("Ese argumento", "that argument", "Lập luận đó", "identifies the claim being examined"), c("parte del supuesto", "starts from the assumption", "dựa trên giả định", "reveals its underlying premise"), c("de que todas las personas", "that everyone", "rằng mọi người đều", "introduces the assumed group"), c("tienen las mismas opciones", "have the same options", "có những lựa chọn như nhau", "states the challenged assumption")]),
    l("Weighing evidence", "qualified conclusion", "En conjunto, la evidencia es convincente, si bien quedan preguntas por resolver.", "Taken together, the evidence is convincing, although questions remain to be resolved.", "Nhìn chung, bằng chứng khá thuyết phục, tuy vẫn còn những câu hỏi cần giải quyết.", "si bien", "summary stance + formal concession", "nhìn chung + tuy vẫn còn", [c("En conjunto", "taken together", "Nhìn chung", "signals an overall assessment"), c("la evidencia es convincente", "the evidence is convincing", "bằng chứng khá thuyết phục", "states the main evaluation"), c("si bien", "although", "tuy", "introduces a formal qualification"), c("quedan preguntas por resolver", "questions remain to be resolved", "vẫn còn những câu hỏi cần giải quyết", "identifies unresolved limits")]),
  ]],
  [39, "Professional precision", [
    l("Defining scope", "formal proposal constraint", "La propuesta contempla ampliar el servicio sin modificar el presupuesto aprobado.", "The proposal provides for expanding the service without changing the approved budget.", "Đề xuất dự kiến mở rộng dịch vụ mà không thay đổi ngân sách đã được phê duyệt.", "contempla ampliar", "formal planning verb + infinitive + sin", "dự kiến + mà không + đã được", [c("La propuesta contempla", "the proposal provides for", "Đề xuất dự kiến", "frames the documented scope"), c("ampliar el servicio", "expanding the service", "mở rộng dịch vụ", "states the planned change"), c("sin modificar", "without changing", "mà không thay đổi", "excludes an alteration"), c("el presupuesto aprobado", "the approved budget", "ngân sách đã được phê duyệt", "names the protected constraint")]),
    l("Documenting a decision", "institutional record", "Se acordó posponer la implementación hasta que concluyera la evaluación técnica.", "It was agreed to postpone implementation until the technical evaluation was concluded.", "Các bên đã thống nhất hoãn việc triển khai cho đến khi hoàn tất đánh giá kỹ thuật.", "Se acordó", "impersonal agreement + infinitive + imperfect subjunctive", "đã thống nhất + cho đến khi", [c("Se acordó", "it was agreed", "Các bên đã thống nhất", "records a collective decision without foregrounding individuals"), c("posponer la implementación", "to postpone implementation", "hoãn việc triển khai", "states the decision"), c("hasta que concluyera", "until it was concluded", "cho đến khi hoàn tất", "sets the required endpoint"), c("la evaluación técnica", "the technical evaluation", "đánh giá kỹ thuật", "names the prerequisite process")]),
    l("Qualifying feasibility", "professional risk statement", "El objetivo sería alcanzable siempre que se asignaran recursos adicionales.", "The objective would be achievable provided that additional resources were allocated.", "Mục tiêu sẽ khả thi với điều kiện có thêm nguồn lực được phân bổ.", "siempre que", "conditional assessment + condition + passive subjunctive", "sẽ + với điều kiện + được", [c("El objetivo sería alcanzable", "the objective would be achievable", "Mục tiêu sẽ khả thi", "gives a conditional feasibility judgment"), c("siempre que", "provided that", "với điều kiện", "introduces the requirement"), c("se asignaran", "were allocated", "được phân bổ", "states the required institutional action"), c("recursos adicionales", "additional resources", "có thêm nguồn lực", "names what is required")]),
    l("Diplomatic correction", "formal clarification", "Conviene precisar que el informe describe una tendencia, no una certeza.", "It is worth clarifying that the report describes a trend, not a certainty.", "Cần làm rõ rằng báo cáo mô tả một xu hướng, chứ không phải một điều chắc chắn.", "Conviene precisar", "impersonal recommendation + corrective contrast", "cần làm rõ rằng + chứ không phải", [c("Conviene precisar que", "it is worth clarifying that", "Cần làm rõ rằng", "introduces a diplomatic correction"), c("el informe describe", "the report describes", "báo cáo mô tả", "attributes the limited claim"), c("una tendencia", "a trend", "một xu hướng", "states what the evidence supports"), c("no una certeza", "not a certainty", "chứ không phải một điều chắc chắn", "excludes overstatement")]),
  ]],
  [40, "Humor and implication", [
    l("Understatement", "implied criticism", "Decir que la reunión fue poco productiva sería quedarse corto.", "To say the meeting was not very productive would be an understatement.", "Nói cuộc họp không mấy hiệu quả vẫn còn là nói nhẹ.", "quedarse corto", "infinitive subject + conditional idiom", "nói... vẫn còn là nói nhẹ", [c("Decir que", "to say that", "Nói", "introduces the characterization being judged"), c("la reunión fue poco productiva", "the meeting was not very productive", "cuộc họp không mấy hiệu quả", "states the deliberately mild description"), c("sería", "would be", "vẫn còn là", "marks the evaluative result"), c("quedarse corto", "to fall short; understate", "nói nhẹ", "reveals that reality was worse")]),
    l("Reading implication", "pragmatic inference", "Cuando dijo que la idea era 'interesante', todos entendimos lo que quería evitar decir.", "When she said the idea was 'interesting,' we all understood what she wanted to avoid saying.", "Khi cô ấy nói ý tưởng 'thú vị', tất cả chúng tôi đều hiểu điều cô ấy muốn tránh nói ra.", "lo que quería evitar decir", "reported evaluation + free relative implication", "nói... đều hiểu điều... tránh nói", [c("Cuando dijo", "when she said", "Khi cô ấy nói", "sets the interpretive moment"), c("que la idea era 'interesante'", "that the idea was 'interesting'", "ý tưởng 'thú vị'", "quotes the surface evaluation"), c("todos entendimos", "we all understood", "tất cả chúng tôi đều hiểu", "marks shared inference"), c("lo que quería evitar decir", "what she wanted to avoid saying", "điều cô ấy muốn tránh nói ra", "names the unstated meaning")]),
    l("Playful contrast", "contextual irony", "Perfecto: justo hoy que olvidé el paraguas, decide llover.", "Perfect: on the very day I forgot my umbrella, it decides to rain.", "Tuyệt thật: đúng hôm tôi quên ô thì trời lại quyết định mưa.", "justo hoy que", "ironic evaluation + marked timing", "tuyệt thật + đúng hôm... thì lại", [c("Perfecto", "perfect", "Tuyệt thật", "expresses an evaluation made ironic by context"), c("justo hoy que", "on the very day that", "đúng hôm", "emphasizes unfortunate timing"), c("olvidé el paraguas", "I forgot the umbrella", "tôi quên ô", "states the relevant circumstance"), c("decide llover", "it decides to rain", "thì trời lại quyết định mưa", "personifies the weather for comic effect")]),
    l("Explaining wordplay", "linguistic humor", "El juego de palabras depende de que ambos términos suenen igual, aunque signifiquen cosas distintas.", "The wordplay depends on both terms sounding the same although they mean different things.", "Lối chơi chữ dựa vào việc hai từ nghe giống nhau dù mang nghĩa khác nhau.", "depende de que", "dependency + subjunctive + concession", "dựa vào việc + dù", [c("El juego de palabras", "the wordplay", "Lối chơi chữ", "names the humorous device"), c("depende de que", "depends on", "dựa vào việc", "introduces its mechanism"), c("ambos términos suenen igual", "both terms sound the same", "hai từ nghe giống nhau", "states the formal similarity"), c("aunque signifiquen cosas distintas", "although they mean different things", "dù mang nghĩa khác nhau", "states the semantic contrast")]),
  ]],
  [41, "Emotion with precision", [
    l("Mixed feelings", "qualified emotion", "Me alegra que hayas aceptado, aunque me preocupa que asumas demasiado.", "I am glad you accepted, although I worry that you are taking on too much.", "Tôi vui vì bạn đã nhận lời, mặc dù lo rằng bạn đang gánh quá nhiều.", "Me alegra que", "emotion + perfect subjunctive + concessive concern", "vui vì + đã + mặc dù lo rằng", [c("Me alegra que hayas aceptado", "I am glad you accepted", "Tôi vui vì bạn đã nhận lời", "expresses positive feeling about a completed choice"), c("aunque", "although", "mặc dù", "introduces a simultaneous reservation"), c("me preocupa que", "it worries me that", "lo rằng", "frames the concern"), c("asumas demasiado", "you are taking on too much", "bạn đang gánh quá nhiều", "names its cause")]),
    l("A clear boundary", "firm but relational limit", "Entiendo tu urgencia, pero no puedo comprometerme sin revisar primero las condiciones.", "I understand your urgency, but I cannot commit without first reviewing the conditions.", "Tôi hiểu sự khẩn cấp của bạn, nhưng không thể cam kết khi chưa xem xét các điều kiện trước.", "no puedo comprometerme", "acknowledgment + negated pronominal commitment", "hiểu... nhưng không thể + khi chưa", [c("Entiendo tu urgencia", "I understand your urgency", "Tôi hiểu sự khẩn cấp của bạn", "acknowledges the other person's situation"), c("pero", "but", "nhưng", "marks the boundary"), c("no puedo comprometerme", "I cannot commit", "không thể cam kết", "states the limit"), c("sin revisar primero las condiciones", "without first reviewing the conditions", "khi chưa xem xét các điều kiện trước", "gives the unmet prerequisite")]),
    l("Regret and learning", "counterfactual reflection", "Ojalá hubiera expresado antes lo que necesitaba en lugar de guardar silencio.", "I wish I had expressed what I needed earlier instead of remaining silent.", "Giá như tôi đã nói sớm điều mình cần thay vì im lặng.", "Ojalá hubiera expresado", "counterfactual wish + pluperfect subjunctive", "giá như + đã + thay vì", [c("Ojalá hubiera expresado", "I wish I had expressed", "Giá như tôi đã nói", "marks regret about an unreal past alternative"), c("antes", "earlier", "sớm", "locates the missed action"), c("lo que necesitaba", "what I needed", "điều mình cần", "names the unexpressed need"), c("en lugar de guardar silencio", "instead of remaining silent", "thay vì im lặng", "contrasts the action actually taken")]),
    l("Relational nuance", "care without control", "Quiero apoyarte sin que sientas que intento decidir por ti.", "I want to support you without making you feel that I am trying to decide for you.", "Tôi muốn hỗ trợ bạn mà không khiến bạn cảm thấy tôi đang quyết định thay bạn.", "sin que sientas", "intention + sin que + subjunctive", "muốn + mà không khiến + cảm thấy", [c("Quiero apoyarte", "I want to support you", "Tôi muốn hỗ trợ bạn", "states the caring intention"), c("sin que sientas", "without you feeling", "mà không khiến bạn cảm thấy", "excludes an unwanted emotional effect"), c("que intento decidir", "that I am trying to decide", "tôi đang quyết định", "states the possible interpretation"), c("por ti", "for you; in your place", "thay bạn", "marks the agency that must remain yours")]),
  ]],
  [42, "Ideas and interpretation", [
    l("Defining an idea", "conceptual explanation", "La autonomía no consiste en actuar sin límites, sino en elegir con responsabilidad.", "Autonomy does not consist of acting without limits, but of choosing responsibly.", "Tự chủ không phải là hành động không giới hạn mà là lựa chọn có trách nhiệm.", "no consiste en... sino en", "corrective definition + parallel infinitives", "không phải là... mà là", [c("La autonomía no consiste en", "autonomy does not consist of", "Tự chủ không phải là", "rejects an inadequate definition"), c("actuar sin límites", "acting without limits", "hành động không giới hạn", "states the rejected meaning"), c("sino en", "but rather in", "mà là", "introduces the corrected definition"), c("elegir con responsabilidad", "choosing responsibly", "lựa chọn có trách nhiệm", "states the intended meaning")]),
    l("Interpreting a text", "evidence-based reading", "El autor sugiere, sin afirmarlo directamente, que el progreso también implica pérdidas.", "The author suggests, without stating it directly, that progress also entails losses.", "Tác giả ngụ ý, dù không nói thẳng, rằng tiến bộ cũng đi kèm mất mát.", "sin afirmarlo", "reporting verb + detached qualification + noun clause", "ngụ ý + dù không nói thẳng + rằng", [c("El autor sugiere", "the author suggests", "Tác giả ngụ ý", "attributes an implicit interpretation"), c("sin afirmarlo directamente", "without stating it directly", "dù không nói thẳng", "qualifies the claim as unstated"), c("que el progreso también implica", "that progress also entails", "rằng tiến bộ cũng đi kèm", "introduces the interpreted proposition"), c("pérdidas", "losses", "mất mát", "names its difficult consequence")]),
    l("Connecting concepts", "causal interpretation", "La confianza se construye cuando las palabras coinciden de manera constante con los actos.", "Trust is built when words consistently match actions.", "Niềm tin được xây dựng khi lời nói nhất quán với hành động.", "se construye", "passive se + temporal condition", "được xây dựng + khi", [c("La confianza se construye", "trust is built", "Niềm tin được xây dựng", "presents trust as a developing result"), c("cuando", "when", "khi", "introduces the enabling condition"), c("las palabras coinciden", "words match", "lời nói nhất quán", "states the alignment"), c("de manera constante con los actos", "consistently with actions", "với hành động", "identifies the comparison and its continuity")]),
    l("Mediating complexity", "accessible synthesis", "En términos sencillos, el sistema premia las decisiones cuyos beneficios aparecen pronto.", "In simple terms, the system rewards decisions whose benefits appear quickly.", "Nói đơn giản, hệ thống ưu tiên những quyết định mang lại lợi ích sớm.", "cuyos beneficios", "reformulation + possessive relative clause", "nói đơn giản + những... mang lại", [c("En términos sencillos", "in simple terms", "Nói đơn giản", "signals an accessible reformulation"), c("el sistema premia", "the system rewards", "hệ thống ưu tiên", "states the central mechanism"), c("las decisiones cuyos beneficios", "decisions whose benefits", "những quyết định mang lại lợi ích", "links decisions to their outcomes"), c("aparecen pronto", "appear quickly", "sớm", "identifies the favored timing")]),
  ]],
  [43, "Spontaneous interaction", [
    l("Holding the floor", "turn management", "Déjame terminar la idea y enseguida escucho tu objeción.", "Let me finish the idea, and I will listen to your objection right away.", "Hãy để tôi nói hết ý rồi tôi sẽ nghe phản đối của bạn ngay.", "Déjame", "affirmative command + clitic + immediate future", "hãy để + rồi sẽ", [c("Déjame terminar", "let me finish", "Hãy để tôi nói hết", "claims a brief turn without rejecting the other speaker"), c("la idea", "the idea", "ý", "names what needs completion"), c("y enseguida escucho", "and I will listen right away", "rồi tôi sẽ nghe ngay", "promises an immediate handoff"), c("tu objeción", "your objection", "phản đối của bạn", "acknowledges the other contribution")]),
    l("Self-correcting", "subtle repair", "Mejor dicho, no fue una decisión equivocada, sino una decisión tomada demasiado pronto.", "More precisely, it was not a wrong decision, but a decision made too early.", "Nói chính xác hơn, đó không phải quyết định sai mà là quyết định được đưa ra quá sớm.", "Mejor dicho", "repair marker + corrective contrast + participle", "nói chính xác hơn + không phải... mà là", [c("Mejor dicho", "more precisely", "Nói chính xác hơn", "signals self-correction"), c("no fue una decisión equivocada", "it was not a wrong decision", "đó không phải quyết định sai", "withdraws the first characterization"), c("sino una decisión", "but a decision", "mà là quyết định", "introduces the refined description"), c("tomada demasiado pronto", "made too early", "được đưa ra quá sớm", "states the actual problem")]),
    l("Adapting register", "informal-to-formal shift", "Si le parece, podríamos retomar este punto una vez revisada la documentación.", "If that suits you, we could return to this point once the documentation has been reviewed.", "Nếu ông bà thấy phù hợp, chúng ta có thể quay lại điểm này sau khi xem xét tài liệu.", "Si le parece", "formal address + conditional proposal + detached participle", "nếu thấy phù hợp + có thể + sau khi", [c("Si le parece", "if that suits you", "Nếu ông bà thấy phù hợp", "opens a deferential proposal"), c("podríamos retomar", "we could return to", "chúng ta có thể quay lại", "softens the proposed action"), c("este punto", "this point", "điểm này", "identifies the topic"), c("una vez revisada la documentación", "once the documentation is reviewed", "sau khi xem xét tài liệu", "sets the prerequisite")]),
    l("Repairing misunderstanding", "interactive clarification", "Creo que estamos usando la misma palabra con sentidos diferentes.", "I think we are using the same word with different meanings.", "Tôi nghĩ chúng ta đang dùng cùng một từ theo những nghĩa khác nhau.", "estamos usando", "stance + progressive + contrastive complement", "nghĩ + đang dùng + theo nghĩa", [c("Creo que", "I think that", "Tôi nghĩ", "offers a non-accusatory diagnosis"), c("estamos usando", "we are using", "chúng ta đang dùng", "frames the shared ongoing behavior"), c("la misma palabra", "the same word", "cùng một từ", "identifies the surface agreement"), c("con sentidos diferentes", "with different meanings", "theo những nghĩa khác nhau", "locates the semantic mismatch")]),
  ]],
  [44, "Ethics and responsibility", [
    l("Competing duties", "ethical trade-off", "Ayudar en una emergencia puede justificar romper una regla, pero no ignorar sus consecuencias.", "Helping in an emergency may justify breaking a rule, but not ignoring its consequences.", "Giúp đỡ trong tình huống khẩn cấp có thể biện minh cho việc phá lệ, nhưng không thể bỏ qua hậu quả.", "puede justificar", "infinitive subject + modal justification + contrast", "có thể biện minh + nhưng không thể", [c("Ayudar en una emergencia", "helping in an emergency", "Giúp đỡ trong tình huống khẩn cấp", "names the ethically relevant action"), c("puede justificar", "may justify", "có thể biện minh cho", "marks a limited moral permission"), c("romper una regla", "breaking a rule", "việc phá lệ", "names what may be permitted"), c("pero no ignorar sus consecuencias", "but not ignoring its consequences", "nhưng không thể bỏ qua hậu quả", "preserves accountability")]),
    l("Qualified judgment", "moral evaluation", "No basta con que una decisión sea legal; también debería ser justa.", "It is not enough for a decision to be legal; it should also be fair.", "Một quyết định hợp pháp thôi chưa đủ; nó còn phải công bằng.", "No basta con que", "insufficiency + subjunctive + modal recommendation", "thôi chưa đủ + còn phải", [c("No basta con que", "it is not enough that", "thôi chưa đủ", "rejects a single criterion as sufficient"), c("una decisión sea legal", "a decision be legal", "Một quyết định hợp pháp", "states that criterion"), c("también debería ser", "it should also be", "nó còn phải", "adds a normative requirement"), c("justa", "fair", "công bằng", "names the required quality")]),
    l("Responsibility for impact", "intention versus consequence", "Aunque no hubiera mala intención, quien causó el daño tiene la responsabilidad de repararlo.", "Even if there was no bad intention, whoever caused the harm has a responsibility to repair it.", "Dù không có ý xấu, người gây ra thiệt hại vẫn có trách nhiệm khắc phục.", "Aunque no hubiera", "concessive imperfect subjunctive + free relative", "dù không có + người + vẫn", [c("Aunque no hubiera mala intención", "even if there was no bad intention", "Dù không có ý xấu", "concedes the absence of intent"), c("quien causó el daño", "whoever caused the harm", "người gây ra thiệt hại", "identifies responsibility by action"), c("tiene la responsabilidad", "has the responsibility", "vẫn có trách nhiệm", "states the obligation"), c("de repararlo", "to repair it", "khắc phục", "names the restorative action")]),
    l("A principled challenge", "ethical disagreement", "Me cuesta aceptar una solución que protege la eficiencia a costa de las personas.", "I find it difficult to accept a solution that protects efficiency at people's expense.", "Tôi khó chấp nhận một giải pháp bảo vệ hiệu quả nhưng gây thiệt hại cho con người.", "a costa de", "evaluative difficulty + relative clause + idiom", "khó chấp nhận + nhưng gây thiệt hại", [c("Me cuesta aceptar", "I find it difficult to accept", "Tôi khó chấp nhận", "frames principled resistance"), c("una solución que protege", "a solution that protects", "một giải pháp bảo vệ", "introduces the criticized trade-off"), c("la eficiencia", "efficiency", "hiệu quả", "names the protected value"), c("a costa de las personas", "at people's expense", "nhưng gây thiệt hại cho con người", "names who bears the cost")]),
  ]],
  [45, "Systems and society", [
    l("Explaining incentives", "systemic causation", "Cuando se premia únicamente la velocidad, se tiende a descuidar la calidad.", "When only speed is rewarded, quality tends to be neglected.", "Khi chỉ tốc độ được khen thưởng, chất lượng thường bị xem nhẹ.", "se tiende a", "impersonal passive + tendency", "khi + được + thường bị", [c("Cuando se premia", "when it is rewarded", "Khi được khen thưởng", "introduces the institutional incentive"), c("únicamente la velocidad", "only speed", "chỉ tốc độ", "names the narrowly rewarded value"), c("se tiende a descuidar", "there is a tendency to neglect", "thường bị xem nhẹ", "states the systemic tendency"), c("la calidad", "quality", "chất lượng", "names what loses attention")]),
    l("Unequal effects", "distributional analysis", "La misma política puede beneficiar a un grupo y perjudicar a otro.", "The same policy can benefit one group and harm another.", "Cùng một chính sách có thể có lợi cho nhóm này nhưng gây hại cho nhóm khác.", "beneficiar... perjudicar", "modal + coordinated opposing effects", "có thể + có lợi... nhưng gây hại", [c("La misma política", "the same policy", "Cùng một chính sách", "holds the cause constant"), c("puede beneficiar", "can benefit", "có thể có lợi cho", "states one possible effect"), c("a un grupo", "one group", "nhóm này", "identifies the beneficiary"), c("y perjudicar a otro", "and harm another", "nhưng gây hại cho nhóm khác", "contrasts the burdened group")]),
    l("Institutional feedback", "recursive system effect", "Cuanto menos confía la gente en la institución, más difícil resulta aplicar sus decisiones.", "The less people trust the institution, the harder it becomes to implement its decisions.", "Người dân càng ít tin vào thể chế thì việc thực hiện quyết định của nó càng khó.", "Cuanto menos... más", "correlative comparison", "càng ít... thì càng", [c("Cuanto menos confía la gente", "the less people trust", "Người dân càng ít tin", "states the changing public attitude"), c("en la institución", "in the institution", "vào thể chế", "identifies the object of trust"), c("más difícil resulta", "the harder it becomes", "thì càng khó", "states the linked consequence"), c("aplicar sus decisiones", "to implement its decisions", "việc thực hiện quyết định của nó", "names the affected institutional action")]),
    l("Structural reform", "institutional change", "Para que la reforma sea duradera, deben cambiar tanto las normas como los incentivos.", "For the reform to last, both the rules and the incentives must change.", "Để cải cách bền vững, cả quy định lẫn động lực đều phải thay đổi.", "Para que", "purpose + subjunctive + tanto...como", "để + cả... lẫn... đều phải", [c("Para que la reforma sea duradera", "for the reform to last", "Để cải cách bền vững", "states the intended long-term result"), c("deben cambiar", "must change", "đều phải thay đổi", "marks necessity"), c("tanto las normas", "both the rules", "cả quy định", "names the first system component"), c("como los incentivos", "and the incentives", "lẫn động lực", "adds the equally necessary component")]),
  ]],
  [46, "Science and technology", [
    l("Calibrating certainty", "scientific probability", "Es muy probable que el tratamiento reduzca los síntomas, aunque no funcione igual para todos.", "The treatment is very likely to reduce symptoms, although it may not work equally for everyone.", "Phương pháp điều trị rất có khả năng làm giảm triệu chứng, dù có thể không hiệu quả như nhau với mọi người.", "Es muy probable que", "high probability + subjunctive + concession", "rất có khả năng + dù có thể", [c("Es muy probable que", "it is very likely that", "rất có khả năng", "calibrates a strong but non-absolute claim"), c("el tratamiento reduzca los síntomas", "the treatment reduces symptoms", "phương pháp điều trị làm giảm triệu chứng", "states the expected effect"), c("aunque no funcione igual", "although it may not work equally", "dù có thể không hiệu quả như nhau", "qualifies variation in response"), c("para todos", "for everyone", "với mọi người", "sets the affected population")]),
    l("Explaining evidence", "method and result", "El estudio comparó dos grupos para determinar si la diferencia era significativa.", "The study compared two groups to determine whether the difference was significant.", "Nghiên cứu so sánh hai nhóm để xác định liệu sự khác biệt có đáng kể hay không.", "para determinar si", "preterite method + purpose + embedded question", "để xác định liệu... hay không", [c("El estudio comparó", "the study compared", "Nghiên cứu so sánh", "states the research method"), c("dos grupos", "two groups", "hai nhóm", "identifies the comparison"), c("para determinar si", "to determine whether", "để xác định liệu", "states the analytic purpose"), c("la diferencia era significativa", "the difference was significant", "sự khác biệt có đáng kể hay không", "names the tested question")]),
    l("Projecting consequences", "future inference", "Dentro de unos años, muchas tareas rutinarias se habrán automatizado.", "Within a few years, many routine tasks will have been automated.", "Trong vài năm tới, nhiều công việc thường ngày sẽ được tự động hóa.", "se habrán automatizado", "future perfect reflexive-passive", "sẽ được + time frame", [c("Dentro de unos años", "within a few years", "Trong vài năm tới", "sets the future horizon"), c("muchas tareas rutinarias", "many routine tasks", "nhiều công việc thường ngày", "names the affected work"), c("se habrán automatizado", "will have been automated", "sẽ được tự động hóa", "projects completion before that horizon"), c("future consequence", "a projected structural change", "thay đổi dự kiến", "marks this as projection rather than present fact")]),
    l("Responsible uncertainty", "technical limitation", "Los resultados son prometedores, pero aún no permiten afirmar que la tecnología sea segura a largo plazo.", "The results are promising, but they do not yet allow us to state that the technology is safe in the long term.", "Kết quả đầy hứa hẹn, nhưng vẫn chưa đủ để khẳng định công nghệ an toàn về lâu dài.", "no permiten afirmar", "contrast + evidential limit + subjunctive claim", "nhưng vẫn chưa đủ để khẳng định", [c("Los resultados son prometedores", "the results are promising", "Kết quả đầy hứa hẹn", "acknowledges positive evidence"), c("pero aún no permiten", "but do not yet allow", "nhưng vẫn chưa đủ", "sets the evidential limit"), c("afirmar que la tecnología sea segura", "to state that the technology is safe", "để khẳng định công nghệ an toàn", "names the unsupported conclusion"), c("a largo plazo", "in the long term", "về lâu dài", "defines the unresolved time scale")]),
  ]],
  [47, "Register and diplomacy", [
    l("Mitigated disagreement", "diplomatic challenge", "Comprendo el planteamiento, pero quizá convendría examinar también sus efectos indirectos.", "I understand the approach, but perhaps it would be advisable to examine its indirect effects as well.", "Tôi hiểu cách tiếp cận, nhưng có lẽ cũng nên xem xét các tác động gián tiếp.", "quizá convendría", "acknowledgment + conditional mitigation", "hiểu... nhưng có lẽ cũng nên", [c("Comprendo el planteamiento", "I understand the approach", "Tôi hiểu cách tiếp cận", "acknowledges the proposal"), c("pero quizá", "but perhaps", "nhưng có lẽ", "softens the disagreement"), c("convendría examinar también", "it would be advisable to examine as well", "cũng nên xem xét", "offers the alternative action"), c("sus efectos indirectos", "its indirect effects", "các tác động gián tiếp", "names the overlooked issue")]),
    l("Preserving face", "respectful refusal", "Agradezco la confianza; sin embargo, no estaría en condiciones de asumir esa responsabilidad ahora.", "I appreciate the trust; however, I would not be in a position to assume that responsibility now.", "Tôi trân trọng sự tin tưởng; tuy nhiên, hiện tại tôi chưa thể nhận trách nhiệm đó.", "no estaría en condiciones", "appreciation + formal contrast + conditional limitation", "trân trọng + tuy nhiên + chưa thể", [c("Agradezco la confianza", "I appreciate the trust", "Tôi trân trọng sự tin tưởng", "recognizes the positive intention"), c("sin embargo", "however", "tuy nhiên", "marks the refusal formally"), c("no estaría en condiciones", "I would not be in a position", "hiện tại tôi chưa thể", "states inability without blunt rejection"), c("de asumir esa responsabilidad ahora", "to assume that responsibility now", "nhận trách nhiệm đó", "defines the declined commitment")]),
    l("Negotiating wording", "collaborative reformulation", "¿Le parecería aceptable sustituir 'obligatorio' por 'recomendado' en este apartado?", "Would you find it acceptable to replace 'mandatory' with 'recommended' in this section?", "Ông bà có thấy chấp nhận được nếu thay 'bắt buộc' bằng 'khuyến nghị' trong phần này không?", "¿Le parecería aceptable...?", "formal conditional question + infinitive substitution", "có thấy chấp nhận được nếu thay... bằng... không", [c("¿Le parecería aceptable", "would you find it acceptable", "Ông bà có thấy chấp nhận được", "opens a deferential negotiation"), c("sustituir 'obligatorio'", "to replace 'mandatory'", "nếu thay 'bắt buộc'", "names the source wording"), c("por 'recomendado'", "with 'recommended'", "bằng 'khuyến nghị'", "names the proposed wording"), c("en este apartado?", "in this section", "trong phần này không?", "locates the change and closes the question")]),
    l("Conditional compromise", "formal negotiated condition", "Podríamos aceptar el plazo propuesto, siempre y cuando se revisen las prioridades.", "We could accept the proposed deadline, provided that the priorities are reviewed.", "Chúng tôi có thể chấp nhận thời hạn đề xuất với điều kiện các ưu tiên được xem xét lại.", "siempre y cuando", "conditional compromise + passive subjunctive", "có thể chấp nhận + với điều kiện + được", [c("Podríamos aceptar", "we could accept", "Chúng tôi có thể chấp nhận", "states conditional willingness"), c("el plazo propuesto", "the proposed deadline", "thời hạn đề xuất", "names the negotiable term"), c("siempre y cuando", "provided that", "với điều kiện", "introduces the condition"), c("se revisen las prioridades", "the priorities are reviewed", "các ưu tiên được xem xét lại", "states the required adjustment")]),
  ]],
  [48, "B2 integration", [
    l("Integrated analysis", "evidence and qualification", "A la luz de los datos, la estrategia parece eficaz, aunque sería prematuro considerarla definitiva.", "In light of the data, the strategy appears effective, although it would be premature to consider it definitive.", "Xét theo dữ liệu, chiến lược có vẻ hiệu quả, dù còn quá sớm để coi đó là kết luận cuối cùng.", "sería prematuro", "evidential frame + concession + conditional evaluation", "xét theo + có vẻ + dù còn quá sớm", [c("A la luz de los datos", "in light of the data", "Xét theo dữ liệu", "grounds the evaluation"), c("la estrategia parece eficaz", "the strategy appears effective", "chiến lược có vẻ hiệu quả", "states the supported interpretation"), c("aunque sería prematuro", "although it would be premature", "dù còn quá sớm", "limits confidence"), c("considerarla definitiva", "to consider it definitive", "để coi đó là kết luận cuối cùng", "names the overstrong conclusion")]),
    l("Integrated negotiation", "nuanced proposal", "Estoy dispuesto a apoyar el cambio, con tal de que acordemos cómo evaluar sus resultados.", "I am willing to support the change, provided that we agree on how to evaluate its results.", "Tôi sẵn sàng ủng hộ thay đổi với điều kiện chúng ta thống nhất cách đánh giá kết quả.", "con tal de que", "willingness + condition + subjunctive", "sẵn sàng + với điều kiện + thống nhất", [c("Estoy dispuesto a apoyar", "I am willing to support", "Tôi sẵn sàng ủng hộ", "states constructive willingness"), c("el cambio", "the change", "thay đổi", "names the proposal"), c("con tal de que acordemos", "provided that we agree", "với điều kiện chúng ta thống nhất", "introduces the negotiated condition"), c("cómo evaluar sus resultados", "how to evaluate its results", "cách đánh giá kết quả", "names the required accountability")]),
    l("Integrated mediation", "reframing conflict", "Ambas partes buscan estabilidad, pero entienden de manera distinta qué condiciones la garantizan.", "Both sides seek stability, but they understand differently which conditions guarantee it.", "Cả hai bên đều muốn ổn định, nhưng hiểu khác nhau về những điều kiện bảo đảm điều đó.", "qué condiciones la garantizan", "shared premise + contrast + embedded question", "cả hai đều + nhưng hiểu khác nhau", [c("Ambas partes buscan estabilidad", "both sides seek stability", "Cả hai bên đều muốn ổn định", "identifies shared purpose"), c("pero entienden de manera distinta", "but understand differently", "nhưng hiểu khác nhau", "locates the disagreement in interpretation"), c("qué condiciones", "which conditions", "về những điều kiện", "opens the disputed question"), c("la garantizan", "guarantee it", "bảo đảm điều đó", "links conditions to the shared goal")]),
    l("B2 reflection", "independent nuanced expression", "Ya puedo defender una posición con matices y adaptar el registro según la situación.", "I can now defend a nuanced position and adapt my register to the situation.", "Giờ đây tôi có thể bảo vệ quan điểm có sắc thái và điều chỉnh cách diễn đạt theo tình huống.", "según la situación", "present ability + coordinated infinitives + contextual standard", "giờ đây có thể + và + theo tình huống", [c("Ya puedo defender", "I can now defend", "Giờ đây tôi có thể bảo vệ", "states developed independent ability"), c("una posición con matices", "a nuanced position", "quan điểm có sắc thái", "names the level of argument"), c("y adaptar el registro", "and adapt register", "và điều chỉnh cách diễn đạt", "adds pragmatic flexibility"), c("según la situación", "according to the situation", "theo tình huống", "sets the contextual standard")]),
  ]],
];

let previous = "b1-u36-4-b1-reflection";
const lessons = [];
for (const [unitNumber, unitTitle, items] of groups) {
  for (const [index, item] of items.entries()) {
    const [title, skill, spanish, english, vietnamese, focus, pattern, bridgePattern, units] = item;
    const slug = title.toLocaleLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
    const objectiveId = `b2-u${unitNumber}-${index + 1}-${slug}`;
    lessons.push({
      id: `${objectiveId}-lesson`, objectiveId, prerequisites: [previous], unit: unitNumber, lesson: index + 1,
      unitTitle, title, skill, spanish, english, vietnamese, focus, pattern, bridgePattern,
      units: units.map((entry) => ({ ...entry, part: "Contextual phrase",
        spanishForm: `The Spanish scope “${entry.spanish}” functions as an authored unit in ${pattern}; its mood, tense, agreement, and governed links are interpreted from this exact sentence.`,
        vietnameseForm: `The Vietnamese scope “${entry.vietnamese}” functions analytically in ${bridgePattern}; order, particles, and aspect or stance markers carry the relationship without Spanish-style conjugation.` })),
    });
    previous = objectiveId;
  }
}

export default { id: "b2-core-1", version: 1, level: "B2", lessons };
