const s = (spanish, meaning, vietnamese, role) => ({ spanish, meaning, vietnamese, role });
const q = (title, spanish, english, vietnamese, focus, units) => ({ title, spanish, english, vietnamese, focus, units });

const groups = [
  [49, "Implicit meaning", [
    q("What was left unsaid", "No dijo que estuviera en contra, pero su silencio resultó bastante elocuente.", "She did not say she was opposed, but her silence was quite telling.", "Cô ấy không nói rằng mình phản đối, nhưng sự im lặng lại nói lên rất nhiều.", "unstated attitude", [s("No dijo que estuviera en contra", "she did not say she was opposed", "Cô ấy không nói rằng mình phản đối", "denies an explicit statement"), s("pero su silencio", "but her silence", "nhưng sự im lặng", "contrasts words with behavior"), s("resultó bastante elocuente", "proved quite telling", "lại nói lên rất nhiều", "invites an inference from what was omitted")]),
    q("Reading a reservation", "Que aceptara tan deprisa no significa necesariamente que estuviera convencido.", "His accepting so quickly does not necessarily mean that he was convinced.", "Việc anh ấy đồng ý quá nhanh không nhất thiết có nghĩa là anh ấy đã bị thuyết phục.", "inference with restraint", [s("Que aceptara tan deprisa", "his accepting so quickly", "Việc anh ấy đồng ý quá nhanh", "turns an observed action into the topic"), s("no significa necesariamente", "does not necessarily mean", "không nhất thiết có nghĩa là", "blocks an automatic inference"), s("que estuviera convencido", "that he was convinced", "anh ấy đã bị thuyết phục", "names the uncertain interpretation")]),
    q("Calibrating a hint", "Al decir que 'ya lo pensaríamos', dejó entrever que la propuesta no le entusiasmaba.", "By saying that 'we would think about it,' she hinted that the proposal did not excite her.", "Khi nói rằng 'chúng ta sẽ suy nghĩ thêm', cô ấy ngầm cho thấy mình không hào hứng với đề xuất.", "indirect stance", [s("Al decir que 'ya lo pensaríamos'", "by saying 'we would think about it'", "Khi nói rằng 'chúng ta sẽ suy nghĩ thêm'", "quotes the surface response"), s("dejó entrever que", "she hinted that", "cô ấy ngầm cho thấy", "marks an inferred attitude"), s("la propuesta no le entusiasmaba", "the proposal did not excite her", "mình không hào hứng với đề xuất", "states the implied position")]),
    q("Interpersonal positioning", "La forma en que formuló la pregunta daba a entender que esperaba una respuesta concreta.", "The way he phrased the question suggested that he expected a particular answer.", "Cách anh ấy đặt câu hỏi cho thấy anh ấy mong đợi một câu trả lời cụ thể.", "form implies expectation", [s("La forma en que formuló la pregunta", "the way he phrased the question", "Cách anh ấy đặt câu hỏi", "makes wording the evidence"), s("daba a entender que", "suggested that", "cho thấy", "introduces the pragmatic inference"), s("esperaba una respuesta concreta", "he expected a particular answer", "anh ấy mong đợi một câu trả lời cụ thể", "names the inferred expectation")]),
  ]],
  [50, "Register and voice", [
    q("Institutional voice", "Se ruega a las personas asistentes que mantengan apagados sus dispositivos.", "Attendees are requested to keep their devices switched off.", "Kính đề nghị người tham dự tắt các thiết bị của mình.", "formal impersonal request", [s("Se ruega", "attendees are requested", "Kính đề nghị", "creates a formal institutional request"), s("a las personas asistentes", "the attendees", "người tham dự", "identifies the addressees impersonally"), s("que mantengan apagados sus dispositivos", "to keep their devices switched off", "tắt các thiết bị của mình", "states the expected conduct")]),
    q("Intimate voice", "No hace falta que me expliques todo; con saber que estás bien me basta.", "You do not need to explain everything; knowing that you are well is enough for me.", "Bạn không cần giải thích mọi chuyện; chỉ cần biết bạn ổn là đủ với tôi.", "intimate reassurance", [s("No hace falta que me expliques todo", "you do not need to explain everything", "Bạn không cần giải thích mọi chuyện", "removes pressure in a close relationship"), s("con saber que estás bien", "knowing that you are well", "chỉ cần biết bạn ổn", "names the limited reassurance needed"), s("me basta", "is enough for me", "là đủ với tôi", "closes with personal sufficiency")]),
    q("Neutral professional voice", "Te envío el borrador para que puedas revisarlo cuando te resulte conveniente.", "I am sending you the draft so that you can review it when convenient.", "Tôi gửi bạn bản nháp để bạn có thể xem lại khi thuận tiện.", "neutral professional courtesy", [s("Te envío el borrador", "I am sending you the draft", "Tôi gửi bạn bản nháp", "states the practical action"), s("para que puedas revisarlo", "so that you can review it", "để bạn có thể xem lại", "states its purpose without pressure"), s("cuando te resulte conveniente", "when convenient for you", "khi thuận tiện", "leaves timing with the recipient")]),
    q("Shifting voice", "Entre amigos lo diría sin rodeos; en este contexto, conviene formularlo con más cautela.", "Among friends I would say it directly; in this context, it is better to phrase it more cautiously.", "Với bạn bè tôi sẽ nói thẳng; trong hoàn cảnh này, nên diễn đạt thận trọng hơn.", "register adaptation", [s("Entre amigos lo diría sin rodeos", "among friends I would say it directly", "Với bạn bè tôi sẽ nói thẳng", "models intimate directness"), s("en este contexto", "in this context", "trong hoàn cảnh này", "changes the social frame"), s("conviene formularlo con más cautela", "it is better to phrase it more cautiously", "nên diễn đạt thận trọng hơn", "adapts wording to that frame")]),
  ]],
  [51, "Extended argument", [
    q("Establishing a thesis", "Sostengo que la medida es necesaria no porque sea perfecta, sino porque evita un daño mayor.", "I maintain that the measure is necessary not because it is perfect, but because it prevents greater harm.", "Tôi cho rằng biện pháp này cần thiết không phải vì nó hoàn hảo mà vì nó ngăn được thiệt hại lớn hơn.", "qualified thesis", [s("Sostengo que la medida es necesaria", "I maintain that the measure is necessary", "Tôi cho rằng biện pháp này cần thiết", "states the thesis"), s("no porque sea perfecta", "not because it is perfect", "không phải vì nó hoàn hảo", "rejects an overstated basis"), s("sino porque evita un daño mayor", "but because it prevents greater harm", "mà vì nó ngăn được thiệt hại lớn hơn", "supplies the actual justification")]),
    q("Developing the reasoning", "Si se consideran tanto los costos inmediatos como los beneficios futuros, la inversión resulta razonable.", "If both immediate costs and future benefits are considered, the investment proves reasonable.", "Nếu xem xét cả chi phí trước mắt lẫn lợi ích tương lai, khoản đầu tư trở nên hợp lý.", "balanced evaluation", [s("Si se consideran", "if they are considered", "Nếu xem xét", "opens the evaluative condition"), s("tanto los costos inmediatos como los beneficios futuros", "both immediate costs and future benefits", "cả chi phí trước mắt lẫn lợi ích tương lai", "sets a balanced evidence base"), s("la inversión resulta razonable", "the investment proves reasonable", "khoản đầu tư trở nên hợp lý", "states the resulting judgment")]),
    q("Answering a counterargument", "Se podría objetar que el cambio genera incertidumbre; aun así, mantener el sistema actual también entraña riesgos.", "One might object that the change creates uncertainty; even so, keeping the current system also entails risks.", "Có thể phản đối rằng thay đổi tạo ra bất ổn; tuy vậy, giữ nguyên hệ thống hiện tại cũng tiềm ẩn rủi ro.", "counterargument response", [s("Se podría objetar que", "one might object that", "Có thể phản đối rằng", "presents the counterargument fairly"), s("el cambio genera incertidumbre", "the change creates uncertainty", "thay đổi tạo ra bất ổn", "states its concern"), s("aun así, mantener el sistema actual también entraña riesgos", "even so, keeping the current system also entails risks", "tuy vậy, giữ nguyên hệ thống hiện tại cũng tiềm ẩn rủi ro", "answers by restoring the comparison")]),
    q("Drawing a conclusion", "Por consiguiente, la cuestión no es si debemos actuar, sino cómo hacerlo sin perder de vista la equidad.", "Consequently, the question is not whether we should act, but how to do so without losing sight of fairness.", "Vì thế, vấn đề không phải là có nên hành động hay không mà là làm thế nào để không quên tính công bằng.", "rhetorical conclusion", [s("Por consiguiente", "consequently", "Vì thế", "signals the derived conclusion"), s("la cuestión no es si debemos actuar", "the question is not whether we should act", "vấn đề không phải là có nên hành động hay không", "closes one debate"), s("sino cómo hacerlo sin perder de vista la equidad", "but how to do so without losing sight of fairness", "mà là làm thế nào để không quên tính công bằng", "reframes the remaining question")]),
  ]],
  [52, "Professional leadership", [
    q("Opening deliberation", "Antes de decidir, me gustaría que distinguiéramos entre lo urgente y lo verdaderamente importante.", "Before deciding, I would like us to distinguish between what is urgent and what is truly important.", "Trước khi quyết định, tôi muốn chúng ta phân biệt điều cấp bách với điều thực sự quan trọng.", "facilitating priorities", [s("Antes de decidir", "before deciding", "Trước khi quyết định", "slows premature commitment"), s("me gustaría que distinguiéramos", "I would like us to distinguish", "tôi muốn chúng ta phân biệt", "invites collective analysis"), s("entre lo urgente y lo verdaderamente importante", "between the urgent and the truly important", "điều cấp bách với điều thực sự quan trọng", "defines the distinction")]),
    q("Reframing conflict", "No estamos discutiendo sobre el objetivo, sino sobre el grado de riesgo que estamos dispuestos a asumir.", "We are not arguing about the objective, but about the degree of risk we are willing to assume.", "Chúng ta không tranh luận về mục tiêu mà về mức độ rủi ro sẵn sàng chấp nhận.", "strategic reframing", [s("No estamos discutiendo sobre el objetivo", "we are not arguing about the objective", "Chúng ta không tranh luận về mục tiêu", "identifies shared ground"), s("sino sobre el grado de riesgo", "but about the degree of risk", "mà về mức độ rủi ro", "relocates the disagreement"), s("que estamos dispuestos a asumir", "we are willing to assume", "sẵn sàng chấp nhận", "defines the decision variable")]),
    q("Inviting dissent", "Si alguien ve un riesgo que no hayamos considerado, este es el momento de plantearlo.", "If anyone sees a risk we have not considered, this is the moment to raise it.", "Nếu ai thấy một rủi ro chúng ta chưa xem xét, đây là lúc nêu ra.", "leadership invitation", [s("Si alguien ve un riesgo", "if anyone sees a risk", "Nếu ai thấy một rủi ro", "opens space for dissent"), s("que no hayamos considerado", "that we have not considered", "chúng ta chưa xem xét", "acknowledges possible blind spots"), s("este es el momento de plantearlo", "this is the moment to raise it", "đây là lúc nêu ra", "authorizes immediate challenge")]),
    q("Closing with accountability", "Queda acordado que revisaremos los resultados en seis semanas y corregiremos el rumbo si fuera necesario.", "It is agreed that we will review the results in six weeks and adjust course if necessary.", "Chúng ta thống nhất sẽ xem lại kết quả sau sáu tuần và điều chỉnh hướng đi nếu cần.", "accountable decision", [s("Queda acordado que", "it is agreed that", "Chúng ta thống nhất", "records collective commitment"), s("revisaremos los resultados en seis semanas", "we will review the results in six weeks", "sẽ xem lại kết quả sau sáu tuần", "sets the review point"), s("y corregiremos el rumbo si fuera necesario", "and we will adjust course if necessary", "và điều chỉnh hướng đi nếu cần", "preserves adaptive responsibility")]),
  ]],
  [53, "Literary and cultural language", [
    q("Figurative image", "La ciudad despertaba despacio, como si aún dudara entre la noche y el día.", "The city woke slowly, as if it still hesitated between night and day.", "Thành phố thức dậy chậm rãi, như thể vẫn còn do dự giữa đêm và ngày.", "personification and simile", [s("La ciudad despertaba despacio", "the city woke slowly", "Thành phố thức dậy chậm rãi", "personifies a place through an imperfect scene"), s("como si aún dudara", "as if it still hesitated", "như thể vẫn còn do dự", "opens an unreal figurative comparison"), s("entre la noche y el día", "between night and day", "giữa đêm và ngày", "names the symbolic threshold")]),
    q("Interpreting an allusion", "La referencia al viaje no describe solo un desplazamiento, sino una transformación interior.", "The reference to the journey describes not only movement, but an inner transformation.", "Hình ảnh chuyến đi không chỉ mô tả sự di chuyển mà còn là một biến đổi nội tâm.", "symbolic interpretation", [s("La referencia al viaje", "the reference to the journey", "Hình ảnh chuyến đi", "identifies the textual image"), s("no describe solo un desplazamiento", "does not describe only movement", "không chỉ mô tả sự di chuyển", "rejects a purely literal reading"), s("sino una transformación interior", "but an inner transformation", "mà còn là một biến đổi nội tâm", "states the symbolic reading")]),
    q("Marked word order", "Solo entonces comprendió el peso de las palabras que había pronunciado.", "Only then did she understand the weight of the words she had spoken.", "Chỉ đến lúc đó cô ấy mới hiểu sức nặng của những lời mình đã nói.", "foregrounded timing", [s("Solo entonces", "only then", "Chỉ đến lúc đó", "foregrounds the delayed moment"), s("comprendió el peso", "she understood the weight", "cô ấy mới hiểu sức nặng", "states the realization"), s("de las palabras que había pronunciado", "of the words she had spoken", "của những lời mình đã nói", "links it to earlier speech")]),
    q("Cultural idiom", "La expresión no debe tomarse al pie de la letra: invita a actuar con prudencia.", "The expression should not be taken literally: it invites prudent action.", "Không nên hiểu thành ngữ theo nghĩa đen: nó khuyên người ta hành động thận trọng.", "idiom versus literal meaning", [s("La expresión no debe tomarse", "the expression should not be taken", "Không nên hiểu thành ngữ", "warns against a reading"), s("al pie de la letra", "literally", "theo nghĩa đen", "names the rejected method"), s("invita a actuar con prudencia", "it invites prudent action", "nó khuyên người ta hành động thận trọng", "states the pragmatic meaning")]),
  ]],
  [54, "Mediation across languages", [
    q("Reconstructing a concept", "No existe un equivalente exacto; la expresión combina respeto, cercanía y posición social.", "There is no exact equivalent; the expression combines respect, closeness, and social position.", "Không có từ tương đương chính xác; cách nói này kết hợp sự tôn trọng, gần gũi và vị thế xã hội.", "non-equivalence", [s("No existe un equivalente exacto", "there is no exact equivalent", "Không có từ tương đương chính xác", "rejects false one-to-one mapping"), s("la expresión combina", "the expression combines", "cách nói này kết hợp", "opens a component explanation"), s("respeto, cercanía y posición social", "respect, closeness, and social position", "sự tôn trọng, gần gũi và vị thế xã hội", "names the meanings carried together")]),
    q("Preserving intention", "Una traducción literal conservaría las palabras, pero perdería la cortesía implícita.", "A literal translation would preserve the words but lose the implicit courtesy.", "Bản dịch sát chữ sẽ giữ được từ ngữ nhưng làm mất sự lịch sự hàm ý.", "literal versus pragmatic", [s("Una traducción literal conservaría las palabras", "a literal translation would preserve the words", "Bản dịch sát chữ sẽ giữ được từ ngữ", "acknowledges formal preservation"), s("pero perdería", "but would lose", "nhưng làm mất", "marks the pragmatic cost"), s("la cortesía implícita", "the implicit courtesy", "sự lịch sự hàm ý", "names what natural mediation must preserve")]),
    q("Adding context", "Para que se entienda la broma, conviene explicar primero la relación entre los personajes.", "For the joke to be understood, it helps to explain the relationship between the characters first.", "Để hiểu câu đùa, nên giải thích trước mối quan hệ giữa các nhân vật.", "contextual mediation", [s("Para que se entienda la broma", "for the joke to be understood", "Để hiểu câu đùa", "states the comprehension goal"), s("conviene explicar primero", "it helps to explain first", "nên giải thích trước", "recommends added context"), s("la relación entre los personajes", "the relationship between the characters", "mối quan hệ giữa các nhân vật", "identifies the necessary frame")]),
    q("Transparent uncertainty", "La formulación admite varias lecturas; ofreceré la más probable sin presentarla como definitiva.", "The wording allows several readings; I will offer the most likely without presenting it as definitive.", "Cách diễn đạt cho phép nhiều cách hiểu; tôi sẽ nêu cách có khả năng nhất nhưng không coi đó là kết luận cuối cùng.", "honest mediation", [s("La formulación admite varias lecturas", "the wording allows several readings", "Cách diễn đạt cho phép nhiều cách hiểu", "acknowledges ambiguity"), s("ofreceré la más probable", "I will offer the most likely", "tôi sẽ nêu cách có khả năng nhất", "makes a calibrated choice"), s("sin presentarla como definitiva", "without presenting it as definitive", "nhưng không coi đó là kết luận cuối cùng", "preserves uncertainty")]),
  ]],
  [55, "Precision under pressure", [
    q("Correcting immediately", "Retiro esa palabra: no fue irresponsable, sino insuficientemente prudente.", "I withdraw that word: it was not irresponsible, but insufficiently cautious.", "Tôi xin rút lại từ đó: không phải vô trách nhiệm mà là chưa đủ thận trọng.", "precision repair", [s("Retiro esa palabra", "I withdraw that word", "Tôi xin rút lại từ đó", "performs immediate self-correction"), s("no fue irresponsable", "it was not irresponsible", "không phải vô trách nhiệm", "rejects the overstatement"), s("sino insuficientemente prudente", "but insufficiently cautious", "mà là chưa đủ thận trọng", "replaces it with a precise judgment")]),
    q("Responding without overclaiming", "Con la información disponible, puedo confirmar el problema, pero no todavía su causa.", "With the available information, I can confirm the problem, but not yet its cause.", "Với thông tin hiện có, tôi có thể xác nhận vấn đề nhưng chưa thể xác nhận nguyên nhân.", "bounded certainty", [s("Con la información disponible", "with the available information", "Với thông tin hiện có", "states the evidence boundary"), s("puedo confirmar el problema", "I can confirm the problem", "tôi có thể xác nhận vấn đề", "states what is known"), s("pero no todavía su causa", "but not yet its cause", "nhưng chưa thể xác nhận nguyên nhân", "states what remains unknown")]),
    q("Defusing escalation", "Entiendo que la situación es frustrante; centrémonos en lo que podemos resolver ahora.", "I understand that the situation is frustrating; let us focus on what we can resolve now.", "Tôi hiểu tình hình gây bức xúc; hãy tập trung vào điều chúng ta có thể giải quyết ngay.", "calm redirection", [s("Entiendo que la situación es frustrante", "I understand that the situation is frustrating", "Tôi hiểu tình hình gây bức xúc", "validates emotion"), s("centrémonos", "let us focus", "hãy tập trung", "redirects collectively"), s("en lo que podemos resolver ahora", "on what we can resolve now", "vào điều chúng ta có thể giải quyết ngay", "narrows to actionable scope")]),
    q("Protecting accuracy", "Prefiero verificar el dato antes que responder con una seguridad que no tengo.", "I prefer to verify the fact rather than answer with confidence I do not have.", "Tôi muốn kiểm tra dữ liệu hơn là trả lời với sự chắc chắn mình không có.", "epistemic responsibility", [s("Prefiero verificar el dato", "I prefer to verify the fact", "Tôi muốn kiểm tra dữ liệu", "chooses accuracy"), s("antes que responder", "rather than answer", "hơn là trả lời", "contrasts the premature alternative"), s("con una seguridad que no tengo", "with confidence I do not have", "với sự chắc chắn mình không có", "names the false stance avoided")]),
  ]],
  [56, "Research and synthesis", [
    q("Distinguishing claim and evidence", "El artículo afirma que la medida funcionó, pero los datos solo muestran una mejora temporal.", "The article claims the measure worked, but the data show only a temporary improvement.", "Bài báo khẳng định biện pháp có hiệu quả, nhưng dữ liệu chỉ cho thấy sự cải thiện tạm thời.", "claim versus evidence", [s("El artículo afirma que la medida funcionó", "the article claims the measure worked", "Bài báo khẳng định biện pháp có hiệu quả", "states the source's conclusion"), s("pero los datos solo muestran", "but the data show only", "nhưng dữ liệu chỉ cho thấy", "limits it to observed evidence"), s("una mejora temporal", "a temporary improvement", "sự cải thiện tạm thời", "names the actual finding")]),
    q("Integrating sources", "Mientras un estudio destaca los beneficios, otro advierte de efectos que aún no se han medido.", "While one study highlights the benefits, another warns of effects that have not yet been measured.", "Trong khi một nghiên cứu nhấn mạnh lợi ích, nghiên cứu khác cảnh báo về những tác động chưa được đo lường.", "source contrast", [s("Mientras un estudio destaca los beneficios", "while one study highlights the benefits", "Trong khi một nghiên cứu nhấn mạnh lợi ích", "summarizes the first source"), s("otro advierte de efectos", "another warns of effects", "nghiên cứu khác cảnh báo về những tác động", "introduces the second source"), s("que aún no se han medido", "that have not yet been measured", "chưa được đo lường", "identifies the evidential gap")]),
    q("Synthesizing a pattern", "En los tres casos se observa la misma tendencia: el efecto disminuye con el tiempo.", "The same trend is observed in all three cases: the effect decreases over time.", "Trong cả ba trường hợp đều thấy cùng một xu hướng: tác động giảm dần theo thời gian.", "cross-source pattern", [s("En los tres casos", "in all three cases", "Trong cả ba trường hợp", "sets the synthesis scope"), s("se observa la misma tendencia", "the same trend is observed", "đều thấy cùng một xu hướng", "states the shared pattern"), s("el efecto disminuye con el tiempo", "the effect decreases over time", "tác động giảm dần theo thời gian", "defines that pattern")]),
    q("Reporting limitations", "La conclusión debe interpretarse con cautela, dado que la muestra era pequeña y poco diversa.", "The conclusion should be interpreted cautiously, given that the sample was small and not very diverse.", "Cần diễn giải kết luận thận trọng vì mẫu nghiên cứu nhỏ và ít đa dạng.", "methodological qualification", [s("La conclusión debe interpretarse con cautela", "the conclusion should be interpreted cautiously", "Cần diễn giải kết luận thận trọng", "calibrates the claim"), s("dado que", "given that", "vì", "introduces the methodological reason"), s("la muestra era pequeña y poco diversa", "the sample was small and not very diverse", "mẫu nghiên cứu nhỏ và ít đa dạng", "states the limitation")]),
  ]],
  [57, "Philosophy and meaning", [
    q("Defining freedom", "La libertad puede entenderse no como ausencia de límites, sino como capacidad de orientar la propia vida.", "Freedom can be understood not as an absence of limits, but as the capacity to direct one's own life.", "Tự do có thể được hiểu không phải là không có giới hạn mà là khả năng định hướng cuộc đời mình.", "conceptual distinction", [s("La libertad puede entenderse", "freedom can be understood", "Tự do có thể được hiểu", "opens a proposed definition"), s("no como ausencia de límites", "not as an absence of limits", "không phải là không có giới hạn", "rejects one conception"), s("sino como capacidad de orientar la propia vida", "but as the capacity to direct one's own life", "mà là khả năng định hướng cuộc đời mình", "states the alternative")]),
    q("Testing a principle", "Si toda decisión está condicionada, ¿en qué sentido podemos seguir hablando de responsabilidad?", "If every decision is conditioned, in what sense can we continue speaking of responsibility?", "Nếu mọi quyết định đều bị chi phối, theo nghĩa nào chúng ta vẫn có thể nói về trách nhiệm?", "philosophical question", [s("Si toda decisión está condicionada", "if every decision is conditioned", "Nếu mọi quyết định đều bị chi phối", "states the premise"), s("¿en qué sentido", "in what sense", "theo nghĩa nào", "questions the relevant definition"), s("podemos seguir hablando de responsabilidad?", "can we continue speaking of responsibility", "chúng ta vẫn có thể nói về trách nhiệm?", "tests the concept against the premise")]),
    q("Preserving a distinction", "Comprender una acción no equivale a justificarla, aunque ambas cosas puedan parecer cercanas.", "Understanding an action is not equivalent to justifying it, although the two may seem close.", "Hiểu một hành động không đồng nghĩa với biện minh cho nó, dù hai việc có vẻ gần nhau.", "understanding versus justification", [s("Comprender una acción", "understanding an action", "Hiểu một hành động", "names the first concept"), s("no equivale a justificarla", "is not equivalent to justifying it", "không đồng nghĩa với biện minh cho nó", "draws the distinction"), s("aunque ambas cosas puedan parecer cercanas", "although the two may seem close", "dù hai việc có vẻ gần nhau", "concedes their apparent overlap")]),
    q("Reasoning conditionally", "Si el valor de una vida no depende de su utilidad, entonces la dignidad no puede medirse por la productividad.", "If the value of a life does not depend on its usefulness, then dignity cannot be measured by productivity.", "Nếu giá trị của một đời người không phụ thuộc vào tính hữu ích, thì phẩm giá không thể đo bằng năng suất.", "conditional argument", [s("Si el valor de una vida no depende de su utilidad", "if the value of a life does not depend on its usefulness", "Nếu giá trị của một đời người không phụ thuộc vào tính hữu ích", "states the principle"), s("entonces la dignidad", "then dignity", "thì phẩm giá", "introduces the implication"), s("no puede medirse por la productividad", "cannot be measured by productivity", "không thể đo bằng năng suất", "states the derived conclusion")]),
  ]],
  [58, "Public reasoning", [
    q("Addressing a broad audience", "La pregunta que debemos hacernos no es quién gana hoy, sino qué sociedad queremos construir.", "The question we must ask is not who wins today, but what society we want to build.", "Câu hỏi chúng ta cần đặt ra không phải là ai thắng hôm nay mà là muốn xây dựng một xã hội như thế nào.", "public reframing", [s("La pregunta que debemos hacernos", "the question we must ask ourselves", "Câu hỏi chúng ta cần đặt ra", "establishes collective responsibility"), s("no es quién gana hoy", "is not who wins today", "không phải là ai thắng hôm nay", "rejects the narrow frame"), s("sino qué sociedad queremos construir", "but what society we want to build", "mà là muốn xây dựng một xã hội như thế nào", "opens the larger public frame")]),
    q("Recognizing legitimate concern", "Quienes temen el cambio plantean una preocupación legítima que merece una respuesta concreta.", "Those who fear the change raise a legitimate concern that deserves a concrete answer.", "Những người lo ngại thay đổi nêu ra một mối quan tâm chính đáng cần được trả lời cụ thể.", "fair representation", [s("Quienes temen el cambio", "those who fear the change", "Những người lo ngại thay đổi", "identifies the opposing public"), s("plantean una preocupación legítima", "raise a legitimate concern", "nêu ra một mối quan tâm chính đáng", "recognizes validity"), s("que merece una respuesta concreta", "that deserves a concrete answer", "cần được trả lời cụ thể", "accepts the burden of response")]),
    q("Defending with proportion", "La propuesta no resolverá todos los problemas, pero puede mejorar de forma significativa una parte de ellos.", "The proposal will not solve every problem, but it can significantly improve some of them.", "Đề xuất sẽ không giải quyết mọi vấn đề, nhưng có thể cải thiện đáng kể một phần.", "proportionate claim", [s("La propuesta no resolverá todos los problemas", "the proposal will not solve every problem", "Đề xuất sẽ không giải quyết mọi vấn đề", "rejects an absolute promise"), s("pero puede mejorar de forma significativa", "but it can significantly improve", "nhưng có thể cải thiện đáng kể", "states the defensible benefit"), s("una parte de ellos", "some of them", "một phần", "limits the scope honestly")]),
    q("Answering criticism", "La crítica señala un riesgo real; precisamente por eso incluimos una revisión independiente.", "The criticism identifies a real risk; that is precisely why we included an independent review.", "Lời phê bình chỉ ra một rủi ro có thật; chính vì vậy chúng tôi đưa vào cơ chế đánh giá độc lập.", "criticism into safeguard", [s("La crítica señala un riesgo real", "the criticism identifies a real risk", "Lời phê bình chỉ ra một rủi ro có thật", "accepts the factual concern"), s("precisamente por eso", "precisely for that reason", "chính vì vậy", "turns the concern into rationale"), s("incluimos una revisión independiente", "we included an independent review", "chúng tôi đưa vào cơ chế đánh giá độc lập", "states the safeguard")]),
  ]],
  [59, "Idiomatic control", [
    q("Choosing an idiom", "Después de meses de dudas, decidió dar el paso y presentar su proyecto.", "After months of doubt, she decided to take the plunge and present her project.", "Sau nhiều tháng do dự, cô ấy quyết định mạnh dạn tiến bước và trình bày dự án.", "idiom for commitment", [s("Después de meses de dudas", "after months of doubt", "Sau nhiều tháng do dự", "sets the prior hesitation"), s("decidió dar el paso", "she decided to take the step", "cô ấy quyết định mạnh dạn tiến bước", "uses an idiom for committing"), s("y presentar su proyecto", "and present her project", "và trình bày dự án", "states the concrete action")]),
    q("Recognizing limits", "La expresión suena natural entre amigos, pero resultaría demasiado informal en un informe.", "The expression sounds natural among friends but would be too informal in a report.", "Cách nói này tự nhiên giữa bạn bè nhưng sẽ quá thân mật trong một báo cáo.", "register limits of idiom", [s("La expresión suena natural", "the expression sounds natural", "Cách nói này tự nhiên", "evaluates idiomatic fit"), s("entre amigos", "among friends", "giữa bạn bè", "sets the suitable context"), s("pero resultaría demasiado informal en un informe", "but would be too informal in a report", "nhưng sẽ quá thân mật trong một báo cáo", "marks the register boundary")]),
    q("Regional awareness", "En esta región se usa con frecuencia, mientras que en otros lugares puede sonar anticuado.", "It is used frequently in this region, while elsewhere it may sound old-fashioned.", "Ở vùng này cách nói được dùng thường xuyên, trong khi ở nơi khác có thể nghe lỗi thời.", "regional variation", [s("En esta región se usa con frecuencia", "it is used frequently in this region", "Ở vùng này cách nói được dùng thường xuyên", "locates common usage"), s("mientras que en otros lugares", "while in other places", "trong khi ở nơi khác", "opens regional contrast"), s("puede sonar anticuado", "it may sound old-fashioned", "có thể nghe lỗi thời", "qualifies reception elsewhere")]),
    q("Avoiding decorative idiom", "La metáfora aclara la idea porque organiza la relación, no simplemente porque suena elegante.", "The metaphor clarifies the idea because it organizes the relationship, not simply because it sounds elegant.", "Ẩn dụ làm rõ ý vì nó tổ chức mối quan hệ, không chỉ vì nghe tao nhã.", "functional figurative language", [s("La metáfora aclara la idea", "the metaphor clarifies the idea", "Ẩn dụ làm rõ ý", "states its communicative effect"), s("porque organiza la relación", "because it organizes the relationship", "vì nó tổ chức mối quan hệ", "gives the substantive reason"), s("no simplemente porque suena elegante", "not simply because it sounds elegant", "không chỉ vì nghe tao nhã", "rejects decoration as sufficient")]),
  ]],
  [60, "C1 integration", [
    q("Integrated inference", "Aunque nadie lo afirmó abiertamente, el cambio de tono indicaba que el acuerdo estaba en peligro.", "Although no one stated it openly, the change in tone indicated that the agreement was in danger.", "Mặc dù không ai nói thẳng, sự thay đổi giọng điệu cho thấy thỏa thuận đang gặp nguy hiểm.", "implicit synthesis", [s("Aunque nadie lo afirmó abiertamente", "although no one stated it openly", "Mặc dù không ai nói thẳng", "marks the absence of explicit speech"), s("el cambio de tono indicaba", "the change in tone indicated", "sự thay đổi giọng điệu cho thấy", "identifies the pragmatic evidence"), s("que el acuerdo estaba en peligro", "that the agreement was in danger", "thỏa thuận đang gặp nguy hiểm", "states the inference")]),
    q("Integrated leadership", "Propongo que avancemos, pero con mecanismos que nos permitan corregir el rumbo si cambian las circunstancias.", "I propose that we proceed, but with mechanisms that allow us to adjust course if circumstances change.", "Tôi đề nghị chúng ta tiến hành, nhưng cần có cơ chế cho phép điều chỉnh hướng đi nếu hoàn cảnh thay đổi.", "adaptive strategy", [s("Propongo que avancemos", "I propose that we proceed", "Tôi đề nghị chúng ta tiến hành", "states the decision direction"), s("pero con mecanismos que nos permitan corregir el rumbo", "but with mechanisms allowing us to adjust course", "nhưng cần có cơ chế cho phép điều chỉnh hướng đi", "builds in adaptation"), s("si cambian las circunstancias", "if circumstances change", "nếu hoàn cảnh thay đổi", "defines the trigger")]),
    q("Integrated mediation", "El desacuerdo no radica en los hechos, sino en el valor que cada parte les atribuye.", "The disagreement lies not in the facts, but in the value each side assigns to them.", "Bất đồng không nằm ở sự kiện mà ở giá trị mỗi bên gán cho chúng.", "conceptual mediation", [s("El desacuerdo no radica en los hechos", "the disagreement does not lie in the facts", "Bất đồng không nằm ở sự kiện", "identifies shared evidence"), s("sino en el valor", "but in the value", "mà ở giá trị", "relocates the conflict"), s("que cada parte les atribuye", "each side assigns to them", "mỗi bên gán cho chúng", "identifies differing interpretation")]),
    q("C1 reflection", "Puedo expresar ideas complejas con flexibilidad, aunque sigo afinando mi voz en contextos nuevos.", "I can express complex ideas flexibly, although I continue refining my voice in new contexts.", "Tôi có thể diễn đạt ý tưởng phức tạp một cách linh hoạt, dù vẫn tiếp tục trau chuốt giọng điệu trong bối cảnh mới.", "advanced self-assessment", [s("Puedo expresar ideas complejas", "I can express complex ideas", "Tôi có thể diễn đạt ý tưởng phức tạp", "states the achieved range"), s("con flexibilidad", "flexibly", "một cách linh hoạt", "qualifies control"), s("aunque sigo afinando mi voz en contextos nuevos", "although I continue refining my voice in new contexts", "dù vẫn tiếp tục trau chuốt giọng điệu trong bối cảnh mới", "keeps development open")]),
  ]],
];

let previous = "b2-u48-4-b2-reflection";
const lessons = [];
for (const [unitNumber, unitTitle, items] of groups) for (const [index, item] of items.entries()) {
  const slug = item.title.toLocaleLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
  const objectiveId = `c1-u${unitNumber}-${index + 1}-${slug}`;
  lessons.push({ id: `${objectiveId}-lesson`, objectiveId, prerequisites: [previous], unit: unitNumber, lesson: index + 1,
    unitTitle, title: item.title, skill: `${unitTitle.toLocaleLowerCase()}: ${item.focus}`, spanish: item.spanish, english: item.english,
    vietnamese: item.vietnamese, focus: item.focus, pattern: item.focus, bridgePattern: item.focus,
    units: item.units.map((entry) => ({ ...entry, part: "Contextual phrase",
      spanishForm: `In this C1 sentence, “${entry.spanish}” realizes ${entry.role}; its exact mood, tense, agreement, information structure, and governed links are interpreted in context.`,
      vietnameseForm: `In this C1 sentence, “${entry.vietnamese}” realizes ${entry.role}; its analytic order, particles, aspect, register, and implied information are interpreted in context.` })) });
  previous = objectiveId;
}

export default { id: "c1-core-1", version: 1, level: "C1", lessons };
