const s = (spanish, meaning, vietnamese, role) => ({ spanish, meaning, vietnamese, role });
const q = (title, spanish, english, vietnamese, focus, units) => ({ title, spanish, english, vietnamese, focus, units });

const groups = [
  [61, "Fine shades of meaning", [
    q("Reluctance or refusal", "No es que se negara; más bien parecía poco dispuesto a comprometerse.", "It is not that he refused; rather, he seemed reluctant to commit.", "Không hẳn là anh ấy từ chối; đúng hơn là anh ấy có vẻ không sẵn lòng cam kết.", "calibrated willingness", [s("No es que se negara", "it is not that he refused", "Không hẳn là anh ấy từ chối", "rejects the stronger interpretation"), s("más bien parecía poco dispuesto", "rather, he seemed reluctant", "đúng hơn là anh ấy có vẻ không sẵn lòng", "substitutes a finer stance"), s("a comprometerse", "to commit", "cam kết", "names the withheld action")]),
    q("Concern or alarm", "La situación me inquieta, aunque no diría que me alarma.", "The situation concerns me, though I would not say it alarms me.", "Tình hình khiến tôi băn khoăn, dù tôi không đến mức nói rằng mình hoảng sợ.", "intensity distinction", [s("La situación me inquieta", "the situation concerns me", "Tình hình khiến tôi băn khoăn", "states moderate unease"), s("aunque no diría", "though I would not say", "dù tôi không đến mức nói rằng", "marks a deliberate limit"), s("que me alarma", "that it alarms me", "mình hoảng sợ", "excludes a stronger emotion")]),
    q("Possible or plausible", "La explicación es posible, pero todavía no resulta plenamente plausible.", "The explanation is possible, but it is not yet fully plausible.", "Lời giải thích có thể xảy ra, nhưng vẫn chưa thật sự thuyết phục.", "logical versus evidential possibility", [s("La explicación es posible", "the explanation is possible", "Lời giải thích có thể xảy ra", "allows logical possibility"), s("pero todavía no resulta", "but it is not yet", "nhưng vẫn chưa", "marks an evidential reservation"), s("plenamente plausible", "fully plausible", "thật sự thuyết phục", "names the stronger standard")]),
    q("Precision of stance", "Lo considero desacertado, no tanto por el resultado como por el criterio empleado.", "I consider it misguided, less because of the result than because of the criterion used.", "Tôi cho rằng điều đó không thỏa đáng, không hẳn vì kết quả mà vì tiêu chí được sử dụng.", "source of judgment", [s("Lo considero desacertado", "I consider it misguided", "Tôi cho rằng điều đó không thỏa đáng", "states a precise evaluation"), s("no tanto por el resultado", "not so much because of the result", "không hẳn vì kết quả", "downweights one basis"), s("como por el criterio empleado", "as because of the criterion used", "mà vì tiêu chí được sử dụng", "identifies the decisive basis")]),
  ]],
  [62, "Effortless reformulation", [
    q("Compressing an argument", "En suma, el problema consiste en que exigimos resultados inmediatos a procesos que requieren tiempo.", "In short, the problem is that we demand immediate results from processes that require time.", "Tóm lại, vấn đề là chúng ta đòi kết quả tức thì từ những quá trình cần thời gian.", "argument compression", [s("En suma", "in short", "Tóm lại", "signals compression"), s("el problema consiste en que exigimos resultados inmediatos", "the problem is that we demand immediate results", "vấn đề là chúng ta đòi kết quả tức thì", "states the central mismatch"), s("a procesos que requieren tiempo", "from processes that require time", "từ những quá trình cần thời gian", "names the conflicting reality")]),
    q("Expanding a premise", "Dicho con mayor precisión, la confianza no desapareció de golpe, sino que se fue erosionando.", "More precisely, trust did not disappear at once; it gradually eroded.", "Nói chính xác hơn, niềm tin không biến mất đột ngột mà bị bào mòn dần.", "aspectual reformulation", [s("Dicho con mayor precisión", "more precisely", "Nói chính xác hơn", "signals refinement"), s("la confianza no desapareció de golpe", "trust did not disappear at once", "niềm tin không biến mất đột ngột", "rejects a punctual reading"), s("sino que se fue erosionando", "but gradually eroded", "mà bị bào mòn dần", "recasts it as progressive change")]),
    q("Changing grammatical form", "Lo que antes se describía como un fracaso hoy se interpreta como aprendizaje.", "What used to be described as failure is now interpreted as learning.", "Điều trước đây được mô tả là thất bại nay được hiểu là bài học.", "nominal-verbal shift", [s("Lo que antes se describía como un fracaso", "what used to be described as failure", "Điều trước đây được mô tả là thất bại", "packages the earlier label"), s("hoy se interpreta", "is now interpreted", "nay được hiểu", "shifts viewpoint and time"), s("como aprendizaje", "as learning", "là bài học", "supplies the new frame")]),
    q("Preserving tone", "Podría resumirlo como una negativa, pero eso borraría la delicadeza con que puso el límite.", "I could summarize it as a refusal, but that would erase the delicacy with which she set the boundary.", "Có thể tóm tắt đó là lời từ chối, nhưng như vậy sẽ làm mất sự tinh tế trong cách cô ấy đặt giới hạn.", "tone-preserving paraphrase", [s("Podría resumirlo como una negativa", "I could summarize it as a refusal", "Có thể tóm tắt đó là lời từ chối", "offers a compressed paraphrase"), s("pero eso borraría la delicadeza", "but that would erase the delicacy", "nhưng như vậy sẽ làm mất sự tinh tế", "identifies its loss"), s("con que puso el límite", "with which she set the boundary", "trong cách cô ấy đặt giới hạn", "names the preserved interpersonal meaning")]),
  ]],
  [63, "Idiomatic command", [
    q("Judicious idiom", "Tras varias tentativas fallidas, por fin dieron con la clave del problema.", "After several failed attempts, they finally hit upon the key to the problem.", "Sau nhiều lần thử không thành, cuối cùng họ cũng tìm ra mấu chốt của vấn đề.", "idiomatic discovery", [s("Tras varias tentativas fallidas", "after several failed attempts", "Sau nhiều lần thử không thành", "sets the search history"), s("por fin dieron con", "they finally hit upon", "cuối cùng họ cũng tìm ra", "uses an idiom for successful discovery"), s("la clave del problema", "the key to the problem", "mấu chốt của vấn đề", "names the decisive insight")]),
    q("Collocational precision", "La decisión suscitó dudas razonables, pero no desató la crisis que algunos habían previsto.", "The decision raised reasonable doubts but did not unleash the crisis some had predicted.", "Quyết định làm dấy lên những nghi ngờ hợp lý, nhưng không gây ra cuộc khủng hoảng mà một số người dự đoán.", "strong collocations", [s("La decisión suscitó dudas razonables", "the decision raised reasonable doubts", "Quyết định làm dấy lên những nghi ngờ hợp lý", "uses a formal cause-response collocation"), s("pero no desató la crisis", "but did not unleash the crisis", "nhưng không gây ra cuộc khủng hoảng", "rejects the stronger consequence"), s("que algunos habían previsto", "that some had predicted", "mà một số người dự đoán", "attributes the forecast")]),
    q("Contextual limit", "La frase encaja en una conversación distendida, pero sonaría afectada en un intercambio cotidiano.", "The phrase fits a relaxed conversation but would sound mannered in an everyday exchange.", "Câu này hợp với cuộc trò chuyện thoải mái, nhưng sẽ nghe kiểu cách trong giao tiếp hằng ngày.", "idiomatic fit", [s("La frase encaja en una conversación distendida", "the phrase fits a relaxed conversation", "Câu này hợp với cuộc trò chuyện thoải mái", "marks a suitable context"), s("pero sonaría afectada", "but would sound mannered", "nhưng sẽ nghe kiểu cách", "predicts an unwanted effect"), s("en un intercambio cotidiano", "in an everyday exchange", "trong giao tiếp hằng ngày", "sets the unsuitable context")]),
    q("Regional judgment", "Aunque la locución se entiende ampliamente, su uso activo está muy ligado a ciertas regiones.", "Although the expression is widely understood, its active use is closely tied to certain regions.", "Mặc dù thành ngữ được hiểu rộng rãi, việc chủ động sử dụng lại gắn chặt với một số vùng.", "receptive versus active idiom", [s("Aunque la locución se entiende ampliamente", "although the expression is widely understood", "Mặc dù thành ngữ được hiểu rộng rãi", "states broad receptive knowledge"), s("su uso activo está muy ligado", "its active use is closely tied", "việc chủ động sử dụng lại gắn chặt", "limits productive use"), s("a ciertas regiones", "to certain regions", "với một số vùng", "locates the variation")]),
  ]],
  [64, "Rhetoric and style", [
    q("Parallel emphasis", "No pedimos certezas; pedimos rigor. No exigimos unanimidad; exigimos honestidad.", "We do not ask for certainty; we ask for rigor. We do not demand unanimity; we demand honesty.", "Chúng ta không đòi sự chắc chắn; chúng ta đòi tính nghiêm cẩn. Không yêu cầu đồng thuận tuyệt đối; yêu cầu sự trung thực.", "rhetorical parallelism", [s("No pedimos certezas; pedimos rigor", "we do not ask for certainty; we ask for rigor", "Chúng ta không đòi sự chắc chắn; chúng ta đòi tính nghiêm cẩn", "builds contrast through repetition"), s("No exigimos unanimidad", "we do not demand unanimity", "Không yêu cầu đồng thuận tuyệt đối", "repeats the negative frame"), s("exigimos honestidad", "we demand honesty", "yêu cầu sự trung thực", "lands on the governing value")]),
    q("Rhythmic accumulation", "Escuchó, dudó, volvió sobre sus pasos y, solo entonces, respondió.", "She listened, hesitated, retraced her steps, and only then answered.", "Cô ấy lắng nghe, do dự, suy nghĩ lại và chỉ lúc đó mới trả lời.", "narrative rhythm", [s("Escuchó, dudó", "she listened, hesitated", "Cô ấy lắng nghe, do dự", "begins a measured sequence"), s("volvió sobre sus pasos", "she retraced her steps", "suy nghĩ lại", "adds reconsideration"), s("y, solo entonces, respondió", "and only then answered", "và chỉ lúc đó mới trả lời", "delays the decisive action")]),
    q("Foregrounding a value", "Lo esencial no es cuánto avanzamos, sino qué nos negamos a sacrificar para hacerlo.", "What matters is not how far we advance, but what we refuse to sacrifice in doing so.", "Điều cốt yếu không phải là tiến được bao xa mà là điều chúng ta từ chối hy sinh để đạt được nó.", "rhetorical focus", [s("Lo esencial no es cuánto avanzamos", "what matters is not how far we advance", "Điều cốt yếu không phải là tiến được bao xa", "rejects speed as the measure"), s("sino qué nos negamos a sacrificar", "but what we refuse to sacrifice", "mà là điều chúng ta từ chối hy sinh", "foregrounds moral limits"), s("para hacerlo", "in doing so", "để đạt được nó", "links limits to progress")]),
    q("Controlled understatement", "El resultado dista bastante de ser ideal, por decirlo con moderación.", "The result is quite far from ideal, to put it mildly.", "Kết quả còn cách xa lý tưởng, nói một cách nhẹ nhàng.", "understatement", [s("El resultado dista bastante", "the result is quite far", "Kết quả còn cách xa", "states a measured negative judgment"), s("de ser ideal", "from being ideal", "lý tưởng", "names the standard"), s("por decirlo con moderación", "to put it mildly", "nói một cách nhẹ nhàng", "signals deliberate understatement")]),
  ]],
  [65, "Complex mediation", [
    q("Reconciling sources", "Las fuentes no se contradicen por completo: describen momentos distintos del mismo proceso.", "The sources do not entirely contradict one another; they describe different moments in the same process.", "Các nguồn không hoàn toàn mâu thuẫn; chúng mô tả những thời điểm khác nhau của cùng một quá trình.", "source reconciliation", [s("Las fuentes no se contradicen por completo", "the sources do not entirely contradict one another", "Các nguồn không hoàn toàn mâu thuẫn", "limits the apparent conflict"), s("describen momentos distintos", "they describe different moments", "chúng mô tả những thời điểm khác nhau", "explains the divergence"), s("del mismo proceso", "of the same process", "của cùng một quá trình", "restores conceptual unity")]),
    q("Mapping concepts", "Un marco habla de obligación; el otro expresa la misma relación en términos de pertenencia y deber mutuo.", "One framework speaks of obligation; the other expresses the same relationship through belonging and mutual duty.", "Một khuôn khổ nói về nghĩa vụ; khuôn khổ kia diễn đạt cùng mối quan hệ bằng sự thuộc về và bổn phận tương hỗ.", "conceptual translation", [s("Un marco habla de obligación", "one framework speaks of obligation", "Một khuôn khổ nói về nghĩa vụ", "states the first conceptual vocabulary"), s("el otro expresa la misma relación", "the other expresses the same relationship", "khuôn khổ kia diễn đạt cùng mối quan hệ", "preserves the underlying meaning"), s("en términos de pertenencia y deber mutuo", "through belonging and mutual duty", "bằng sự thuộc về và bổn phận tương hỗ", "states the alternative frame")]),
    q("Weighing testimony", "El testimonio aporta una experiencia irreductible a las estadísticas, aunque no sustituye el análisis general.", "The testimony contributes an experience irreducible to statistics, though it does not replace general analysis.", "Lời chứng mang lại trải nghiệm không thể quy giản thành số liệu, dù không thay thế phân tích tổng thể.", "evidence-type mediation", [s("El testimonio aporta una experiencia", "the testimony contributes an experience", "Lời chứng mang lại trải nghiệm", "recognizes experiential evidence"), s("irreductible a las estadísticas", "irreducible to statistics", "không thể quy giản thành số liệu", "protects its distinct meaning"), s("aunque no sustituye el análisis general", "though it does not replace general analysis", "dù không thay thế phân tích tổng thể", "preserves methodological limits")]),
    q("Making a relationship visible", "La aparente paradoja desaparece si distinguimos entre control inmediato e influencia a largo plazo.", "The apparent paradox disappears if we distinguish immediate control from long-term influence.", "Nghịch lý bề ngoài biến mất nếu phân biệt kiểm soát tức thời với ảnh hưởng lâu dài.", "conceptual clarification", [s("La aparente paradoja desaparece", "the apparent paradox disappears", "Nghịch lý bề ngoài biến mất", "states the clarified result"), s("si distinguimos", "if we distinguish", "nếu phân biệt", "names the analytic action"), s("entre control inmediato e influencia a largo plazo", "immediate control from long-term influence", "kiểm soát tức thời với ảnh hưởng lâu dài", "draws the decisive distinction")]),
  ]],
  [66, "Cultural and interpersonal mastery", [
    q("Protecting face", "En vez de corregirlo delante del grupo, buscó una forma de señalar el error sin exponerlo.", "Rather than correct him before the group, she found a way to point out the error without exposing him.", "Thay vì sửa anh ấy trước nhóm, cô ấy tìm cách chỉ ra lỗi mà không làm anh ấy mất mặt.", "face-sensitive repair", [s("En vez de corregirlo delante del grupo", "rather than correct him before the group", "Thay vì sửa anh ấy trước nhóm", "rejects public correction"), s("buscó una forma de señalar el error", "she found a way to point out the error", "cô ấy tìm cách chỉ ra lỗi", "preserves the substantive repair"), s("sin exponerlo", "without exposing him", "mà không làm anh ấy mất mặt", "protects social face")]),
    q("Hierarchy and warmth", "El tratamiento es respetuoso sin resultar distante, algo difícil de reproducir con una sola palabra.", "The form of address is respectful without sounding distant, something difficult to reproduce with a single word.", "Cách xưng hô vừa tôn trọng mà không xa cách, điều khó tái hiện bằng một từ duy nhất.", "address-system nuance", [s("El tratamiento es respetuoso", "the form of address is respectful", "Cách xưng hô vừa tôn trọng", "states the status relation"), s("sin resultar distante", "without sounding distant", "mà không xa cách", "preserves warmth"), s("algo difícil de reproducir con una sola palabra", "something difficult to reproduce with a single word", "điều khó tái hiện bằng một từ duy nhất", "marks cross-language compression loss")]),
    q("Delicate disagreement", "Puede que tengas razón en el fondo; donde discrepo es en la manera de llevarlo a la práctica.", "You may be right in principle; where I disagree is in how to put it into practice.", "Có thể về cơ bản bạn đúng; điểm tôi không đồng ý là cách đưa nó vào thực tế.", "agreement with bounded dissent", [s("Puede que tengas razón en el fondo", "you may be right in principle", "Có thể về cơ bản bạn đúng", "concedes the underlying point"), s("donde discrepo", "where I disagree", "điểm tôi không đồng ý", "locates rather than globalizes dissent"), s("es en la manera de llevarlo a la práctica", "is in how to put it into practice", "là cách đưa nó vào thực tế", "defines the practical disagreement")]),
    q("Humor with judgment", "La broma alivió la tensión porque se dirigía a la situación, no a la dignidad de nadie.", "The joke eased the tension because it targeted the situation, not anyone's dignity.", "Câu đùa làm dịu căng thẳng vì nhắm vào tình huống chứ không vào phẩm giá của ai.", "socially safe humor", [s("La broma alivió la tensión", "the joke eased the tension", "Câu đùa làm dịu căng thẳng", "states the social effect"), s("porque se dirigía a la situación", "because it targeted the situation", "vì nhắm vào tình huống", "identifies the safe target"), s("no a la dignidad de nadie", "not anyone's dignity", "chứ không vào phẩm giá của ai", "marks the ethical boundary")]),
  ]],
  [67, "Specialized expression", [
    q("Defining a technical term", "Por resiliencia del sistema entendemos su capacidad de seguir funcionando pese a fallos parciales.", "By system resilience we mean its capacity to keep functioning despite partial failures.", "Khả năng phục hồi của hệ thống được hiểu là khả năng tiếp tục hoạt động dù có lỗi cục bộ.", "technical definition", [s("Por resiliencia del sistema entendemos", "by system resilience we mean", "Khả năng phục hồi của hệ thống được hiểu là", "establishes a field-specific definition"), s("su capacidad de seguir funcionando", "its capacity to keep functioning", "khả năng tiếp tục hoạt động", "states the core property"), s("pese a fallos parciales", "despite partial failures", "dù có lỗi cục bộ", "sets the stress condition")]),
    q("Adapting to a field", "En términos jurídicos, la intención importa, pero no elimina necesariamente la responsabilidad.", "In legal terms, intention matters but does not necessarily eliminate liability.", "Theo thuật ngữ pháp lý, ý định có ý nghĩa nhưng không nhất thiết loại bỏ trách nhiệm.", "disciplinary register", [s("En términos jurídicos", "in legal terms", "Theo thuật ngữ pháp lý", "sets the expert frame"), s("la intención importa", "intention matters", "ý định có ý nghĩa", "states one relevant factor"), s("pero no elimina necesariamente la responsabilidad", "but does not necessarily eliminate liability", "nhưng không nhất thiết loại bỏ trách nhiệm", "qualifies its legal effect")]),
    q("Explaining across expertise", "Para una persona no especialista, puede describirse como un filtro que separa señal y ruido.", "For a non-specialist, it can be described as a filter separating signal from noise.", "Với người không chuyên, có thể mô tả nó như một bộ lọc tách tín hiệu khỏi nhiễu.", "expert-to-public mediation", [s("Para una persona no especialista", "for a non-specialist", "Với người không chuyên", "identifies the audience"), s("puede describirse como un filtro", "it can be described as a filter", "có thể mô tả nó như một bộ lọc", "offers an accessible model"), s("que separa señal y ruido", "separating signal from noise", "tách tín hiệu khỏi nhiễu", "maps the technical function")]),
    q("Genre control", "El resumen ejecutivo prioriza la decisión; el anexo conserva el detalle que permite auditarla.", "The executive summary prioritizes the decision; the appendix preserves the detail needed to audit it.", "Bản tóm tắt điều hành ưu tiên quyết định; phụ lục giữ lại chi tiết cần thiết để kiểm tra.", "genre-specific information", [s("El resumen ejecutivo prioriza la decisión", "the executive summary prioritizes the decision", "Bản tóm tắt điều hành ưu tiên quyết định", "states one genre's purpose"), s("el anexo conserva el detalle", "the appendix preserves the detail", "phụ lục giữ lại chi tiết", "contrasts the supporting genre"), s("que permite auditarla", "that permits it to be audited", "cần thiết để kiểm tra", "states why detail remains")]),
  ]],
  [68, "Expert dialogue", [
    q("Challenging a premise", "Antes de aceptar la conclusión, convendría examinar si el modelo presupone aquello que pretende demostrar.", "Before accepting the conclusion, we should examine whether the model assumes what it seeks to prove.", "Trước khi chấp nhận kết luận, nên xem mô hình có giả định chính điều nó muốn chứng minh hay không.", "premise audit", [s("Antes de aceptar la conclusión", "before accepting the conclusion", "Trước khi chấp nhận kết luận", "suspends assent"), s("convendría examinar si el modelo presupone", "we should examine whether the model assumes", "nên xem mô hình có giả định", "opens a premise test"), s("aquello que pretende demostrar", "what it seeks to prove", "chính điều nó muốn chứng minh hay không", "names the circularity risk")]),
    q("Revising a position", "A la vista de esa distinción, reformularía mi objeción: el problema es de alcance, no de validez.", "In light of that distinction, I would reformulate my objection: the problem concerns scope, not validity.", "Xét theo sự phân biệt đó, tôi sẽ diễn đạt lại phản đối: vấn đề nằm ở phạm vi chứ không phải tính hợp lệ.", "instant revision", [s("A la vista de esa distinción", "in light of that distinction", "Xét theo sự phân biệt đó", "acknowledges new analysis"), s("reformularía mi objeción", "I would reformulate my objection", "tôi sẽ diễn đạt lại phản đối", "revises the stance"), s("el problema es de alcance, no de validez", "the problem concerns scope, not validity", "vấn đề nằm ở phạm vi chứ không phải tính hợp lệ", "states the corrected diagnosis")]),
    q("Clarifying assumptions", "¿Estamos suponiendo que las preferencias permanecen estables, o el modelo permite que evolucionen?", "Are we assuming preferences remain stable, or does the model allow them to evolve?", "Chúng ta đang giả định sở thích không đổi, hay mô hình cho phép chúng phát triển?", "assumption clarification", [s("¿Estamos suponiendo", "are we assuming", "Chúng ta đang giả định", "opens the premise check"), s("que las preferencias permanecen estables", "that preferences remain stable", "sở thích không đổi", "states one assumption"), s("o el modelo permite que evolucionen?", "or does the model allow them to evolve", "hay mô hình cho phép chúng phát triển?", "states the alternative")]),
    q("Separating levels", "La explicación funciona en el plano descriptivo, pero aún falta justificar la recomendación normativa.", "The explanation works descriptively, but the normative recommendation still needs justification.", "Lời giải thích phù hợp ở bình diện mô tả, nhưng khuyến nghị chuẩn tắc vẫn cần được biện minh.", "descriptive versus normative", [s("La explicación funciona en el plano descriptivo", "the explanation works descriptively", "Lời giải thích phù hợp ở bình diện mô tả", "accepts one level"), s("pero aún falta justificar", "but it still remains to justify", "nhưng vẫn cần được biện minh", "marks the missing argument"), s("la recomendación normativa", "the normative recommendation", "khuyến nghị chuẩn tắc", "identifies the distinct level")]),
  ]],
  [69, "Humor and wordplay", [
    q("Layered ambiguity", "La gracia reside en que 'banco' activa a la vez la imagen del dinero y la de sentarse.", "The humor lies in 'banco' activating both money and sitting at once.", "Cái hay nằm ở chỗ 'banco' đồng thời gợi tiền bạc và chỗ ngồi.", "lexical ambiguity", [s("La gracia reside en que", "the humor lies in", "Cái hay nằm ở chỗ", "introduces the mechanism"), s("'banco' activa a la vez", "'banco' activates at once", "'banco' đồng thời gợi", "identifies the ambiguous form"), s("la imagen del dinero y la de sentarse", "the image of money and that of sitting", "tiền bạc và chỗ ngồi", "names both readings")]),
    q("Sound-based play", "El efecto no se traduce literalmente porque depende de dos palabras que casi suenan igual.", "The effect cannot be translated literally because it depends on two words that sound almost alike.", "Hiệu ứng không thể dịch sát chữ vì phụ thuộc vào hai từ có âm gần giống nhau.", "phonological wordplay", [s("El efecto no se traduce literalmente", "the effect cannot be translated literally", "Hiệu ứng không thể dịch sát chữ", "states the translation limit"), s("porque depende de dos palabras", "because it depends on two words", "vì phụ thuộc vào hai từ", "introduces the mechanism"), s("que casi suenan igual", "that sound almost alike", "có âm gần giống nhau", "names the sound relation")]),
    q("Timing the joke", "La pausa antes de la última palabra obliga al oyente a construir una expectativa equivocada.", "The pause before the final word makes the listener build the wrong expectation.", "Khoảng dừng trước từ cuối khiến người nghe hình thành một kỳ vọng sai.", "pragmatic timing", [s("La pausa antes de la última palabra", "the pause before the final word", "Khoảng dừng trước từ cuối", "identifies the timing device"), s("obliga al oyente a construir", "makes the listener build", "khiến người nghe hình thành", "states its cognitive effect"), s("una expectativa equivocada", "the wrong expectation", "một kỳ vọng sai", "sets up the reversal")]),
    q("Judging translatability", "En vez de copiar el juego verbal, la versión recrea una sorpresa equivalente en la otra lengua.", "Instead of copying the wordplay, the version recreates an equivalent surprise in the other language.", "Thay vì sao chép lối chơi chữ, bản dịch tái tạo một bất ngờ tương đương trong ngôn ngữ kia.", "functional translation of humor", [s("En vez de copiar el juego verbal", "instead of copying the wordplay", "Thay vì sao chép lối chơi chữ", "rejects formal imitation"), s("la versión recrea", "the version recreates", "bản dịch tái tạo", "states the translation strategy"), s("una sorpresa equivalente en la otra lengua", "an equivalent surprise in the other language", "một bất ngờ tương đương trong ngôn ngữ kia", "preserves the effect")]),
  ]],
  [70, "Cultural subtext", [
    q("Historical echo", "La frase evoca un episodio histórico que convierte una observación cotidiana en una advertencia política.", "The phrase evokes a historical episode that turns an everyday observation into a political warning.", "Câu nói gợi lại một sự kiện lịch sử, biến nhận xét thường ngày thành lời cảnh báo chính trị.", "historical allusion", [s("La frase evoca un episodio histórico", "the phrase evokes a historical episode", "Câu nói gợi lại một sự kiện lịch sử", "identifies the allusion"), s("que convierte una observación cotidiana", "that turns an everyday observation", "biến nhận xét thường ngày", "states the surface form"), s("en una advertencia política", "into a political warning", "thành lời cảnh báo chính trị", "reveals the subtext")]),
    q("Regional subtext", "Para un hablante local, el diminutivo expresa cercanía; fuera de la región podría parecer condescendiente.", "For a local speaker, the diminutive expresses closeness; outside the region it might seem condescending.", "Với người địa phương, dạng từ thu nhỏ biểu thị sự gần gũi; ngoài vùng có thể nghe trịch thượng.", "regional pragmatic contrast", [s("Para un hablante local", "for a local speaker", "Với người địa phương", "sets the insider frame"), s("el diminutivo expresa cercanía", "the diminutive expresses closeness", "dạng từ thu nhỏ biểu thị sự gần gũi", "states the local meaning"), s("fuera de la región podría parecer condescendiente", "outside the region it might seem condescending", "ngoài vùng có thể nghe trịch thượng", "marks the shifted reception")]),
    q("Compressed hierarchy", "La elección del pronombre sitúa a los interlocutores dentro de una relación de edad, respeto y familiaridad.", "The pronoun choice positions the speakers within a relationship of age, respect, and familiarity.", "Việc chọn đại từ đặt người nói vào quan hệ tuổi tác, tôn trọng và thân mật.", "social deixis", [s("La elección del pronombre", "the pronoun choice", "Việc chọn đại từ", "identifies the grammatical signal"), s("sitúa a los interlocutores", "positions the speakers", "đặt người nói", "states its social work"), s("dentro de una relación de edad, respeto y familiaridad", "within age, respect, and familiarity", "vào quan hệ tuổi tác, tôn trọng và thân mật", "names the encoded dimensions")]),
    q("Interpreting ellipsis", "Lo que se omite no es irrelevante: se da por compartido y, por eso mismo, refuerza la pertenencia.", "What is omitted is not irrelevant; it is treated as shared and thereby reinforces belonging.", "Điều bị lược bỏ không phải không quan trọng; nó được coi là hiểu chung và vì thế củng cố cảm giác thuộc về.", "shared-context omission", [s("Lo que se omite no es irrelevante", "what is omitted is not irrelevant", "Điều bị lược bỏ không phải không quan trọng", "rejects absence as insignificance"), s("se da por compartido", "it is treated as shared", "nó được coi là hiểu chung", "states the common-ground assumption"), s("y, por eso mismo, refuerza la pertenencia", "and thereby reinforces belonging", "và vì thế củng cố cảm giác thuộc về", "names the social effect")]),
  ]],
  [71, "Personal voice", [
    q("Measured conviction", "No pretendo tener la última palabra; sí quiero dejar claro desde dónde hablo.", "I do not claim the final word; I do want to make clear where I speak from.", "Tôi không cho rằng mình có lời cuối cùng; nhưng muốn nói rõ mình đang nói từ vị trí nào.", "positioned voice", [s("No pretendo tener la última palabra", "I do not claim the final word", "Tôi không cho rằng mình có lời cuối cùng", "rejects absolute authority"), s("sí quiero dejar claro", "I do want to make clear", "nhưng muốn nói rõ", "adds deliberate emphasis"), s("desde dónde hablo", "where I speak from", "mình đang nói từ vị trí nào", "states situated perspective")]),
    q("Rhythmic intimacy", "A veces basta una pregunta honesta, una pausa, la disposición a no defenderse enseguida.", "Sometimes an honest question, a pause, and a willingness not to defend oneself immediately are enough.", "Đôi khi chỉ cần một câu hỏi chân thành, một khoảng lặng, và sự sẵn lòng không tự vệ ngay.", "personal cadence", [s("A veces basta", "sometimes it is enough", "Đôi khi chỉ cần", "opens a restrained claim"), s("una pregunta honesta, una pausa", "an honest question, a pause", "một câu hỏi chân thành, một khoảng lặng", "builds a rhythmic list"), s("la disposición a no defenderse enseguida", "the willingness not to defend oneself immediately", "và sự sẵn lòng không tự vệ ngay", "lands on the relational practice")]),
    q("Public clarity", "Mi posición nace de una convicción sencilla: ninguna eficiencia compensa la pérdida de humanidad.", "My position grows from a simple conviction: no efficiency compensates for a loss of humanity.", "Quan điểm của tôi xuất phát từ một niềm tin đơn giản: không hiệu quả nào bù đắp được sự mất mát tính người.", "signature conviction", [s("Mi posición nace de una convicción sencilla", "my position grows from a simple conviction", "Quan điểm của tôi xuất phát từ một niềm tin đơn giản", "locates the voice in a value"), s("ninguna eficiencia compensa", "no efficiency compensates", "không hiệu quả nào bù đắp được", "states the categorical judgment"), s("la pérdida de humanidad", "a loss of humanity", "sự mất mát tính người", "names the protected value")]),
    q("Self-editing voice", "La frase era elegante, pero no era mía; la reescribí hasta reconocerme en ella.", "The sentence was elegant, but it was not mine; I rewrote it until I recognized myself in it.", "Câu văn tao nhã nhưng không phải của tôi; tôi viết lại cho đến khi nhận ra chính mình trong đó.", "authentic revision", [s("La frase era elegante, pero no era mía", "the sentence was elegant, but it was not mine", "Câu văn tao nhã nhưng không phải của tôi", "distinguishes polish from authenticity"), s("la reescribí", "I rewrote it", "tôi viết lại", "states the editorial action"), s("hasta reconocerme en ella", "until I recognized myself in it", "cho đến khi nhận ra chính mình trong đó", "sets the personal standard")]),
  ]],
  [72, "C2 integration and maintenance", [
    q("Integrated precision", "La objeción es atendible, aunque afecta a la aplicación del principio y no al principio mismo.", "The objection deserves consideration, though it concerns application of the principle rather than the principle itself.", "Phản đối này đáng được xem xét, dù nó liên quan đến việc áp dụng nguyên tắc chứ không phải bản thân nguyên tắc.", "fine conceptual distinction", [s("La objeción es atendible", "the objection deserves consideration", "Phản đối này đáng được xem xét", "grants legitimacy"), s("aunque afecta a la aplicación del principio", "though it concerns application of the principle", "dù nó liên quan đến việc áp dụng nguyên tắc", "locates the concern"), s("y no al principio mismo", "and not the principle itself", "chứ không phải bản thân nguyên tắc", "protects the distinction")]),
    q("Integrated reformulation", "Si lo expreso sin tecnicismos: el sistema aprende del pasado, pero también hereda sus sesgos.", "Without technical language: the system learns from the past, but it also inherits its biases.", "Nói không dùng thuật ngữ chuyên môn: hệ thống học từ quá khứ nhưng cũng thừa hưởng thiên kiến của nó.", "expert mediation", [s("Si lo expreso sin tecnicismos", "if I put it without technical language", "Nói không dùng thuật ngữ chuyên môn", "signals audience adaptation"), s("el sistema aprende del pasado", "the system learns from the past", "hệ thống học từ quá khứ", "states the accessible mechanism"), s("pero también hereda sus sesgos", "but also inherits its biases", "nhưng cũng thừa hưởng thiên kiến của nó", "preserves the critical consequence")]),
    q("Integrated cultural judgment", "La respuesta es gramaticalmente impecable, pero socialmente torpe en una relación tan cercana.", "The response is grammatically flawless but socially awkward in such a close relationship.", "Câu trả lời hoàn hảo về ngữ pháp nhưng vụng về về mặt xã hội trong một mối quan hệ thân thiết như vậy.", "grammar versus pragmatics", [s("La respuesta es gramaticalmente impecable", "the response is grammatically flawless", "Câu trả lời hoàn hảo về ngữ pháp", "acknowledges formal accuracy"), s("pero socialmente torpe", "but socially awkward", "nhưng vụng về về mặt xã hội", "identifies pragmatic failure"), s("en una relación tan cercana", "in such a close relationship", "trong một mối quan hệ thân thiết như vậy", "sets the decisive context")]),
    q("Lifelong maintenance", "La fluidez no es un punto final, sino la capacidad de seguir aprendiendo sin perder la propia voz.", "Fluency is not an endpoint, but the capacity to keep learning without losing one's own voice.", "Sự lưu loát không phải điểm kết thúc mà là khả năng tiếp tục học mà không đánh mất giọng nói riêng.", "C2 maintenance", [s("La fluidez no es un punto final", "fluency is not an endpoint", "Sự lưu loát không phải điểm kết thúc", "rejects static completion"), s("sino la capacidad de seguir aprendiendo", "but the capacity to keep learning", "mà là khả năng tiếp tục học", "defines durable mastery"), s("sin perder la propia voz", "without losing one's own voice", "mà không đánh mất giọng nói riêng", "preserves authentic expression")]),
  ]],
];

let previous = "c1-u60-4-c1-reflection";
const lessons = [];
for (const [unitNumber, unitTitle, items] of groups) for (const [index, item] of items.entries()) {
  const slug = item.title.toLocaleLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
  const objectiveId = `c2-u${unitNumber}-${index + 1}-${slug}`;
  lessons.push({ id: `${objectiveId}-lesson`, objectiveId, prerequisites: [previous], unit: unitNumber, lesson: index + 1,
    unitTitle, title: item.title, skill: `${unitTitle.toLocaleLowerCase()}: ${item.focus}`, spanish: item.spanish, english: item.english,
    vietnamese: item.vietnamese, focus: item.focus, pattern: item.focus, bridgePattern: item.focus,
    units: item.units.map((entry) => ({ ...entry, part: "Contextual phrase",
      spanishForm: `In this C2 sentence, “${entry.spanish}” realizes ${entry.role}; its lexical choice, syntax, mood, aspect, register, implication, and stylistic effect are interpreted in the complete context.`,
      vietnameseForm: `In this C2 sentence, “${entry.vietnamese}” realizes ${entry.role}; analytic order, particles, register, implication, and culturally situated effect are interpreted in the complete context.` })) });
  previous = objectiveId;
}

export default { id: "c2-core-1", version: 1, level: "C2", lessons };
