import type { FoundationLanguage } from "../multilingual-foundation";

// Draft translations. Editorial sign-off is required before release.
const keys = ["title", "intro", "start", "check", "limit", "study", "recognize", "write", "typed", "assisted", "inputNote", "keyboard", "retry", "correct", "continue", "chooseAgain", "summary", "reading", "writing", "supported", "return", "model"] as const;
export const literacyTranslations: Record<FoundationLanguage, readonly string[]> = {
 en: ["Your starting point", "How familiar are you with this language’s writing system? Spoken familiarity and literacy may differ.", "Start from the foundations", "Check what I already know", "Four introductory expressions only—not a full script course or proficiency certificate.", "Read the expression and compare its meaning. Notice its written forms.", "Choose the meaning.", "Write the meaning in the language shown.", "Typing without assistance", "Dictation or other assistance", "Input method is self-reported. Assisted input does not demonstrate independent writing.", "Keyboard setup", "This does not match the draft’s accepted answer. Try again or view the model.", "This matches the accepted answer.", "Continue", "Choose another starting point", "Introductory practice complete", "Recognition without help", "Writing without help", "Supported practice", "Return to lessons", "Show the model"],
 es: ["Tu punto de partida", "¿Qué familiaridad tienes con la escritura de este idioma? Hablarlo y saber leerlo no son lo mismo.", "Empezar por los fundamentos", "Comprobar lo que ya sé", "Solo cuatro expresiones introductorias: no es un curso completo de escritura ni un certificado de nivel.", "Lee la expresión y compara su significado. Observa cómo se escribe.", "Elige el significado.", "Escribe el significado en el idioma indicado.", "Escritura sin ayuda", "Dictado u otra ayuda", "El método de entrada lo declaras tú. La ayuda no demuestra escritura independiente.", "Configurar el teclado", "No coincide con la respuesta aceptada del borrador. Inténtalo de nuevo o consulta el modelo.", "Coincide con la respuesta aceptada.", "Continuar", "Elegir otro punto de partida", "Práctica introductoria completada", "Reconocimiento sin ayuda", "Escritura sin ayuda", "Práctica con apoyo", "Volver a las lecciones", "Mostrar el modelo"],
 vi: ["Điểm bắt đầu của bạn", "Bạn quen với hệ chữ viết của ngôn ngữ này đến mức nào? Biết nói không đồng nghĩa với biết đọc viết.", "Bắt đầu từ nền tảng", "Kiểm tra những gì đã biết", "Chỉ có bốn cách diễn đạt nhập môn, không phải khóa học chữ viết đầy đủ hay chứng nhận trình độ.", "Đọc câu và so sánh ý nghĩa. Chú ý cách viết.", "Chọn ý nghĩa.", "Viết ý nghĩa bằng ngôn ngữ được chỉ định.", "Tự gõ, không hỗ trợ", "Đọc chính tả hoặc hỗ trợ khác", "Bạn tự khai báo cách nhập. Nhập có hỗ trợ không chứng minh khả năng tự viết.", "Thiết lập bàn phím", "Chưa khớp với đáp án được chấp nhận trong bản nháp. Hãy thử lại hoặc xem mẫu.", "Khớp với đáp án được chấp nhận.", "Tiếp tục", "Chọn điểm bắt đầu khác", "Hoàn thành luyện tập nhập môn", "Nhận biết không hỗ trợ", "Viết không hỗ trợ", "Luyện tập có hỗ trợ", "Trở lại bài học", "Xem mẫu"],
 fr: ["Votre point de départ", "Connaissez-vous le système d’écriture de cette langue ? La parler et savoir la lire sont deux aptitudes distinctes.", "Commencer par les bases", "Vérifier mes acquis", "Quatre expressions introductives seulement : ni un cours complet d’écriture ni une certification.", "Lisez l’expression et comparez son sens. Observez sa forme écrite.", "Choisissez le sens.", "Écrivez le sens dans la langue indiquée.", "Saisie sans aide", "Dictée ou autre aide", "Vous déclarez le mode de saisie. Une saisie assistée ne démontre pas une écriture autonome.", "Configurer le clavier", "Cela ne correspond pas à une réponse acceptée dans ce brouillon. Réessayez ou consultez le modèle.", "Cela correspond à une réponse acceptée.", "Continuer", "Choisir un autre point de départ", "Pratique introductive terminée", "Reconnaissance sans aide", "Écriture sans aide", "Pratique accompagnée", "Revenir aux leçons", "Afficher le modèle"],
 pt: ["Seu ponto de partida", "Você conhece o sistema de escrita deste idioma? Saber falar e saber ler são capacidades distintas.", "Começar pelos fundamentos", "Verificar o que já sei", "Apenas quatro expressões introdutórias: não é um curso completo de escrita nem uma certificação.", "Leia a expressão e compare o significado. Observe a forma escrita.", "Escolha o significado.", "Escreva o significado no idioma indicado.", "Digitação sem ajuda", "Ditado ou outra ajuda", "Você informa o método de entrada. A entrada assistida não demonstra escrita independente.", "Configurar o teclado", "Não corresponde a uma resposta aceita neste rascunho. Tente novamente ou veja o modelo.", "Corresponde a uma resposta aceita.", "Continuar", "Escolher outro ponto de partida", "Prática introdutória concluída", "Reconhecimento sem ajuda", "Escrita sem ajuda", "Prática com apoio", "Voltar às lições", "Mostrar o modelo"],
 de: ["Dein Ausgangspunkt", "Wie vertraut bist du mit dem Schriftsystem dieser Sprache? Sprechen und Lesen sind unterschiedliche Fähigkeiten.", "Mit den Grundlagen beginnen", "Vorwissen überprüfen", "Nur vier einführende Ausdrücke – kein vollständiger Schriftkurs und kein Sprachnachweis.", "Lies den Ausdruck und vergleiche seine Bedeutung. Achte auf die Schriftformen.", "Wähle die Bedeutung.", "Schreibe die Bedeutung in der angegebenen Sprache.", "Tippen ohne Hilfe", "Diktat oder andere Hilfe", "Die Eingabemethode gibst du selbst an. Unterstützte Eingabe belegt kein selbstständiges Schreiben.", "Tastatur einrichten", "Das entspricht keiner akzeptierten Antwort dieses Entwurfs. Versuche es erneut oder zeige die Vorlage.", "Das entspricht einer akzeptierten Antwort.", "Weiter", "Anderen Ausgangspunkt wählen", "Einführende Übung abgeschlossen", "Erkennen ohne Hilfe", "Schreiben ohne Hilfe", "Unterstützte Übung", "Zurück zu den Lektionen", "Vorlage zeigen"],
 it: ["Il tuo punto di partenza", "Conosci il sistema di scrittura di questa lingua? Saper parlare e saper leggere sono capacità diverse.", "Iniziare dalle basi", "Verificare ciò che so già", "Solo quattro espressioni introduttive: non è un corso completo di scrittura né una certificazione.", "Leggi l’espressione e confronta il significato. Osserva le forme scritte.", "Scegli il significato.", "Scrivi il significato nella lingua indicata.", "Digitazione senza aiuto", "Dettatura o altro aiuto", "Dichiari tu il metodo di inserimento. L’inserimento assistito non dimostra scrittura autonoma.", "Configurare la tastiera", "Non corrisponde a una risposta accettata in questa bozza. Riprova o guarda il modello.", "Corrisponde a una risposta accettata.", "Continua", "Scegliere un altro punto di partenza", "Pratica introduttiva completata", "Riconoscimento senza aiuto", "Scrittura senza aiuto", "Pratica assistita", "Tornare alle lezioni", "Mostrare il modello"],
 zh: ["你的起点", "你对这门语言的书写系统有多熟悉？会说与会读写是不同的能力。", "从基础开始", "检验已有能力", "这里只练习四个入门表达，不是完整的文字课程，也不是语言能力认证。", "阅读表达并比较意思，留意书写形式。", "选择对应的意思。", "用所示语言写出意思。", "独立打字", "语音输入或其他辅助", "输入方式由你自行申报。辅助输入不能证明独立书写能力。", "设置键盘", "与草稿中收录的答案不符。请重试或查看示例。", "与收录的答案相符。", "继续", "重新选择起点", "入门练习已完成", "独立识读", "独立书写", "辅助练习", "返回课程", "查看示例"],
 ja: ["あなたの出発点", "この言語の文字体系にどのくらい慣れていますか？話す力と読み書きの力は異なります。", "基礎から始める", "今の力を確かめる", "入門表現を四つ練習します。文字体系全体のコースや能力認定ではありません。", "表現を読み、意味を比べ、文字の形に注目してください。", "意味を選んでください。", "表示された言語で意味を書いてください。", "補助なしで入力", "音声入力・その他の補助", "入力方法は自己申告です。補助付き入力は自力で書く力の証明にはなりません。", "キーボード設定", "この草案の許容解答と一致しません。再試行するか例を見てください。", "許容解答と一致しています。", "続ける", "出発点を選び直す", "入門練習が完了しました", "補助なしの読解", "補助なしの筆記", "補助付きの練習", "レッスンに戻る", "例を見る"],
 ko: ["나의 출발점", "이 언어의 문자 체계에 얼마나 익숙한가요? 말하기와 읽고 쓰기는 다른 능력입니다.", "기초부터 시작하기", "이미 아는 것 확인하기", "입문 표현 네 개만 연습합니다. 전체 문자 과정이나 언어 능력 인증이 아닙니다.", "표현을 읽고 뜻을 비교하며 글자 형태를 살펴보세요.", "뜻을 고르세요.", "표시된 언어로 뜻을 쓰세요.", "도움 없이 입력", "음성 입력 또는 다른 도움", "입력 방법은 직접 신고합니다. 도움을 받은 입력은 독립적인 쓰기 능력을 증명하지 않습니다.", "키보드 설정", "초안에 등록된 답과 일치하지 않습니다. 다시 시도하거나 예문을 보세요.", "등록된 답과 일치합니다.", "계속", "출발점 다시 선택하기", "입문 연습 완료", "도움 없는 읽기", "도움 없는 쓰기", "도움을 받은 연습", "수업으로 돌아가기", "예문 보기"],
 ar: ["نقطة بدايتك", "ما مدى معرفتك بنظام كتابة هذه اللغة؟ القدرة على التحدث تختلف عن القراءة والكتابة.", "البدء من الأساسيات", "التحقق مما أعرفه", "أربعة تعبيرات تمهيدية فقط، وليست دورة كتابة كاملة أو شهادة كفاءة.", "اقرأ التعبير وقارن معناه. لاحظ أشكاله المكتوبة.", "اختر المعنى.", "اكتب المعنى باللغة الموضحة.", "كتابة دون مساعدة", "إملاء صوتي أو مساعدة أخرى", "أنت تحدد طريقة الإدخال. الإدخال بمساعدة لا يثبت القدرة على الكتابة المستقلة.", "إعداد لوحة المفاتيح", "لا يطابق إجابة مقبولة في المسودة. حاول مجددًا أو اعرض النموذج.", "يطابق إجابة مقبولة.", "متابعة", "اختيار نقطة بداية أخرى", "اكتمل التدريب التمهيدي", "التعرف دون مساعدة", "الكتابة دون مساعدة", "تدريب بمساعدة", "العودة إلى الدروس", "عرض النموذج"],
 hi: ["आपकी शुरुआत", "आप इस भाषा की लिपि से कितने परिचित हैं? बोलना और पढ़ना-लिखना अलग क्षमताएँ हैं।", "बुनियाद से शुरू करें", "जो आता है उसे जाँचें", "केवल चार शुरुआती अभिव्यक्तियाँ—यह पूरी लिपि का पाठ्यक्रम या दक्षता प्रमाणपत्र नहीं है।", "अभिव्यक्ति पढ़ें और अर्थ की तुलना करें। लिखित रूपों पर ध्यान दें।", "अर्थ चुनें।", "दिखाई गई भाषा में अर्थ लिखें।", "बिना सहायता टाइप करना", "बोलकर लिखना या अन्य सहायता", "इनपुट विधि आप स्वयं बताते हैं। सहायता से लिखा पाठ स्वतंत्र लेखन क्षमता का प्रमाण नहीं है।", "कीबोर्ड सेटअप", "यह मसौदे के स्वीकृत उत्तर से मेल नहीं खाता। फिर प्रयास करें या उदाहरण देखें।", "यह स्वीकृत उत्तर से मेल खाता है।", "आगे बढ़ें", "दूसरी शुरुआत चुनें", "शुरुआती अभ्यास पूरा हुआ", "बिना सहायता पहचान", "बिना सहायता लेखन", "सहायता के साथ अभ्यास", "पाठों पर लौटें", "उदाहरण दिखाएँ"],
 ru: ["Ваша отправная точка", "Насколько вам знакома письменность этого языка? Устная речь и грамотность — разные навыки.", "Начать с основ", "Проверить свои знания", "Только четыре вводных выражения — не полный курс письменности и не подтверждение уровня.", "Прочитайте выражение и сравните значение. Обратите внимание на письменные формы.", "Выберите значение.", "Передайте смысл письменно на указанном языке.", "Ввод без помощи", "Диктовка или другая помощь", "Способ ввода вы указываете сами. Ввод с помощью не подтверждает самостоятельное письмо.", "Настройка клавиатуры", "Ответ не совпадает с принятым вариантом в черновике. Попробуйте снова или посмотрите образец.", "Ответ совпадает с принятым вариантом.", "Продолжить", "Выбрать другую отправную точку", "Вводная практика завершена", "Распознавание без помощи", "Письмо без помощи", "Практика с поддержкой", "Вернуться к урокам", "Показать образец"],
};
export function literacyCopy(language: FoundationLanguage): Record<typeof keys[number], string> {
 const values = literacyTranslations[language];
 if (values.length !== keys.length || values.some(value => !value.trim())) throw new Error(`Incomplete literacy translation: ${language}`);
 return Object.fromEntries(keys.map((key, i) => [key, values[i]])) as Record<typeof keys[number], string>;
}
